using System.Linq;
using System.Numerics;
using Content.Client.Interaction;
using Content.Client.Stylesheets;
using Content.Shared._White.Humanoid.Markings.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._White.Humanoid.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class MarkingOrderer : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private LayerDragDropBeacon? _dragTarget;

    private readonly DragDropHelper<LayerMarkingDragged> _dragDropHelper;
    private readonly List<LayerDragDropBeacon> _beacons = new();
    private readonly MarkingsViewModel _model;
    private readonly ProtoId<MarkingCategoryPrototype> _category;

    public MarkingOrderer(MarkingsViewModel model, ProtoId<MarkingCategoryPrototype> category)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _dragDropHelper = new(OnBeginDrag, OnContinueDrag, OnEndDrag);
        _model = model;
        _category = category;

        UpdateItems();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _model.MarkingsReset += UpdateItems;
        _model.MarkingsChanged += MarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _model.MarkingsReset -= UpdateItems;
        _model.MarkingsChanged -= MarkingsChanged;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _dragDropHelper.Update(args.DeltaSeconds);
    }

    private void MarkingsChanged(ProtoId<MarkingCategoryPrototype> category)
    {
        if (_category != category)
            return;

        UpdateItems();
    }

    private bool OnBeginDrag()
    {
        var (item, container) = _dragDropHelper.Dragged;

        container.Visible = false;
        item.Orphan();
        item.DefaultCursorShape = CursorShape.Hand;
        UserInterfaceManager.PopupRoot.AddChild(item);
        LayoutContainer.SetPosition(item, UserInterfaceManager.MousePositionScaled.Position - new Vector2(32, 32));
        return true;
    }

    private bool OnContinueDrag(float frameTime)
    {
        var item= _dragDropHelper.Dragged.Item;

        LayoutContainer.SetPosition(item, UserInterfaceManager.MousePositionScaled.Position - new Vector2(32, 32));

        var closestBeacon = _beacons.MinBy(beacon => (UserInterfaceManager.MousePositionScaled.Position - beacon.GlobalPosition).LengthSquared());
        if (closestBeacon == _dragTarget)
            return true;

        _dragTarget?.UnBecomeTarget();
        _dragTarget = closestBeacon;
        _dragTarget?.BecomeTarget();

        return true;
    }

    private void OnEndDrag()
    {
        var (item, container) = _dragDropHelper.Dragged;

        container.Visible = true;
        item.Orphan();
        container.AddChild(item);
        _dragTarget?.UnBecomeTarget();

        if (_dragTarget == null)
            return;

        _model.ChangeMarkingOrder(_category, item.MarkingId, _dragTarget.CandidatePosition, _dragTarget.Index);
    }

    private void OnItemPressed(GUIBoundKeyEventArgs args, MarkingItem item, LayerMarkingItemContainer container)
    {
        _dragDropHelper.MouseDown(new(item, container));
    }

    private void OnItemUnpressed(GUIBoundKeyEventArgs args, MarkingItem item)
    {
        _dragDropHelper.EndDrag();
    }

    private void UpdateItems()
    {
        Items.RemoveAllChildren();
        _beacons.Clear();

        if (!_model.TryGetSelectedMarkings(_category, out var markings))
            return;

        for (var i = 0; i < markings.Count; i++)
        {
            var marking = markings[i];

            var container = new LayerMarkingItemContainer();
            container.Margin = new(4);

            var item = new MarkingItem(false, _prototype.Index(marking.Id), _model, _category);
            item.DefaultCursorShape = CursorShape.Hand;
            item.Pressed += (args, control) => OnItemPressed(args, control, container);
            item.Unpressed += OnItemUnpressed;

            container.AddChild(item);

            var before = new LayerDragDropBeacon(CandidatePosition.Before, i);
            var after = new LayerDragDropBeacon(CandidatePosition.After, i);
            _beacons.Add(before);
            _beacons.Add(after);

            Items.AddChild(before);
            Items.AddChild(container);
            Items.AddChild(after);
        }
    }
}

internal readonly record struct LayerMarkingDragged(MarkingItem Item, LayerMarkingItemContainer Container);

internal sealed class LayerMarkingItemContainer : PanelContainer
{
    public LayerMarkingItemContainer()
    {
        SetHeight = 64;
        HorizontalExpand = true;
    }
}

internal sealed class LayerDragDropBeacon(CandidatePosition position, int index) : PanelContainer
{
    public readonly CandidatePosition CandidatePosition = position;
    public readonly int Index = index;

    public void BecomeTarget()
    {
        SetHeight = 64;
        HorizontalExpand = true;
        SetOnlyStyleClass(StyleNano.StyleClassPanelDropTarget);
    }

    public void UnBecomeTarget()
    {
        SetHeight = float.NaN;
        RemoveStyleClass(StyleNano.StyleClassPanelDropTarget);
    }
}
