using System.Linq;
using Content.Client.Guidebook.Controls;
using Content.Shared._White.Humanoid.Markings.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._White.Humanoid.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class MarkingItem : BoxContainer, ISearchableControl
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private List<ColorSelectorSliders>? _colorSliders;

    private readonly bool _interactive;
    private readonly MarkingPrototype _marking;
    private readonly MarkingsViewModel _model;
    private readonly ProtoId<MarkingCategoryPrototype> _category;
    private readonly SpriteSystem _sprite;

    public event Action<GUIBoundKeyEventArgs, MarkingItem>? Pressed;
    public event Action<GUIBoundKeyEventArgs, MarkingItem>? Unpressed;

    public ProtoId<MarkingPrototype> MarkingId => _marking.ID;

    public MarkingItem(bool interactive, MarkingPrototype marking, MarkingsViewModel model, ProtoId<MarkingCategoryPrototype> category)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _interactive = interactive;
        _marking = marking;
        _model = model;
        _category = category;
        _sprite = _entity.System<SpriteSystem>();

        UpdateData();
        UpdateSelection();

        SelectButton.OnPressed += SelectButtonPressed;
        ColorsButton.OnPressed += ColorsButtonPressed;

        OnKeyBindDown += OnPressed;
        OnKeyBindUp += OnUnpressed;

        if (interactive)
            return;

        SelectButton.MouseFilter = MouseFilterMode.Ignore;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _model.MarkingsReset += UpdateSelection;
        _model.MarkingsChanged += MarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _model.MarkingsReset -= UpdateSelection;
        _model.MarkingsChanged -= MarkingsChanged;
    }

    public bool CheckMatchesSearch(string query)
    {
        return Loc.GetString($"marking-{_marking.ID}").Contains(query, StringComparison.OrdinalIgnoreCase);
    }

    private void ColorsButtonPressed(BaseButton.ButtonEventArgs args)
    {
        ColorsContainer.Visible = ColorsButton.Pressed;

        if (_colorSliders is not null)
            return;

        if (!_model.TryGetMarkings(_marking.ID, out var markings))
            return;

        _colorSliders = new();

        for (var i = 0; i < _marking.Markings.Count; i++)
        {
            var container = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            ColorsContainer.AddChild(container);

            var selector = new ColorSelectorSliders();
            selector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;

            var label = _marking.Markings[i].Sprite switch
            {
                SpriteSpecifier.Rsi rsi => Loc.GetString($"marking-{_marking.ID}-{rsi.RsiState}"),
                SpriteSpecifier.Texture texture => Loc.GetString($"marking-{_marking.ID}-{texture.TexturePath.Filename}"),
                _ => throw new InvalidOperationException("SpriteSpecifier not of known type"),
            };

            container.AddChild(new Label { Text = label });
            container.AddChild(selector);

            selector.Color = markings[i].Color;

            _colorSliders.Add(selector);

            var colorIndex = i;
            selector.OnColorChanged += _ =>
            {
                _model.TrySetMarkingColor(_marking.ID, colorIndex, selector.Color);
            };
        }
    }

    private void MarkingsChanged(ProtoId<MarkingCategoryPrototype> category)
    {
        if (_category != category)
            return;

        UpdateSelection();
    }

    private void OnPressed(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        Pressed?.Invoke(args, this);
    }

    private void OnUnpressed(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        Unpressed?.Invoke(args, this);
    }

    private void SelectButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (!_interactive)
        {
            SelectButton.Pressed = false;
            return;
        }

        if (_model.TryGetMarkings(_marking.ID, out _))
        {
            if (_model.TryDeselectMarking(_marking.ID))
                return;

            SelectButton.Pressed = true;
            return;
        }

        if (_model.TrySelectMarking(_marking.ID))
            return;

        SelectButton.Pressed = false;
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    private void UpdateData()
    {
        MarkingTexture.Textures = _marking.Markings.Select(data => _sprite.Frame0(data.Sprite)).ToList();
        SelectButton.Text = Loc.GetString($"marking-{_marking.ID}");
    }

    private void UpdateSelection()
    {
        var selected = _model.TryGetMarkings(_marking.ID, out var markings);
        SelectButton.Pressed = selected && _interactive;
        ColorsButton.Visible = selected && _interactive && _model.IsMarkingColorCustomizable(_marking.ID);

        if (!selected || !_interactive)
        {
            ColorsButton.Pressed = false;
            ColorsContainer.Visible = false;
        }

        if (markings is null || markings.Count == 0 || _colorSliders is not { } sliders)
            return;

        for (var i = 0; i < _marking.Markings.Count; i++)
        {
            sliders[i].Color = markings[i].Color;
        }
    }
}
