book-text-botany =
    {"                                1. Botany and its Basics"}
    {""}
    {"If you have a sufficient variety of plant seeds, this book can help you understand the basics of botany and perhaps come to love it. We also recommend purchasing trays from NanoTrasen Corporation and sterile cotton swabs."}
    {""}
    {""}
    {"  1.1 You have NT trays at your disposal, but what's their purpose? These trays help you understand the needs of plants, as they are capable of reading basic plant data. By examining the tray, you can see several indicator lights, each corresponding to a plant's needs. We'll go from left to right:"}
    {"      • The first green light indicates that the fruits are fully ripe and ready for harvest."}
    {"      • The second red light indicates that the plant is half-dead, either due to old age, external circumstances, or because the plant hasn't received water or nutrients for a long time. Plant fruits can help restore it; they slightly heal the plant and this should help."}
    {"      • The third light will flash red. This means there are either weeds, pests in the tray, or the atmosphere is unsuitable for the plants in the tray. This will gradually harm the plant in the tray."}
    {"      • The fourth will glow yellowish, indicating a need for nutrients."}
    {"      • The fifth, in turn, indicates a need for water."}
    {"    All this is very helpful for your beginnings."}
    {"    We also recommend purchasing a plant analyzer and 2-3 medium-capacity batteries, as the device drains power every second while displaying plant data. This device shows: the plant's maximum lifespan, whether the plant creates or absorbs a specific chemical in the air, fruit size, the chemical composition of the fruits and everything poured into the tray, and whether the plant is seedless."}
    {"    We recommend gathering tools for farming: wire cutters (which are also suitable for wires), a small shovel, a hatchet, small rakes. Suitable chemicals include Robust Harvest, which increases size, but if it starts acting on a plant with a fruit size of 50, then for every milliliter there will be a chance to reduce the number of fruits down to 1; nutrients, which help the plant obtain nourishment."}
    {"    A small tip: if you want to forget about constantly adding water and removing weeds, I advise creating a bot from: 1 standard borg arm, 1 bucket, 1 pair of botany wire cutters, and one motion sensor. I recommend creating two of these; they help remove weeds and water plants while you're away or busy."}
    {""}
    {"  1.2. Let's move on to plant characteristics (genes)"}
    {"    Potency - this denotes fruit size, fruit slip effectiveness, the amount of chemicals in the fruits;"}
    {"    Yield (Number of fruits) - this characteristic is differently related to specific plants. For example, for watermelon seeds, you'll have to crossbreed with other plants or mutate them;"}
    {"    Seedlessness - this is the most important for quickly obtaining a large number of fruits, as there's no need to collect seeds with scissors; this characteristic allows obtaining seeds from the fruit processor;"}
    {"    Endurance - allows the plant to withstand a bad environment longer and have protection against poison, weeds, and pests, i.e., it increases the characteristic that allows ignoring problems until they exceed the tolerable threshold;"}
    {"    Lifespan - this is the age that the plant cannot exceed, but if it happens, the plant will start dying, and only cryoxadone can make the plant younger or turn it into seeds;"}
    {"    Chemical Production - these are the chemicals found specifically in the fruits;"}
    {"    Perennial Growth (Woodiness) - whether the plant can only be harvested with an axe or a scythe."}
    {""}
    {"  1.3. Types of plants with useful characteristics"}
    {"    Cocoa beans - have nutrients, 6 fruits, lifespan 50 years, but the size is very small - this plant is suitable for crossbreeding with its yield and lifespan genes, and by adding 15 milliliters of Robust Harvest you get fruits for fertilizing other plants."}
    {"    Millet, oats, rice - short-lived, fruits can be harvested only once, but they are the fastest growing; also, millet can be crossed with tomatoes or watermelon for faster dough creation, the main thing is to preserve the flour and water."}
    {"    Poppy, thistle, ambrosia, reishi, aloe, bananas - medicinal plants. Thistle, reishi treat poisoning; ambrosia treats burns, slightly helps raise from critical condition from physical damage and speeds up the body, but has an overdose; poppy treats physical damage; bananas satiate, and the chemical composition of the peel helps with bleeding; aloe, when used in a microwave, melts and can be used as a full-fledged ointment for burns."}
    {"    Nettle - the best weapon of a botanist, upon touching the body it injects chemicals from the fruit, but is less effective if the target has clothing."}
    {""}
    {"  1.4. Mutations and how to treat them"}
    {"    Mutations are a form of evolution and degradation in plants; this condition occurs if mutagen is added to the tray. Attention: mutagen is too strong and sometimes because of this, trays gain self-awareness; the manufacturer is not responsible for this! Now I will tell you about the types of mutations and their features: Increase/decrease in potency, this mutation makes the plant larger or smaller, and only with this mutation can you obtain fruits the size of a human; slippery skin mutation, this mutation makes the fruits very slippery, and the slip force depends on the fruit size; bluespace slippery skin, this mutation makes the plant slippery, if someone slips on this fruit, they will likely be teleported within a certain radius, the same will apply to the fruit; appearance of a new chemical, this mutation adds a completely new chemical to the plant's fruits, which will be preserved even if the plant mutates into a new form; reusable harvest/self-harvest, this mutation has 2 stages, the first - if the plant was single-harvest, it allows harvesting fruits multiple times, if the plant already has this function, then upon ripening the fruits will drop by themselves; kudzu, this mutation affects not the plant itself but the weeds, making them so strong that they will soon leave the tray, killing the plant, but you can get rid of it by simply obtaining an identical copy of the plant, and fill the original with fruits so the kudza grows faster, this will cleanse the plant copies; non-viability, a terrible mutation that will soon kill the plant, but 5 milliliters of phalanximine (severely poisons the tray) helps against it; mutation of growth speed acceleration/slowing, fruit ripening acceleration/slowing; production/absorption of a chemical in the air; glowing fruits, the plant and fruits start glowing a random color; seedlessness mutation; and finally, the most important one is the plant species mutation, this mutation changes the type, form, chemical composition of the plant, and sometimes improves properties."}
    {""}
    {"  1.5. Rules of plant crossbreeding"}
    {"    Now we know that plants have genes, genes after mutations, so we can move on to the most important thing - pollinating plants! This section will help create a watermelon with 6 fruits, a long lifespan, or maybe even turn it into a real weapon. First, we need clean swabs. With them, we can transfer genes, but there's a high chance of making the plant seedless, which will slow down the ability to get a large number of seeds. This mechanism is due to the fact that in return we can create an absolute medicine that cures everything, or even a doomsday weapon capable of killing a creature in 2-3 hits. We take a swab and with gentle movements collect pollen from a plant, then sprinkle it on another; afterwards, random genes from the donor will replace the genes of the selected plant. Attention: after pollination, the swab will acquire the genes of the second plant, making it harmful, as it can spoil other plants, and also swabs can only hold genes from one plant. It seems simple, but not quite; there's a chance the plant will lose the ability to receive new genes, and there are two options: continue until this effect passes, or plant a new plant. I advise planting two donor plants, one for genes, and the second a copy of the plant you want to improve; this will help stabilize the plant and preserve the genes/chemicals you need. If your plant is seedless, all is not lost. You can collect plant clippings with scissors, which you plant in a new tray, but this will deal about 1/4 of the plant's maximum health in damage, and the copy of this plant will have the same health level as the plant had at the moment of clipping collection. If you wait until the fruits are ready for harvest, then using scissors, the plant clippings will be completely healthy when planted in another tray."}
    {""}
    {"  1.6. Interactions with chemical equipment"}
    {"    Now you know that you can obtain chemicals that can be given to the chemist for use, but not everyone knows that the centrifuge and electrolyzer in the chemistry lab can be effectively used in botany, and you can even artificially create meat, ignoring animal husbandry. Electrolysis can separate liquid into components, for example, ground-up boards give sugar and carbon, and using liquid oil in a centrifuge you get fats. As a result, we can grow blood tomatoes, mushroom, meaty millet, cocoa beans to create meat (carbon, blood, hydrogen, nutrients, and fat, all 25-10 units each)."}
    {""}
    {"  1.7. Animal husbandry"}
    {"    We know how to speed up the production of the fruits we need, so now we can start breeding animals. First, you will need to build a small fence from rods or wood, and then corral 2 creatures of the same species there - 2 pigs, 2 chickens, 2 geese, etc. Then we separate the species into different enclosures, now we will do our work. Cows, goats eat grasses like millet; other animals and birds eat fruits, vegetables. Next, we must manually feed and water the animals about 10-20 times, after which the animal will trust us and we can leave food and water in buckets within their enclosures. After that, we just need to keep them very close to each other to increase the chance of starting reproduction, and after a few minutes, an egg/small version of the parents will appear. The egg can hatch on its own, but it takes time; I advise increasing the temperature to speed up hatching. It would also be good to give the animals cognizine, then they will independently report when they are hungry."}
    {"    (I was also told in secret that it's possible to create biomass using 3.5 nutrients, 0.5 vitamins, 2 protein, and 2 blood.)"}
    {""}
    {""}
    {""}
    {"  Summary: Thank you for reading this book; it was made to interest you in trying botany and understanding that it's not a job where you have to serve the chef, but a job that provides a lot of new experience. :>"}
