using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class VendingMachineItem : BoxContainer
{
    public VendingMachineItem(EntProtoId entProto, string text, uint price)
    {
        RobustXamlLoader.Load(this);

        ItemPrototype.SetPrototype(entProto);

        UpdateData(text, price);
    }

    public void UpdateData(string text, uint price)
    {
        NameLabel.Text = text;
        if (price > 0)
        {
            PriceLabel.Text = $"{price} эдди.";
            PriceLabel.Visible = true;
        }
        else
        {
            PriceLabel.Visible = false;
        }
    }
}
