# - type: department
#   id: CivilianNC
#   name: Гражданские
#   description: department-CivilianNC-description
#   color: "#999999"
#   roles:
#     - Citizen
#     - Reaper
#     - Fixer
#     - EdgeRunnerSolo

# - type: department
#   id: Militech
#   name: Корпорация Militech
#   description: department-Militech-description
#   color: "#2e4053"
#   roles:
#     - HoSMilitech
#     - HoDMilitech
#     - SquadCommanderMilitech
#     - SecurityMilitech
#     - MedTechM
#     - OperativeMilitech

# - type: department
#   id: Biotech
#   name: Корпорация Biotech
#   description: department-Biotech-description
#   color: "#00d848"
#   roles:
#     - HoSBiotech
#     - HoDBiotech
#     - SquadCommanderBiotech
#     - SecurityBiotech
#     - MedTechB
#     - OperativeBiotech
#     - BotanistBiotech

# - type: department
#   id: NCPD
#   name: NCPD
#   description: department-NCPD-description
#   color: "#1e90ff"
#   roles:
#     - NCPDChief
#     - NCPDOfficer
#     - NCPDSWAT
#     - JobNCPDInspector

# - type: department
#   id: Government
#   name: Мэрия
#   description: department-Government-description
#   color: "#ffb300"
#   roles:
#     - Mayor

# - type: department
#   id: Builders
#   name: Строительная компания
#   description: department-Builders-description
#   color: "#f4d03f"
#   roles:
#     - BuilderChief
#     - Builder
- type: department
  id: Militech
  name: Корпорация Militech
  description: department-Militech-description
  color: "#2e4053"
  roles:
    - HoSMilitech
    - HoDMilitech
    - SquadCommanderMilitech
    - SecurityMilitech
    - MedTechM
    - OperativeMilitech

- type: department
  id: NCPD
  name: NCPD
  description: department-NCPD-description
  color: "#1e90ff"
  roles:
    - NCPDChief
    - NCPDOfficer
    - NCPDSWAT
    - NCPDInspector

# - type: department
#   id: TraumaTeam
#   name: Отдление TraumaTeam
#   description: department-TraumaTeam-description
#   color: "#e74c3c"
#   roles:
#     - TraumaTeamChief
#     - TraumaTeamDoctor
#     - TraumaTeamChemist
#     - TraumaTeamParamedic
#     - TraumaTeamOperative
