- type: department
  id: CivilianNC
  name: Гражданские
  description: department-CivilianNC-description
  color: "#999999"
  roles:
    - Citizen
    - Reaper
    - Fixer
    - EdgeRunnerSolo

- type: department
  id: Militech
  name: Корпорация Militech
  description: department-Militech-description
  color: "#2e4053"
  roles:
    - HoSMilitech
    - HoDMilitech
    - SquadCommanderMilitech
    - SecurityMilitech
    - MedTechM
    - OperativeMilitech

- type: department
  id: NCPD
  name: NCPD
  description: department-NCPD-description
  color: "#1e90ff"
  roles:
    - NCPDChief
    - NCPDWatchAgent
    - NCPDSergeant
    - NCPDOfficer
    - NCPDCadet
    - MaxTacCommander
    - MaxTacOperative
    - MaxTacNetrunner
