using System.Numerics; // For Vector2
using System.Linq;
using Content.Shared._NC.Trauma;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls; // For BoxContainer, Label, etc.
using Robust.Client.UserInterface; // For Control
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths; // Для Thickness
using Robust.Client.Graphics;

namespace Content.Client._NC.Trauma
{
    public sealed partial class TraumaComputerWindow : FancyWindow
    {
        public event Action<NetEntity, TraumaSubscriptionTier>? OnSubscriptionChanged;
        public event Action<NetEntity>? OnDispatch;
        public event Action<NetEntity>? OnConfirmCompletion; // Диспетчер подтверждает завершение

        private readonly BoxContainer _patientList;
        private readonly BoxContainer _logList;
        private HashSet<NetEntity> _pendingCompletions = new();

        private sealed class PatientRow
        {
            public PanelContainer Panel = default!;
            public Label IdLabel = default!;
            public Label NameLabel = default!;
            public Label StatusLabel = default!;
            public OptionButton TierSelector = default!;
            public Button? DispatchBtn;
            public BoxContainer RowContent = default!;
            public TraumaSubscriptionTier CurrentListTier;
            public Action<BaseButton.ButtonEventArgs>? DispatchHandler; // Делегат для перепривязки
        }

        private readonly Dictionary<NetEntity, PatientRow> _patientRows = new();

        public TraumaComputerWindow()
        {
            RobustXamlLoader.Load(this);
            _patientList = FindControl<BoxContainer>("PatientList");
            _logList = FindControl<BoxContainer>("LogList");
        }

        public void UpdateState(TraumaComputerState state)
        {
            // Сохраняем pending completions
            _pendingCompletions = state.PendingCompletions ?? new HashSet<NetEntity>();

            // Remove missing patients
            var currentUids = new HashSet<NetEntity>(state.Patients.Select(p => p.EntityUid));
            var toRemove = _patientRows.Keys.Where(k => !currentUids.Contains(k)).ToList();
            foreach (var k in toRemove)
            {
                var row = _patientRows[k].Panel;
                row.Orphan();
                _patientRows.Remove(k);
            }

            foreach (var patient in state.Patients)
            {
                if (!_patientRows.TryGetValue(patient.EntityUid, out var rowData))
                {
                    rowData = CreatePatientRow(patient.EntityUid);
                    _patientRows[patient.EntityUid] = rowData;
                }

                UpdatePatientRow(rowData, patient);
            }

            // Update Logs
            _logList.DisposeAllChildren();
            // Show newest first
            for (int i = state.Logs.Count - 1; i >= 0; i--)
            {
                var log = state.Logs[i];
                var timeStr = log.Time.ToString(@"hh\:mm\:ss");

                var logLabel = new Label
                {
                    Text = $"[{timeStr}] {log.Editor} changed {log.Target}: {log.OldTier} -> {log.NewTier}",
                    FontColorOverride = Color.LightGray
                };

                _logList.AddChild(logLabel);
            }
        }

        private PatientRow CreatePatientRow(NetEntity uid)
        {
            var row = new PatientRow();

            row.Panel = new PanelContainer
            {
                MinHeight = 35
            };

            // Alternating dark grey / dark tint will happen dynamically or just rely on panel
            row.Panel.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#0b171c") };

            row.RowContent = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(10, 5),
                HorizontalExpand = true
            };

            row.IdLabel = new Label
            {
                MinWidth = 60,
                FontColorOverride = Color.FromHex("#9E9E9E"), // Grey string
                StyleClasses = { "LabelHeading" }
            };
            row.RowContent.AddChild(row.IdLabel);
            row.RowContent.AddChild(new Control { MinSize = new Vector2(10, 0) });

            row.NameLabel = new Label
            {
                HorizontalExpand = true,
                ClipText = true,
                StyleClasses = { "LabelHeading" },
                FontColorOverride = Color.FromHex("#EEEEEE")
            };
            row.RowContent.AddChild(row.NameLabel);
            row.RowContent.AddChild(new Control { MinSize = new Vector2(10, 0) });

            row.TierSelector = new OptionButton { MinWidth = 130 };
            for (int i = 0; i < 4; i++)
            {
                var tier = (TraumaSubscriptionTier) i;
                row.TierSelector.AddItem(tier.ToString().ToUpper(), i);
            }
            row.TierSelector.OnItemSelected += args =>
            {
                row.TierSelector.SelectId(args.Id);
                var newTier = (TraumaSubscriptionTier) args.Id;
                OnSubscriptionChanged?.Invoke(uid, newTier);
            };
            row.RowContent.AddChild(row.TierSelector);
            row.RowContent.AddChild(new Control { MinSize = new Vector2(10, 0) });

            row.StatusLabel = new Label
            {
                MinWidth = 100,
                Align = Label.AlignMode.Center,
                StyleClasses = { "LabelHeading" }
            };
            row.RowContent.AddChild(row.StatusLabel);
            row.RowContent.AddChild(new Control { MinSize = new Vector2(10, 0) });

            row.DispatchBtn = new Button
            {
                Text = "⮞ DISPATCH",
                Modulate = Color.FromHex("#D32F2F"),
                MinWidth = 90
            };
            // Обработчик привязывается динамически в UpdatePatientRow
            row.RowContent.AddChild(row.DispatchBtn);

            row.Panel.AddChild(row.RowContent);
            return row;
        }

        private void UpdatePatientRow(PatientRow row, TraumaPatientData patient)
        {
            var pseudoId = (patient.EntityUid.Id * 997) % 10000;
            row.IdLabel.Text = $"C-{pseudoId:D4}";
            row.NameLabel.Text = patient.Name.ToUpper();

            var statusColor = patient.HealthStatus switch
            {
                "Dead" => Color.FromHex("#D32F2F"),     // Red
                "Critical" => Color.FromHex("#FF9800"), // Orange
                _ => Color.FromHex("#4CAF50")           // Green
            };

            // Map "Alive" to "STABLE" for cyberpunk flavor
            var displayStatus = patient.HealthStatus == "Alive" ? "STABLE" : patient.HealthStatus.ToUpper();

            row.StatusLabel.Text = displayStatus;
            row.StatusLabel.FontColorOverride = statusColor;

            // Only update dropdown selection if it's completely different to prevent focus stealing / closing
            if (row.TierSelector.SelectedId != (int) patient.Subscription)
            {
                row.TierSelector.SelectId((int) patient.Subscription);
            }

            // Style Tier Button text heavily
            if (row.TierSelector.Children.FirstOrDefault() is Label label)
            {
                label.FontColorOverride = patient.Subscription switch
                {
                    TraumaSubscriptionTier.Platinum => Color.FromHex("#FFC107"), // Gold
                    TraumaSubscriptionTier.Silver => Color.FromHex("#64B5F6"),   // Light Blue
                    TraumaSubscriptionTier.Bronze => Color.FromHex("#FFD54F"),
                    _ => Color.FromHex("#9E9E9E") // Grey
                };
                label.StyleClasses.Add("LabelHeading");
            }

            // Dispatch / Confirm Button
            if (_pendingCompletions.Contains(patient.EntityUid))
            {
                // Пациент ожидает подтверждения завершения
                row.DispatchBtn!.Disabled = false;
                row.DispatchBtn.Text = "✓ CONFIRM";
                row.DispatchBtn.Modulate = Color.FromHex("#4CAF50"); // Зелёный

                // Перепривязываем кнопку на подтверждение
                row.DispatchBtn.OnPressed -= row.DispatchHandler;
                row.DispatchHandler = _ => OnConfirmCompletion?.Invoke(patient.EntityUid);
                row.DispatchBtn.OnPressed += row.DispatchHandler;
            }
            else if (patient.Subscription == TraumaSubscriptionTier.Platinum)
            {
                row.DispatchBtn!.Disabled = false;
                row.DispatchBtn.Text = "⪮ DISPATCH";

                // If critical, make outline orange, else red
                var btnColor = patient.HealthStatus == "Critical" ? Color.FromHex("#FF9800") : Color.FromHex("#D32F2F");
                row.DispatchBtn.Modulate = btnColor;

                // Перепривязываем кнопку на dispatch
                row.DispatchBtn.OnPressed -= row.DispatchHandler;
                row.DispatchHandler = _ => OnDispatch?.Invoke(patient.EntityUid);
                row.DispatchBtn.OnPressed += row.DispatchHandler;
            }
            else
            {
                row.DispatchBtn!.Disabled = true;
                row.DispatchBtn.Text = "⪮ N/A";
                row.DispatchBtn.Modulate = Color.FromHex("#424242"); // Dark Grey
                row.DispatchBtn.OnPressed -= row.DispatchHandler;
                row.DispatchHandler = null;
            }

            // Re-parent to the list if not there
            if (row.Panel.Parent != _patientList)
            {
                row.Panel.Orphan();
                _patientList.AddChild(row.Panel);
            }
        }
    }
}
