using System.Numerics;
using Content.Shared._NC.Trauma;
using Content.Client.UserInterface.Controls;
using Robust.Shared.Map;
using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;

namespace Content.Client._NC.Trauma
{
    public sealed partial class TraumaTabletWindow : FancyWindow
    {
        public event Action<NetEntity>? OnOpenMap; // Entity ID to center on?
        public event Action<NetEntity>? OnCompleteMission; // Оперативник нажал "Выполнено"

        private NetEntity? _currentPatient;

        // Controls
        private BoxContainer PatientDetailContainer;
        private BoxContainer EmptyContainer;
        private Label TitleLabel;
        private Label PatientNameLabel;
        private Label PatientStatusLabel;
        private ProgressBar BruteBar;
        private ProgressBar BurnBar;
        private ProgressBar ToxinBar;
        private TraumaNavMapControl NavMap;
        private Label CoordLabel;
        private SpriteView SpriteView;
        private Button CompleteBtn;

        public TraumaTabletWindow()
        {
            RobustXamlLoader.Load(this);

            PatientDetailContainer = FindControl<BoxContainer>("PatientDetailContainer");
            EmptyContainer = FindControl<BoxContainer>("PatientListContainer");
            TitleLabel = FindControl<Label>("TitleLabel");
            PatientNameLabel = FindControl<Label>("PatientNameLabel");
            PatientStatusLabel = FindControl<Label>("PatientStatusLabel");
            BruteBar = FindControl<ProgressBar>("BruteBar");
            BurnBar = FindControl<ProgressBar>("BurnBar");
            ToxinBar = FindControl<ProgressBar>("ToxinBar");
            NavMap = FindControl<TraumaNavMapControl>("NavMap");
            CoordLabel = FindControl<Label>("CoordLabel");
            SpriteView = FindControl<SpriteView>("SpriteView");
            CompleteBtn = FindControl<Button>("CompleteBtn");

            // Кнопка "Выполнено" — отправляем сообщение через BUI
            CompleteBtn.OnPressed += _ =>
            {
                if (_currentPatient.HasValue)
                    OnCompleteMission?.Invoke(_currentPatient.Value);
            };

            // Скрываем тулбар NavMapControl (зум, чекбоксы, кнопка центрирования)
            // Тулбар — это PanelContainer внутри первого BoxContainer NavMap
            if (NavMap.GetChild(0) is BoxContainer navBox && navBox.GetChild(0) is PanelContainer toolbar)
            {
                toolbar.Visible = false;
            }

            // Отключаем авто-центрирование карты
            NavMap.DisableRecentering();

            // Initial state: Empty
            ShowEmpty();
        }

        public void UpdateState(TraumaPatientData? patient, bool isPendingCompletion = false)
        {
            if (patient.HasValue)
            {
                ShowDetails(patient.Value, isPendingCompletion);
            }
            else
            {
                ShowEmpty();
            }
        }

        private void ShowDetails(TraumaPatientData patient, bool isPendingCompletion)
        {
            _currentPatient = patient.EntityUid;

            // Populate view
            PopulateDetails(patient, isPendingCompletion);

            // Switch view
            EmptyContainer.Visible = false;
            PatientDetailContainer.Visible = true;
            TitleLabel.Text = "TT-BIOTRACKER v3.2 - PLATINUM ACTIVE";
        }

        private void PopulateDetails(TraumaPatientData patient, bool isPendingCompletion)
        {
            PatientNameLabel.Text = patient.Name.ToUpper();

            var displayStatus = patient.HealthStatus == "Alive" ? "STABLE" : patient.HealthStatus.ToUpper();
            PatientStatusLabel.Text = displayStatus;

            // Color status
            PatientStatusLabel.FontColorOverride = patient.HealthStatus switch
            {
                "Dead" => Color.FromHex("#D32F2F"), // Red
                "Critical" => Color.Orange,
                _ => Color.FromHex("#4CAF50") // Green
            };

            BruteBar.Value = patient.BruteDamage;
            BurnBar.Value = patient.BurnDamage;
            ToxinBar.Value = patient.ToxinDamage;

            var activeEntity = IoCManager.Resolve<IEntityManager>().GetEntity(patient.EntityUid);
            SpriteView.SetEntity(activeEntity);

            if (patient.TargetCoords.HasValue)
            {
                var coords = IoCManager.Resolve<IEntityManager>().GetCoordinates(patient.TargetCoords.Value);
                // Parent of the coordinates is typically the grid or map
                NavMap.MapUid = coords.EntityId;
                NavMap.CustomBeacons.Clear();

                NavMap.CustomBeacons.Add((coords, "VIP SIGNATURE", PatientStatusLabel.FontColorOverride ?? Color.Green, true));
                NavMap.CenterToCoordinates(coords);
                NavMap.DisableRecentering(); // Не центрировать автоматически
                NavMap.ForceNavMapUpdate();
                CoordLabel.Text = $"{coords.X:F1}, {coords.Y:F1}";
            }
            else
            {
                CoordLabel.Text = "UNKNOWN";
            }

            // Состояние кнопки "Выполнено"
            if (isPendingCompletion)
            {
                CompleteBtn.Disabled = true;
                CompleteBtn.Text = "AWAITING CONFIRM...";
                CompleteBtn.Modulate = Color.FromHex("#9E9E9E"); // Серый
            }
            else
            {
                CompleteBtn.Disabled = false;
                CompleteBtn.Text = "✓ ВЫПОЛНЕНО";
                CompleteBtn.Modulate = Color.FromHex("#4CAF50"); // Зелёный
            }
        }

        private void ShowEmpty()
        {
            _currentPatient = null;
            EmptyContainer.Visible = true;
            PatientDetailContainer.Visible = false;
            TitleLabel.Text = "TT-BIOTRACKER v3.2 - STANDBY";
        }
    }
}
