using Content.Shared.Book;
using Robust.Shared.Utility;
using Robust.Client.Input;
using Robust.Shared.Input;
using Content.Shared.Book.Components;
using Content.Client.UserInterface.Controls;
using Content.Client.Book.UI;
using Content.Client.Paper.UI;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Robust.Client.UserInterface;
using Robust.Shared.IoC;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Content.Shared.Administration;

namespace Content.Client.Book.UI;

[GenerateTypedNameReferences]
public sealed partial class BookWindow : FancyWindow
{
    [Dependency] private readonly IInputManager _inputManager = default!;
    private List<string> _pages = new();
    private int _currentPageIndex = 0;
    private Dictionary<int, string> _bookmarks = new();
    private int _maxBookmarks;
    private DialogWindow? _bookmarkDialog;
    private int _maxCharactersPerPage;
    private int _maxPages;
    private Label? _characterCountLabel;

    public event Action<int>? OnPageChanged;
    public event Action<string>? OnTextSaved;
    public event Action? OnAddPage;
    public event Action<bool>? OnEditModeChanged;
    public event Action<int, string>? OnBookmarkAdded;
    public event Action<int>? OnBookmarkRemoved;
    public event Action<int>? OnPageDeleted;

    public BookWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var resCache = IoCManager.Resolve<IResourceCache>();

        var customTexture = resCache.GetResource<TextureResource>("/Textures/Interface/Book/rounded_book_background.png");
        var paperSheetTexture = resCache.GetResource<TextureResource>("/Textures/Interface/Book/paper_sheet_curled_edges.png");

        var paperBackground = new StyleBoxTexture
        {
            Texture = customTexture,
            Mode = StyleBoxTexture.StretchMode.Stretch
        };
        var paperSheetBackground = new StyleBoxTexture
        {
            Texture = paperSheetTexture,
            Mode = StyleBoxTexture.StretchMode.Stretch,
            Modulate = Color.FromHex("#f8f8f8") // Paper color
        };

        paperBackground.SetPatchMargin(StyleBox.Margin.All, 24.0f);
        paperSheetBackground.SetPatchMargin(StyleBox.Margin.All, 20.0f);

        WindowsPanelBackground.PanelOverride = paperBackground;
        WindowsPanelBackground.ModulateSelfOverride = Color.FromHex("#636363ff"); // Book color

        PaperBackground.Margin = new Thickness(0, 8, 5, 0);
        PaperBackground.MinSize = new Vector2(400, 500);
        PaperBackground.PanelOverride = paperSheetBackground;

        WindowsHeadingBackground.Visible = false;

        var absoluteContainer = new Control
        {
            MouseFilter = Control.MouseFilterMode.Ignore
        };

        var floatingCloseButton = new PanelContainer
        {
            StyleClasses = { "AngleRect" },
            VerticalAlignment = Control.VAlignment.Top,
            HorizontalAlignment = Control.HAlignment.Right,
            Margin = new Thickness(0, -50, 10, 0),
            SetSize = new Vector2(42, 42),
            VerticalExpand = false,
            HorizontalExpand = false
        };

        CloseButton.Parent?.RemoveChild(CloseButton);
        floatingCloseButton.AddChild(CloseButton);

        AddChild(floatingCloseButton);


        PrevPageButton.OnPressed += _ => NavigateToPage(_currentPageIndex - 1);
        NextPageButton.OnPressed += _ => NavigateToPage(_currentPageIndex + 1);
        AddPageButton.OnPressed += _ => OnAddPage?.Invoke();

        Input.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.MultilineTextSubmit)
            {
                SaveCurrentPage();
                args.Handle();
            }
        };

        SaveButton.OnPressed += _ => SaveCurrentPage();
        SaveButton.Text = Loc.GetString("book-ui-save-button", ("keybind", _inputManager.GetKeyFunctionButtonString(EngineKeyFunctions.MultilineTextSubmit)));

        PageNumberInput.OnTextChanged += args =>
        {
            const int maxLength = 3;

            if (args.Text.Length > maxLength)
                PageNumberInput.Text = args.Text[..maxLength];

            var newText = string.Concat(args.Text.Where(char.IsDigit));
            if (newText != args.Text)
                PageNumberInput.Text = newText;
        };
        PageNumberInput.OnTextEntered += OnPageNumberEntered;
        PageNumberInput.OnFocusExit += OnPageNumberEntered;
        InitializeBookmarks();

        Input.OnTextChanged += _ => UpdateCharacterCount();

        DeletePageButton.OnPressed += _ => DeleteCurrentPage();
    }

    public void ShowBook(BookBoundUserInterfaceState state, bool isEditing)
    {
        _pages = state.Pages;

        _currentPageIndex = Math.Max(0, Math.Min(state.CurrentPage, _pages.Count - 1));

        UpdatePageDisplay();
        UpdateNavigationButtons();
        SetEditMode(isEditing);

        _bookmarks = state.Bookmarks;
        _maxBookmarks = state.MaxBookmarks;
        _maxCharactersPerPage = state.MaxCharactersPerPage;
        _maxPages = state.MaxPages;
        UpdateBookmarksDisplay();
    }

    private void SetEditMode(bool isEditing)
    {
        InputContainer.Visible = isEditing;
        EditButtons.Visible = isEditing;
        PageContainer.Visible = !isEditing;

        if (isEditing)
        {
            if (_currentPageIndex >= 0 && _currentPageIndex < _pages.Count && _pages.Count > 0)
            {
                Input.TextRope = new Rope.Leaf(_pages[_currentPageIndex]);
                Input.CursorPosition = new TextEdit.CursorPos(Rope.Collapse(Input.TextRope).Length, TextEdit.LineBreakBias.Top);
            }
            else
            {
                Input.TextRope = new Rope.Leaf("");
                Input.CursorPosition = new TextEdit.CursorPos(0, TextEdit.LineBreakBias.Top);
            }

            UpdateCharacterCount();
        }
    }

    private void SaveCurrentPage()
    {
        OnTextSaved?.Invoke(Rope.Collapse(Input.TextRope));
    }

    private void UpdatePageDisplay()
    {
        if (_pages == null || _pages.Count == 0)
        {
            PageContainer.RemoveAllChildren();

            var blankPageLabel = new RichTextLabel();
            blankPageLabel.SetMessage(Loc.GetString("paper-ui-blank-page-message"), null, Color.Gray);
            PageContainer.AddChild(blankPageLabel);

            PageInfo.Text = Loc.GetString("book-page-info-empty");
            return;
        }

        PageContainer.RemoveAllChildren();

        if (_currentPageIndex < _pages.Count)
        {
            var pageText = _pages[_currentPageIndex];

            if (string.IsNullOrWhiteSpace(pageText))
            {
                var blankPageLabel = new RichTextLabel();
                blankPageLabel.SetMessage(Loc.GetString("paper-ui-blank-page-message"), null, Color.Gray);
                PageContainer.AddChild(blankPageLabel);
            }
            else
            {
                var label = new RichTextLabel();
                var formattedMessage = new FormattedMessage();
                formattedMessage.PushColor(Color.Black);
                try
                {
                    formattedMessage.AddMarkup(pageText);
                }
                catch
                {
                    formattedMessage.AddText(pageText);
                }
                formattedMessage.Pop();
                label.SetMessage(formattedMessage);
                PageContainer.AddChild(label);
            }
        }

        PageInfo.Text = Loc.GetString("book-page-info", ("total", Math.Max(1, _pages.Count)));
    }

    private void UpdatePageNumberDisplay()
    {
        PageNumberInput.Text = (_currentPageIndex + 1).ToString();
    }

    private void NavigateToPage(int pageIndex)
    {
        if (_pages == null) return;

        if (pageIndex >= 0 && pageIndex < _pages.Count)
        {
            _currentPageIndex = pageIndex;
            OnPageChanged?.Invoke(pageIndex);
            UpdatePageDisplay();
            UpdateNavigationButtons();
            UpdateBookmarksDisplay();
            if (InputContainer.Visible) { SetEditMode(true); }
        }
        else
        {
            UpdatePageNumberDisplay();
        }
    }

    private void ToggleBookmarksVisibility()
    {
        BookmarksPanel.Visible = !BookmarksPanel.Visible;
        BookmarksToggleButton.Text = BookmarksPanel.Visible ? Loc.GetString("book-bookmarks-hide") : Loc.GetString("book-bookmarks-show");
    }

    private void ToggleBookmarkForCurrentPage()
    {
        if (_pages == null || _currentPageIndex < 0 || _currentPageIndex >= _pages.Count)
            return;
        if (_bookmarks.ContainsKey(_currentPageIndex))
        {
            _bookmarks.Remove(_currentPageIndex);
            OnBookmarkRemoved?.Invoke(_currentPageIndex);
        }
        else if (_bookmarks.Count < _maxBookmarks)
        {
            var defaultTitle = Loc.GetString("book-bookmark-default-title", ("page", _currentPageIndex + 1));
            ShowBookmarkDialog(defaultTitle);
        }
        UpdateBookmarksDisplay();
    }

    private void UpdateNavigationButtons()
    {
        if (_pages == null)
        {
            PrevPageButton.Disabled = true;
            NextPageButton.Disabled = true;
            DeletePageButton.Disabled = true;
            return;
        }
        PrevPageButton.Disabled = _currentPageIndex <= 0;
        NextPageButton.Disabled = _currentPageIndex >= _pages.Count - 1;
        DeletePageButton.Disabled = _pages.Count <= 1;
        UpdatePageNumberDisplay();
    }

    private void OnPageNumberEntered(LineEdit.LineEditEventArgs args)
    {
        if (int.TryParse(args.Text, out var pageNumber) && pageNumber > 0)
        {
            NavigateToPage(pageNumber - 1);
        }
        else
        {
            UpdatePageNumberDisplay();
        }
    }

    private void InitializeBookmarks()
    {
        ToggleBookmarkButton.OnPressed += _ => ToggleBookmarkForCurrentPage();
        BookmarkDropdown.OnItemSelected += OnBookmarkSelected;
        BookmarksToggleButton.OnPressed += _ => ToggleBookmarksVisibility();
    }

    private void ShowBookmarkDialog(string defaultTitle)
    {
        if (_bookmarkDialog != null)
        {
            if (_bookmarkDialog.IsOpen)
            {
                _bookmarkDialog.MoveToFront();
                return;
            }
            _bookmarkDialog = null;
        }
        var field = "title";
        var prompt = Loc.GetString("book-bookmark-title-prompt");
        var entry = new QuickDialogEntry(field, QuickDialogEntryType.ShortText, prompt, defaultTitle);
        var entries = new List<QuickDialogEntry> { entry };
        _bookmarkDialog = new DialogWindow(Loc.GetString("book-bookmark-title-dialog"), entries);
        _bookmarkDialog.OnConfirmed += responses =>
        {
            var title = responses[field].Trim();
            if (string.IsNullOrEmpty(title))
                title = defaultTitle;

            const int maxLength = 50;
            if (title.Length > maxLength)
                title = title[..maxLength];

            _bookmarks[_currentPageIndex] = title;
            OnBookmarkAdded?.Invoke(_currentPageIndex, title);
            UpdateBookmarksDisplay();
        };
        _bookmarkDialog.OnClose += () => _bookmarkDialog = null;
    }

    private void OnBookmarkSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (args.Id == -1)
            return;

        if (args.Id is int pageIndex && _pages != null)
        {
            NavigateToPage(pageIndex);
        }
    }

    private void UpdateBookmarksDisplay()
    {
        BookmarkDropdown.Clear();

        if (_bookmarks.Count == 0)
        {
            BookmarkDropdown.Disabled = true;
            BookmarkCountLabel.Text = Loc.GetString("book-no-bookmarks");
        }
        else
        {
            BookmarkDropdown.Disabled = false;
            BookmarkDropdown.AddItem(Loc.GetString("book-select-bookmark"), -1);

            var sortedBookmarks = _bookmarks.OrderBy(kvp => kvp.Key);
            foreach (var bookmark in sortedBookmarks)
            {
                var displayText = $"{bookmark.Value}";
                BookmarkDropdown.AddItem(displayText, bookmark.Key);
            }

            BookmarkCountLabel.Text = Loc.GetString("book-bookmarks-count", ("count", _bookmarks.Count), ("max", _maxBookmarks));
            BookmarkDropdown.SelectId(-1);
        }

        bool hasBookmarkOnCurrentPage = _bookmarks.ContainsKey(_currentPageIndex);
        bool reachedMaxBookmarks = _bookmarks.Count >= _maxBookmarks;

        if (hasBookmarkOnCurrentPage)
        {
            ToggleBookmarkButton.Text = "-";
            ToggleBookmarkButton.Disabled = false;
        }
        else if (reachedMaxBookmarks)
        {
            ToggleBookmarkButton.Text = "+";
            ToggleBookmarkButton.Disabled = true;
        }
        else
        {
            ToggleBookmarkButton.Text = "+";
            ToggleBookmarkButton.Disabled = false;
        }
    }

    private void UpdateCharacterCount()
    {
        if (CharacterCountLabel == null || !InputContainer.Visible)
            return;
        var currentLength = Rope.Collapse(Input.TextRope).Length;
        var isOverLimit = currentLength > _maxCharactersPerPage;
        CharacterCountLabel.Text = Loc.GetString("book-character-count",
            ("current", currentLength),
            ("max", _maxCharactersPerPage));
        if (isOverLimit)
        {
            CharacterCountLabel.StyleClasses.Clear();
            CharacterCountLabel.StyleClasses.Add("LabelDanger");
        }
        else
        {
            CharacterCountLabel.StyleClasses.Clear();
            CharacterCountLabel.StyleClasses.Add("LabelSubText");
        }
    }

    private void DeleteCurrentPage()
    {
        if (_pages == null || _pages.Count <= 1 || _currentPageIndex < 0 || _currentPageIndex >= _pages.Count)
            return;
        OnPageDeleted?.Invoke(_currentPageIndex);
    }
}
