using Content.Shared._White.Pain.Systems;
using Content.Shared.FixedPoint;
using Robust.Shared.GameStates;

namespace Content.Shared._White.Pain.Components;

[RegisterComponent, NetworkedComponent, AutoGenerateComponentState(fieldDeltas: true)]
[Access(typeof(SharedPainfulSystem))]
public sealed partial class PainfulWoundComponent : Component
{
    /// <summary>
    /// The rate at which "fresh" pain (pain generated by <see cref="FreshPainCoefficients"/>)
    /// decreases over time per second. This represents the initial intensity fading away.
    /// </summary>
    [DataField]
    public double FreshPainDecreasePerSecond = 0.15d;

    /// <summary>
    /// The temporary, acute pain that fades over time. This value is influenced by
    /// <see cref="FreshPainCoefficients"/> and decreases based on <see cref="FreshPainDecreasePerSecond"/>.
    /// </summary>
    [DataField, AutoNetworkedField]
    public FixedPoint2 FreshPain = FixedPoint2.Zero;

    /// <summary>
    /// The persistent amount of pain caused by the wound that does not diminish over time.
    /// This is the base, long-term pain effect.
    /// </summary>
    [DataField, AutoNetworkedField]
    public FixedPoint2 LastingPain = FixedPoint2.Zero;

    /// <summary>
    /// A multiplier specifically applied to the damage value to determine the initial, higher pain
    /// generated when the wound is fresh. This is often higher than <see cref="PainCoefficients"/>
    /// to represent the acute pain of a new injury.
    /// </summary>
    [DataField(required: true)]
    public float FreshPainCoefficients;

    /// <summary>
    /// A multiplier applied to the damage value to determine the amount of pain generated.
    /// For example, a coefficient of 0.5 means half the damage value contributes to pain.
    /// </summary>
    [DataField(required: true)]
    public float PainCoefficients;

    /// <summary>
    /// The total effective pain caused by the wound, which is the sum of its
    /// <see cref="LastingPain"/> and <see cref="FreshPain"/>.
    /// </summary>
    [ViewVariables]
    public FixedPoint2 Pain => LastingPain + FreshPain;
}
