using Content.Shared._NC.Cyberware;
using Content.Shared._NC.Cyberware.UI;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;

namespace Content.Client._NC.Cyberware.UI;

/// <summary>
///     Окно терминала Автодока в стиле Cyberpunk.
///     Отрисовывает спрайт пациента в центре, слоты кибервари по бокам.
/// </summary>
public sealed partial class CyberwareAutodocWindow : FancyWindow
{
    private readonly IEntityManager _entManager;

    // События для BUI (сигнатуры совместимы с CyberwareAutodocBoundUserInterface)
    public event Action<CyberwareSlot, NetEntity?>? OnInstallPressed;
    public event Action<CyberwareSlot>? OnRemovePressed;

    // UI-элементы слотов, генерируемые программно в BuildSlotPanel
    private readonly Dictionary<CyberwareSlot, Label> _slotImplantLabels = new();
    private readonly Dictionary<CyberwareSlot, Button> _slotActionButtons = new();

    // Текущее состояние от сервера
    private NetEntity? _currentPatient;
    private Dictionary<CyberwareSlot, NetEntity> _installed = new();

    public CyberwareAutodocWindow()
    {
        RobustXamlLoader.Load(this);
        _entManager = IoCManager.Resolve<IEntityManager>();

        // Получаем контейнеры из XAML
        var leftContainer = FindControl<BoxContainer>("LeftSlotsContainer");
        var rightContainer = FindControl<BoxContainer>("RightSlotsContainer");

        // Левая колонка: Голова + Левая сторона тела
        BuildSlotPanel(leftContainer, CyberwareSlot.Neuroport, "НЕЙРОПОРТ");
        BuildSlotPanel(leftContainer, CyberwareSlot.Optics,    "КИБЕРОПТИКА");
        BuildSlotPanel(leftContainer, CyberwareSlot.Audio,     "АУДИОИМПЛАНТ");
        BuildSlotPanel(leftContainer, CyberwareSlot.Style,     "СТИЛЕВЫЕ");
        BuildSlotPanel(leftContainer, CyberwareSlot.Internal,  "ВНУТРЕННИЕ");

        // Правая колонка: Конечности + Внешние импланты
        BuildSlotPanel(rightContainer, CyberwareSlot.RightArm, "ПРАВАЯ РУКА");
        BuildSlotPanel(rightContainer, CyberwareSlot.LeftArm,  "ЛЕВАЯ РУКА");
        BuildSlotPanel(rightContainer, CyberwareSlot.RightLeg, "ПРАВАЯ НОГА");
        BuildSlotPanel(rightContainer, CyberwareSlot.LeftLeg,  "ЛЕВАЯ НОГА");
        BuildSlotPanel(rightContainer, CyberwareSlot.External, "ВНЕШНИЕ");
    }

    /// <summary>
    ///     Создаёт UI-панель для одного слота кибервари в стиле терминала.
    /// </summary>
    private void BuildSlotPanel(BoxContainer parent, CyberwareSlot slot, string displayName)
    {
        // Панель с бордером в стиле терминала
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#0d150d"),
                BorderColor = Color.FromHex("#2a5a2a"),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
            },
        };

        var vbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        // Заголовок слота (янтарный цвет как на референсе)
        var header = new Label
        {
            Text = $"▸ {displayName}",
            FontColorOverride = Color.FromHex("#ffaa00"),
        };

        // Статус установленного импланта
        var implantLabel = new Label
        {
            Text = "[ПУСТО]",
            FontColorOverride = Color.FromHex("#556655"),
            Margin = new Thickness(8, 2, 0, 0),
        };

        // Кнопка извлечения (активна только при установленном импланте)
        var actionBtn = new Button
        {
            Text = "ИЗВЛЕЧЬ",
            Disabled = true,
            HorizontalExpand = true,
            MinHeight = 26,
            Margin = new Thickness(0, 4, 0, 0),
        };

        // Обработчик нажатия — вызывает событие для BUI
        actionBtn.OnPressed += _ =>
        {
            if (_installed.ContainsKey(slot))
                OnRemovePressed?.Invoke(slot);
        };

        vbox.AddChild(header);
        vbox.AddChild(implantLabel);
        vbox.AddChild(actionBtn);
        panel.AddChild(vbox);
        parent.AddChild(panel);

        // Сохраняем ссылки для обновления в UpdateState
        _slotImplantLabels[slot] = implantLabel;
        _slotActionButtons[slot] = actionBtn;
    }

    /// <summary>
    ///     Обновляет состояние окна данными от сервера (вызывается из BUI).
    /// </summary>
    public void UpdateState(AutodocBoundUserInterfaceState state)
    {
        _currentPatient = state.Patient;
        _installed = state.InstalledImplants ?? new Dictionary<CyberwareSlot, NetEntity>();

        // Получаем XAML-элементы центральной колонки
        var patientSprite = FindControl<SpriteView>("PatientSprite");
        var patientNameLabel = FindControl<Label>("PatientNameLabel");
        var patientStatusLabel = FindControl<Label>("PatientStatusLabel");
        var spriteLabel = FindControl<Label>("PatientSpriteLabel");

        // Отрисовываем спрайт пациента, лежащего в автодоке
        if (_currentPatient != null && _entManager.TryGetEntity(_currentPatient.Value, out var patientUid))
        {
            patientSprite.SetEntity(patientUid.Value);

            var name = _entManager.GetComponentOrNull<MetaDataComponent>(patientUid.Value)?.EntityName ?? "Неизвестный";
            patientNameLabel.Text = name;
            patientStatusLabel.Text = "В АВТОДОКЕ";
            patientStatusLabel.FontColorOverride = Color.FromHex("#00ff88");
            spriteLabel.Text = $"[ {name.ToUpper()} ]";
            spriteLabel.FontColorOverride = Color.FromHex("#00ff88");
        }
        else
        {
            patientSprite.SetEntity(null);
            patientNameLabel.Text = "[НЕТ ДАННЫХ]";
            patientStatusLabel.Text = "ПУСТО";
            patientStatusLabel.FontColorOverride = Color.FromHex("#ff5555");
            spriteLabel.Text = "[ПАЦИЕНТ НЕ ОБНАРУЖЕН]";
            spriteLabel.FontColorOverride = Color.FromHex("#556655");
        }

        // Обновляем каждый слот кибервари
        foreach (var (slot, implantLabel) in _slotImplantLabels)
        {
            var actionBtn = _slotActionButtons[slot];

            if (_installed.TryGetValue(slot, out var installedNet))
            {
                // Имплант установлен — показываем его название
                var entity = _entManager.GetEntity(installedNet);
                var implantName = _entManager.GetComponentOrNull<MetaDataComponent>(entity)?.EntityName ?? "???";

                implantLabel.Text = $"{implantName} [УСТАНОВЛЕНО]";
                implantLabel.FontColorOverride = Color.FromHex("#00ff88");

                actionBtn.Text = "ИЗВЛЕЧЬ";
                actionBtn.ModulateSelfOverride = Color.FromHex("#ff3333");
                actionBtn.Disabled = false;
            }
            else
            {
                // Слот пуст
                implantLabel.Text = "[ПУСТО]";
                implantLabel.FontColorOverride = Color.FromHex("#556655");

                actionBtn.Text = "ИЗВЛЕЧЬ";
                actionBtn.ModulateSelfOverride = null;
                actionBtn.Disabled = true;
            }
        }
    }
}