using Content.Shared._NC.Crafting.ConsoleCompiler;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._NC.Crafting.ConsoleCompiler;

/// <summary>
/// Окно консоли-компилятора (Техно-Принтер).
/// Полностью локализовано через .ftl.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ConsoleCompilerWindow : DefaultWindow
{
    // ─── События для BUI ───
    public event Action? OnDigitize;
    public event Action? OnEjectReceiver;
    public event Action? OnEjectMaster;
    public event Action<bool>? OnPrint; // true = Blueprint, false = Recipe

    // ─── Контролы ───
    private readonly Label _inputItemLabel;
    private readonly TextureRect _inputDiskIcon;
    private readonly Label _availableDataLabel;

    private readonly Label _masterDiskLabel;
    private readonly TextureRect _masterDiskIcon;
    private readonly Label _matrixStatusLabel;
    private readonly Label _usesLeftLabel;

    private readonly Button _digitizeButton;
    private readonly Button _printBlueprintButton;
    private readonly Button _printRecipeButton;
    private readonly Button _ejectReceiverButton;
    private readonly Button _ejectMasterButton;

    private readonly Label _blueprintCostLabel;
    private readonly Label _recipeCostLabel;

    private readonly Label _statusLabel;

    // Цвета из макета
    private static readonly Color CyanColor = Color.FromHex("#55EEFF");
    private static readonly Color AmberColor = Color.FromHex("#DDCC44");
    private static readonly Color GrayColor = Color.FromHex("#AAAAAA");

    public ConsoleCompilerWindow()
    {
        RobustXamlLoader.Load(this);

        // Левая панель — DATA BANK
        _inputItemLabel = FindControl<Label>("InputItemLabel");
        _inputDiskIcon = FindControl<TextureRect>("InputDiskIcon");
        _availableDataLabel = FindControl<Label>("AvailableDataLabel");
        _digitizeButton = FindControl<Button>("DigitizeButton");
        _ejectReceiverButton = FindControl<Button>("EjectReceiverButton");

        // Правая панель — COMPILER
        _masterDiskLabel = FindControl<Label>("MasterDiskLabel");
        _masterDiskIcon = FindControl<TextureRect>("MasterDiskIcon");
        _matrixStatusLabel = FindControl<Label>("MatrixStatusLabel");
        _usesLeftLabel = FindControl<Label>("UsesLeftLabel");
        _printBlueprintButton = FindControl<Button>("PrintBlueprintButton");
        _printRecipeButton = FindControl<Button>("PrintRecipeButton");
        _ejectMasterButton = FindControl<Button>("EjectMasterButton");

        _blueprintCostLabel = FindControl<Label>("BlueprintCostLabel");
        _recipeCostLabel = FindControl<Label>("RecipeCostLabel");

        // Статус
        _statusLabel = FindControl<Label>("StatusLabel");

        // Подписки кнопок
        _digitizeButton.OnPressed += _ => OnDigitize?.Invoke();
        _ejectReceiverButton.OnPressed += _ => OnEjectReceiver?.Invoke();
        _ejectMasterButton.OnPressed += _ => OnEjectMaster?.Invoke();
        _printBlueprintButton.OnPressed += _ => OnPrint?.Invoke(true);
        _printRecipeButton.OnPressed += _ => OnPrint?.Invoke(false);
    }

    /// <summary>
    /// Обновление всех элементов интерфейса по BUI-состоянию.
    /// </summary>
    public void UpdateState(ConsoleCompilerBoundUiState state)
    {
        // ─── DATA BANK — Левая панель ───
        if (state.HasReceiverItem)
        {
            _inputItemLabel.Text = "RAW_DATA_SHARD";
            _inputItemLabel.FontColorOverride = CyanColor;
            _inputDiskIcon.Visible = true;
        }
        else
        {
            _inputItemLabel.Text = Loc.GetString("console-compiler-window-input-empty");
            _inputItemLabel.FontColorOverride = GrayColor;
            _inputDiskIcon.Visible = false;
        }

        _availableDataLabel.Text = Loc.GetString("console-compiler-window-memory-value", ("value", state.AvailableData));
        _digitizeButton.Disabled = !state.HasReceiverItem || state.IsPrinting;
        _ejectReceiverButton.Disabled = state.IsPrinting;

        // ─── COMPILER — Правая панель ───
        if (state.HasMasterDisk)
        {
            _masterDiskLabel.Text = state.MasterDiskName.ToUpper().Replace(" ", "_");
            _masterDiskLabel.FontColorOverride = AmberColor;
            _masterDiskIcon.Visible = true;
            _matrixStatusLabel.Text = Loc.GetString("console-compiler-window-matrix-status",
                ("status", Loc.GetString("console-compiler-window-matrix-status-ready")));
            _matrixStatusLabel.FontColorOverride = Color.FromHex("#22EE22");
            _usesLeftLabel.Text = Loc.GetString("console-compiler-window-uses-value", ("count", state.MasterDiskUsesLeft));
        }
        else
        {
            _masterDiskLabel.Text = Loc.GetString("console-compiler-window-matrix-not-found");
            _masterDiskLabel.FontColorOverride = GrayColor;
            _masterDiskIcon.Visible = false;
            _matrixStatusLabel.Text = Loc.GetString("console-compiler-window-matrix-status",
                ("status", Loc.GetString("console-compiler-window-matrix-status-missing")));
            _matrixStatusLabel.FontColorOverride = GrayColor;
            _usesLeftLabel.Text = Loc.GetString("console-compiler-window-uses-value", ("count", 0));
        }

        // Кнопки печати
        var canBlueprint = state.HasMasterDisk && state.MasterDiskUsesLeft > 0 && state.AvailableData >= state.BlueprintCost && !state.IsPrinting;
        var canRecipe = state.HasMasterDisk && state.MasterDiskUsesLeft > 0 && state.AvailableData >= state.RecipeCost && !state.IsPrinting;

        _printBlueprintButton.Disabled = !canBlueprint;
        _printRecipeButton.Disabled = !canRecipe;
        _ejectMasterButton.Disabled = state.IsPrinting;

        // Стоимости под кнопками
        _blueprintCostLabel.Text = Loc.GetString("console-compiler-window-cost-label",
            ("cost", state.BlueprintCost), ("uses", state.HasMasterDisk ? 1 : 0));
        _recipeCostLabel.Text = Loc.GetString("console-compiler-window-cost-label",
            ("cost", state.RecipeCost), ("uses", state.HasMasterDisk ? 1 : 0));

        // ─── Статус нижний ───
        if (state.IsPrinting)
        {
            _statusLabel.Text = Loc.GetString("console-compiler-window-status-printing");
            _statusLabel.FontColorOverride = AmberColor;
        }
        else
        {
            _statusLabel.Text = Loc.GetString("console-compiler-window-status-ready");
            _statusLabel.FontColorOverride = GrayColor;
        }
    }
}
