using Content.Shared._NC.Crafting.ConsoleCompiler;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.Crafting.ConsoleCompiler;

/// <summary>
/// Окно консоли-компилятора (Техно-Принтер).
/// Отображает баланс данных, информацию о мастер-диске и кнопки управления.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ConsoleCompilerWindow : DefaultWindow
{
    // ─── События для BUI ───
    public event Action? OnDigitize;
    public event Action? OnEjectReceiver;
    public event Action? OnEjectMaster;
    public event Action<bool>? OnPrint; // true = Blueprint, false = Recipe

    // ─── Контролы ───
    private readonly Label _availableDataLabel;
    private readonly Label _masterDiskLabel;
    private readonly Label _usesLeftLabel;
    private readonly Label _statusLabel;
    private readonly Button _digitizeButton;
    private readonly Button _ejectReceiverButton;
    private readonly Button _printBlueprintButton;
    private readonly Button _printRecipeButton;
    private readonly Button _ejectMasterButton;

    public ConsoleCompilerWindow()
    {
        RobustXamlLoader.Load(this);

        _availableDataLabel = FindControl<Label>("AvailableDataLabel");
        _masterDiskLabel = FindControl<Label>("MasterDiskLabel");
        _usesLeftLabel = FindControl<Label>("UsesLeftLabel");
        _statusLabel = FindControl<Label>("StatusLabel");
        _digitizeButton = FindControl<Button>("DigitizeButton");
        _ejectReceiverButton = FindControl<Button>("EjectReceiverButton");
        _printBlueprintButton = FindControl<Button>("PrintBlueprintButton");
        _printRecipeButton = FindControl<Button>("PrintRecipeButton");
        _ejectMasterButton = FindControl<Button>("EjectMasterButton");

        // Подписки кнопок
        _digitizeButton.OnPressed += _ => OnDigitize?.Invoke();
        _ejectReceiverButton.OnPressed += _ => OnEjectReceiver?.Invoke();
        _ejectMasterButton.OnPressed += _ => OnEjectMaster?.Invoke();
        _printBlueprintButton.OnPressed += _ => OnPrint?.Invoke(true);
        _printRecipeButton.OnPressed += _ => OnPrint?.Invoke(false);
    }

    /// <summary>
    /// Обновление всех элементов интерфейса по BUI-состоянию.
    /// </summary>
    public void UpdateState(ConsoleCompilerBoundUiState state)
    {
        // ─── Банк данных ───
        _availableDataLabel.Text = $"ПАМЯТЬ: {state.AvailableData} данных";
        _digitizeButton.Disabled = !state.HasReceiverItem || state.IsPrinting;
        _ejectReceiverButton.Disabled = !state.HasReceiverItem || state.IsPrinting;

        // ─── Компилятор ───
        if (state.HasMasterDisk)
        {
            _masterDiskLabel.Text = $"Загружено: {state.MasterDiskName}";
            _usesLeftLabel.Text = $"Остаток ресурса: {state.MasterDiskUsesLeft} использований";
        }
        else
        {
            _masterDiskLabel.Text = "Загружено: нет диска";
            _usesLeftLabel.Text = "Остаток ресурса: —";
        }

        // Кнопки печати: включены если есть мастер-диск, хватает данных, не идёт печать
        var canPrintBlueprint = state.HasMasterDisk
                                && state.MasterDiskUsesLeft > 0
                                && state.AvailableData >= state.BlueprintCost
                                && !state.IsPrinting;

        var canPrintRecipe = state.HasMasterDisk
                             && state.MasterDiskUsesLeft > 0
                             && state.AvailableData >= state.RecipeCost
                             && !state.IsPrinting;

        _printBlueprintButton.Text = $"[ ПЕЧАТЬ: ЧЕРТЁЖ ] — {state.BlueprintCost} данных";
        _printBlueprintButton.Disabled = !canPrintBlueprint;

        _printRecipeButton.Text = $"[ ПЕЧАТЬ: РЕЦЕПТ ] — {state.RecipeCost} данных";
        _printRecipeButton.Disabled = !canPrintRecipe;

        _ejectMasterButton.Disabled = !state.HasMasterDisk || state.IsPrinting;

        // ─── Статус ───
        if (state.IsPrinting)
            _statusLabel.Text = "⏳ Идёт компиляция...";
        else if (!state.HasMasterDisk)
            _statusLabel.Text = "Вставьте мастер-диск для печати.";
        else
            _statusLabel.Text = "Готово к печати.";
    }
}
