- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Security
    min: 36000 # DeltaV - 10 hours
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
      - Foreigner
      - ForeignerLight
      - Muted
      - Blindness
      - Pacifist
      - BrittleBoneDisease
  - !type:CharacterEmployerRequirement
      employers:
      - ZavodskoiInterstellar
      - PMCG
      - NanoTrasen
  - !type:CharacterOverallTimeRequirement # WWDP
    min: 3600
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Maintenance
  - Service
  - Detective
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: DetectiveGear
  subGear:
  - DetectivePlasmamanGear

  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack # WWDP
    # eyes: ClothingEyesGlassesSunglasses # WWDP
    head: ClothingHeadHatFedoraBrown
    # outerClothing: ClothingOuterVestDetective # WWDP
    id: DetectivePDA
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
    belt: ClothingBeltHolsterFilled
  innerClothingSkirt: ClothingUniformJumpskirtDetective
  satchel: ClothingBackpackSatchelSecurity
  duffelbag: ClothingBackpackDuffelSecurity

- type: startingGear
  id: DetectivePlasmamanGear
  parent: BasePlasmamanSecurityGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitDetective
    head: ClothingHeadEnvirohelmDetective
    gloves: ClothingHandsGlovesEnviroglovesWhite
