- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  # WD EDIT START
  # - !type:CharacterDepartmentTimeRequirement
  #   department: Security
  #   min: 36000
  # WD EDIT END
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    - Foreigner
    - ForeignerLight
    - Muted
    - Blindness
    - Pacifist
    - BrittleBoneDisease
  - !type:CharacterEmployerRequirement
    employers:
    - ZavodskoiInterstellar
    - PMCG
    - NanoTrasen
  # WD EDIT START
  - !type:CharacterOverallTimeRequirement
    min: 3600
  # WD EDIT END
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Maintenance
  - Service
  - Detective
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: DetectiveGear
  subGear:
  - DetectivePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack # WD EDIT: ClothingShoesBootsCombatFilled -> ClothingShoesBootsJack
    # eyes: ClothingEyesGlassesSecurity - WD EDIT
    head: ClothingHeadHatFedoraBrown
    # outerClothing: ClothingOuterVestDetective - WD EDIT
    id: DetectivePDA
    ears: ClothingHeadsetAltSecurityRegular
    belt: ClothingBeltHolsterFilled

- type: startingGear
  id: DetectivePlasmamanGear
  parent: BasePlasmamanSecurityGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitDetective
    head: ClothingHeadEnvirohelmDetective
    gloves: ClothingHandsGlovesEnviroglovesWhite
