- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
  # WD EDIT START
  # - !type:CharacterDepartmentTimeRequirement
  #   department: Security
  #   min: 36000 # 10 hours
  # WD EDIT END
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    - Foreigner
    - ForeignerLight
    - Muted
    - Blindness
    - Pacifist
    - BrittleBoneDisease
  - !type:CharacterEmployerRequirement
    employers:
    - ZavodskoiInterstellar
    - PMCG
    - NanoTrasen
    - EastOrionCompany
  # WD EDIT START
  - !type:CharacterOverallTimeRequirement
    min: 3600
  # WD EDIT END
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: SecurityOfficerGear
  subGear:
  - SecurityOfficerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack # WD EDIT: ClothingShoesBootsCombatFilled -> ClothingShoesBootsJack
    # eyes: ClothingEyesGlassesSecurity - WD EDIT
    # head: ClothingHeadHelmetBasic - WD EDIT
    # outerClothing: ClothingOuterArmorPlateCarrier - WD EDIT
    id: SecurityPDA
    ears: ClothingHeadsetAltSecurityRegular
    # belt: ClothingBeltSecurityFilled - WD EDIT
  storage:
    back:
    - WeaponEnergyGunPistolSecurity # WD EDIT

- type: startingGear
  id: SecurityOfficerPlasmamanGear
  parent: BasePlasmamanSecurityGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitSec
    head: ClothingHeadEnvirohelmSec
    gloves: ClothingHandsGlovesEnviroglovesBlack
