- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 36000 # 10 hours
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - BrittleBoneDisease
    - !type:CharacterEmployerRequirement
      employers:
      - ZavodskoiInterstellar
      - PMCG
      - NanoTrasen
      - EastOrionCompany
    - !type:CharacterOverallTimeRequirement # WWDP
      min: 3600
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: SecurityOfficerGear
  subGear:
  - SecurityOfficerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurityFilled # WWDP
    shoes: ClothingShoesBootsJack # WWDP
    # eyes: ClothingEyesGlassesSunglasses # WWDP moved everything to lockers
    # head: ClothingHeadHelmetBasic # WWDP
    # outerClothing: ClothingOuterArmorPlateCarrier # DeltaV - ClothingOuterArmorBasic replaced in favour of plate carrier # WWDP
    id: SecurityPDA
    ears: ClothingHeadsetAltSecurityRegular # Goobstation
  innerClothingSkirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSatchelSecurity
  duffelbag: ClothingBackpackDuffelSecurity

- type: startingGear
  id: SecurityOfficerPlasmamanGear
  parent: BasePlasmamanSecurityGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitSec
    head: ClothingHeadEnvirohelmSec
    gloves: ClothingHandsGlovesEnviroglovesBlack
