- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
  # WD EDIT START
  # - !type:CharacterPlaytimeRequirement
  #   tracker: JobSecurityOfficer
  #   min: 43200 # DeltaV - 12 hrs
  # - !type:CharacterPlaytimeRequirement
  #   tracker: JobDetective
  #   min: 14400 # DeltaV - 4 hours
  # WD EDIT END
  - !type:CharacterWhitelistRequirement
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    - Foreigner
    - ForeignerLight
    - Muted
    - Blindness
    - Pacifist
    - BrittleBoneDisease
  - !type:CharacterEmployerRequirement
    employers:
    - ZavodskoiInterstellar
    - PMCG
    - NanoTrasen
  # WD EDIT START
  - !type:CharacterOverallTimeRequirement
    min: 3600
  # WD EDIT END
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: WardenGear
  subGear:
  - WardenPlasmamanGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack # WD EDIT: ClothingShoesBootsCombatFilled -> ClothingShoesBootsJack
    # eyes: ClothingEyesGlassesSecurity - WD EDIT
    # outerClothing: ClothingOuterCoatWarden - WD EDIT
    id: WardenPDA
    ears: ClothingHeadsetAltSecurityRegular
    # belt: ClothingBeltSecurityFilled - WD EDIT
  storage:
    back:
    - WeaponEnergyGunPistolSecurity # WD EDIT

- type: startingGear
  id: WardenPlasmamanGear
  parent: BasePlasmamanSecurityGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitWarden
    head: ClothingHeadEnvirohelmWarden
    gloves: ClothingHandsGlovesEnviroglovesBlack
