- type: startingGear
  id: OxygenBreather
  abstract: true
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Arachnid
    - Diona
    - Dwarf
    - Felinid
    - Gingerbread
    - Harpy
    - Human
    - Lamia
    - Moth
    - Oni
    - Reptilian

- type: startingGear
  id: NitrogenBreather
  abstract: true
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - SlimePerson
    - Vox

- type: startingGear
  id: PlasmaBreather
  abstract: true
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Plasmaman
