## Static

- type: latheRecipePack
  id: SecurityHypoStatic
  recipes:
  - CartridgeEpinephrine
  - CartridgeBicaridine
  - CartridgeDermaline
  - CartridgeAtropine
  - CartridgeSaline
  - CartridgePain
  - SecHypo

- type: latheRecipePack
  id: SecurityClothingStatic
  recipes:
  # - ClothingOuterArmorPlateCarrier - WD EDIT
  # - ClothingOuterArmorDuraVest - WD EDIT
  - ClothingHeadHelmetBasic

## Dynamic

- type: latheRecipePack
  id: SecurityClothing
  recipes:
  - ClothingEyesNightVisionSecurityGoggles
  - ClothingHeadHelmetInsulated
  - ClothingHeadCage
  - ClothingOuterHardsuitCombatStandard
  - ClothingOuterHardsuitCombatMedical
  - ClothingOuterHardsuitCombatRiot
  - ClothingOuterHardsuitCombatAdvanced
  - ClothingOuterHardsuitShanlinUnpainted
  - ClothingOuterHardsuitShiweiUnpainted
  - ClothingOuterHardsuitJuggernautReverseEngineered
