using Content.Client.UserInterface.Controls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Numerics;
using Content.Client.Guidebook;
using Content.Client.Guidebook.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._White.Event;

[GenerateTypedNameReferences]
public sealed partial class EventItemDispenserConfigWindow : DefaultWindow
{
    public EventItemDispenserConfigWindow()
    {
        //RobustXamlLoader.Load(this); // HATE HATE HATE HATE HATE HATE HATE HATE
        //LineEdit1.IsValid += VerifyInt;
        
    }

    private bool VerifyInt(string input)
    {
        return int.TryParse(input, out var _);
    }
}
