- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  setPreference: false # WWDP disabled role, not mapped
  requirements:
    # - !type:CharacterPlaytimeRequirement # WWDP
    #   tracker: JobAtmosphericTechnician
    #   min: 21600 #6 hrs
    # - !type:CharacterPlaytimeRequirement
    #   tracker: JobStationEngineer
    #   min: 21600 #6 hrs
    # - !type:CharacterDepartmentTimeRequirement
    #   department: Engineering
    #   min: 216000 # 60 hrs
    - !type:CharacterEmployerRequirement
      employers:
      - HephaestusIndustries
      - ZavodskoiInterstellar
      - EinsteinEngines
      - NanoTrasen
    - !type:CharacterOverallTimeRequirement # WWDP
      min: 3600
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  subGear:
  - StationEngineerPlasmamanGear
  equipment:
    head: ClothingHeadHatBeretEngineering
    jumpsuit: ClothingUniformJumpsuitSeniorEngineer
    back: ClothingBackpackEngineering
    shoes: ClothingShoesBootsWork
    id: SeniorEngineerPDA
    # eyes: ClothingEyesGlassesMeson # WWDP
    # belt: ClothingBeltUtilityEngineering # WWDP
    ears: ClothingHeadsetEngineering
