- type: job
  id: StationEngineer
  name: job-name-engineer
  description: job-description-engineer
  playTimeTracker: JobStationEngineer
  requirements:
  # WD EDIT START
  # - !type:CharacterDepartmentTimeRequirement
  #   department: Engineering
  #   min: 14400 #4 hrs
  # WD EDIT END
  - !type:CharacterEmployerRequirement
    employers:
    - HephaestusIndustries
    - ZavodskoiInterstellar
    - EinsteinEngines
    - NanoTrasen
  # WD EDIT START
  - !type:CharacterOverallTimeRequirement
    min: 3600
  # WD EDIT END
  startingGear: StationEngineerGear
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  extendedAccess:
  - Atmospherics

- type: startingGear
  id: StationEngineerGear
  subGear:
  - StationEngineerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: ClothingBackpackEngineering
    shoes: ClothingShoesBootsWork
    id: EngineerPDA
    # eyes: ClothingEyesGlassesMeson - WD EDIT
    # belt: ClothingBeltUtilityEngineering - WD EDIT
    ears: ClothingHeadsetEngineering

- type: startingGear
  id: StationEngineerPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitEngineering
    head: ClothingHeadEnvirohelmEngineering
    gloves: ClothingHandsGlovesEnviroglovesEngineering
