using Content.Client._White.UserInterface.Systems.TargetDoll.Controls;
using Content.Shared._White.Body.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._White.UserInterface.Systems.TargetDoll.Widgets;

[GenerateTypedNameReferences]
public sealed partial class TargetDollGui : UIWidget
{
    private readonly Dictionary<BodyProviderType, BodyProviderButton> _bodyProviderButtons;

    public TargetDollGui()
    {
        RobustXamlLoader.Load(this);
        var controller = UserInterfaceManager.GetUIController<TargetDollUIController>();

        _bodyProviderButtons = new();
        foreach (var provider in Control.Providers.Children)
        {
            if (provider is not BodyProviderButton providerButton)
                continue;

            providerButton.MouseFilter = MouseFilterMode.Stop;
            providerButton.OnPressed += _ => controller.SelectProvider(providerButton.Provider);
            providerButton.OnMouseEntered += _ => Control.TextureHovered = providerButton.TextureHovered;
            providerButton.OnMouseExited += _ => Control.TextureHovered = null;

            _bodyProviderButtons[providerButton.Provider] = providerButton;
        }
    }

    public void OnTargetDollUpdated(BodyProviderType provider)
    {
        Control.TextureFocused = _bodyProviderButtons[provider].TextureFocused;
    }
}
