- type: gameMapPool
  id: DefaultMapPool
  maps:
  # WD EDIT START - white dream maps
  - Kettle
  - Moose
  - WonderBox
  - WhiteMeta
  # TempChange 0 start
  - Gax
  - Asterisk
  - Bagel
  - Pebble
  - Saltern
  - Anchor
  - Core
  - Shoukou
  # TempChange 0 end
  # WD EDIT END
