- type: job
  id: Zookeeper
  name: job-name-zookeeper
  description: job-description-zookeeper
  playTimeTracker: JobZookeeper
  startingGear: ZookeeperGear
  setPreference: false # WWDP disabled
  icon: "JobIconZookeeper"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Zookeeper # DeltaV - Add Zookeeper access
  requirements:
    - !type:CharacterEmployerRequirement
      inverted: true
      employers:
      - Unemployed

- type: startingGear
  id: ZookeeperGear
  subGear:
  - ZookeeperPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSafari
    back: ClothingBackpackFilled
    head: ClothingHeadSafari
    shoes: ClothingShoesColorWhite
    id: ZookeeperPDA
    ears: ClothingHeadsetService
    pocket2: CandyBucket
  innerClothingSkirt: ClothingUniformJumpsuitSafari
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: ZookeeperPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitSafari
    head: ClothingHeadEnvirohelmSafari
    gloves: ClothingHandsGlovesEnviroglovesPurple
