- type: entity
  id: NCStationBank
  parent: BaseStationCargo
  name: station bank settings
  components:
  - type: StationBank
    accounts:
      CityAdmin:
        balance: 0
        increasePerSecond: 0
      TraumaTeam:
        balance: 10000
        increasePerSecond: 5
      Militech:
        balance: 25000
        increasePerSecond: 8
      Biotechnica:
        balance: 15000
        increasePerSecond: 6
      Ncpd:
        balance: 5000
        increasePerSecond: 0
