# Jobs CivilianNC
- type: playTimeTracker
  id: JobCitizen
- type: playTimeTracker
  id: JobReaper
- type: playTimeTracker
  id: JobFixer
- type: playTimeTracker
  id: JobEdgeRunnerSolo

# Jobs NCPD
- type: playTimeTracker
  id: JobNCPDChief
- type: playTimeTracker
  id: JobNCPDWatchAgent
- type: playTimeTracker
  id: JobNCPDSergeant
- type: playTimeTracker
  id: JobNCPDOfficer
- type: playTimeTracker
  id: JobNCPDCadet
- type: playTimeTracker
  id: JobMaxTacCommander
- type: playTimeTracker
  id: JobMaxTacOperative
- type: playTimeTracker
  id: JobMaxTacNetrunner

# Jobs Militech
- type: playTimeTracker
  id: JobHoDM

- type: playTimeTracker
  id: JobHoSM

- type: playTimeTracker
  id: JobMedTechM

- type: playTimeTracker
  id: JobOperativeM

- type: playTimeTracker
  id: JobSCM

- type: playTimeTracker
  id: JobSecM
