# Jobs CivilianNC
- type: playTimeTracker
  id: JobNCCitizen
- type: playTimeTracker
  id: JobReaper
- type: playTimeTracker
  id: JobFixer
- type: playTimeTracker
  id: JobEdgeRunnerSolo

# Jobs NCPD
- type: playTimeTracker
  id: JobNCPDChief
- type: playTimeTracker
  id: JobNCPDWatchAgent
- type: playTimeTracker
  id: JobNCPDSergeant
- type: playTimeTracker
  id: JobNCPDOfficer
- type: playTimeTracker
  id: JobNCPDCadet
- type: playTimeTracker
  id: JobMaxTacCommander
- type: playTimeTracker
  id: JobMaxTacOperative
- type: playTimeTracker
  id: JobMaxTacNetrunner

# Jobs TraumaTeam
- type: playTimeTracker
  id: JobTraumaTeamChief
- type: playTimeTracker
  id: JobTraumaTeamDoctor
- type: playTimeTracker
  id: JobTraumaTeamChemist
- type: playTimeTracker
  id: JobTraumaTeamParamedic
- type: playTimeTracker
  id: JobTraumaTeamOperative
