# Jobs CivilianNC
- type: playTimeTracker
  id: JobNCCitizen
- type: playTimeTracker
  id: JobReaper
- type: playTimeTracker
  id: JobFixer
- type: playTimeTracker
  id: JobEdgeRunnerSolo

# Jobs NCPD
- type: playTimeTracker
  id: JobNCPDChief
- type: playTimeTracker
  id: JobNCPDCommander
- type: playTimeTracker
  id: JobNCPDInspector
- type: playTimeTracker
  id: JobNCPDLieutenant
- type: playTimeTracker
  id: JobNCPDSergeant
- type: playTimeTracker
  id: JobNCPDOfficer
- type: playTimeTracker
  id: JobNCPDWatchAgent
- type: playTimeTracker
  id: JobMaxTacCommander
- type: playTimeTracker
  id: JobMaxTacNetrunner
- type: playTimeTracker
  id: JobMaxTacEraser
- type: playTimeTracker
  id: JobMaxTacPretor
- type: playTimeTracker
  id: JobMaxTacInterdictor

# Jobs TraumaTeam
- type: playTimeTracker
  id: JobTraumaTeamChief
- type: playTimeTracker
  id: JobTraumaTeamDoctor
- type: playTimeTracker
  id: JobTraumaTeamParamedic
- type: playTimeTracker
  id: JobTraumaTeamOperative
- type: playTimeTracker
  id: JobTraumaTeamTech
- type: playTimeTracker
  id: JobTraumaTeamCoroner
- type: playTimeTracker
  id: JobTraumaTeamPsych

