- type: job
  id: NCCitizen
  name: Житель
  description: job-description-citizen
  playTimeTracker: JobNCCitizen
  salary: 50
  startingGear: NCCitizenGear
  access:
    - NC_General

- type: startingGear
  id: NCCitizenGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackSatchel
    shoes: ClothingShoesColorBlack
    id: CitizenPDA
    ears: ClothingHeadsetGrey
