- type: job
  id: NCCitizen
  name: Житель
  description: job-description-citizen
  playTimeTracker: JobNCCitizen
  startingGear: NCCitizenGear
  access:
    - Service

- type: startingGear
  id: NCCitizenGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackSatchel
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
