- type: job
  id: Citizen
  name: Житель
  description: job-description-citizen
  playTimeTracker: JobCitizen
  startingGear: CitizenGear
  access:
    - Service

  startingGear:
    id: CitizenGear
    equipment:
      jumpsuit: ClothingUniformJumpsuitColorGrey
      back: ClothingBackpackSatchel
      shoes: ClothingShoesColorBlack
      id: PassengerPDA
