- type: job
  id: EdgeRunnerSolo
  name: Эджраннер
  description: job-description-edgerunner
  playTimeTracker: JobEdgeRunnerSolo
  salary: 0
  access:
    - NC_General
  startingGear: EdgeRunnerSoloGear

- type: startingGear
  id: EdgeRunnerSoloGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackSatchelSecurity
    shoes: ClothingShoesBootsCombat
    id: PassengerPDA
    ears: ClothingHeadsetAltSecurity
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
