- type: job
  id: NCPDChief
  name: Начальник департамента полиции
  description: job-description-ncpd-chief
  playTimeTracker: JobNCPDChief
  requirements:
    - !type:RoleTimeRequirement
      role: JobNCPDOfficer
      time: 18000 # 5 hours
  weight: 10
  startingGear: NCPDChiefGear
  icon: "JobIconNCPDChief"
  supervisors: job-supervisors-centcom
  access:
    - Command
    - Security
    - Armory
    - Brig
    - Detective
    - Weapons
    - Maintenance
    - External

- type: startingGear
  id: NCPDChiefGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSheriff
    back: ClothingBackpackSatchelSecurity
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatSheriff
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetSecurity
    id: HoSPDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterCoatHoS
