- type: job
  id: NCPDChief
  name: Начальник департамента полиции
  description: job-description-ncpd-chief
  playTimeTracker: JobNCPDChief
  weight: 10
  startingGear: NCPDChiefGear
  supervisors: job-supervisors-centcom
  access:
    - Command
    - Security
    - Armory
    - Brig
    - Detective
    - Weapons
    - Maintenance
    - External

- type: startingGear
  id: NCPDChiefGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSheriff
    back: ClothingBackpackSatchelSecurity
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatSheriff
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetSecurity
    id: HoSPDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterCoatHoS
