- type: job
  id: NCPDCommander
  name: Коммандер
  description: Вы — правая рука закона и левая нога бюрократии. Пока шеф светит лицом на банкетах, вы разгребаете отчеты о расстрелянных патрульных и решаете, на какой район сегодня хватит патронов. Помните: вы уже слишком высоко, чтобы пачкать руки в крови, но все еще недостаточно богаты, чтобы игнорировать звонки из Militech
  playTimeTracker: JobNCPDCommander
  weight: 20
  salary: 1000
  startingGear: NCPDCommanderGear
  supervisors: Начальник департамента полиции
  access:
    - NCPD_Patrol
    - NC_General

- type: startingGear
  id: NCPDCommanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecBlue
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHelmetBasic
    ears: ClothingHeadsetAltSecurity
    id: NCPDCommanderPDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterArmorBasic
