- type: job
  id: NCPDOfficer
  name: Офицер полиции
  description: job-description-ncpd-officer
  playTimeTracker: JobNCPDOfficer
  startingGear: NCPDOfficerGear
  icon: "JobIconSecurityOfficer" #TODO: заменить иконку
  access:
    - NCPD


- type: startingGear
  id: NCPDOfficerGear
  equipment:
    id: HoPPDA
    jumpsuit: ClothingUniformJumpsuitBlueshieldOfficer
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    back: ClothingBackpackSatchelSecurity
    shoes: ClothingShoesChameleonNoSlips
    head: ClothingHeadHatSecsoft
    eyes: ClothingEyesGlassesSecurity