- type: job
  id: NCPDInspector
  name: Инспектор NCPD
  description: job-description-ncpd-prosecutor
  playTimeTracker: JobNCPDInspector
  startingGear: NCPDInspectorGear
  icon: "JobIconLawyer" #TODO: заменить иконку
  access:
    - ArmoryNCPD
    - ProsecutorNCPD
    - NCPD

- type: startingGear
  id: NCPDInspectorGear
  equipment:
    id: HoPPDA
    jumpsuit: ClothingUniformJumpsuitBlueshieldOfficer
    outerCloting: ClothingOuterCoatDetectiveLoadout
    ears: ClothingHeadsetSecurity
    back: ClothingBackpackSatchelSalvage
    shoes: ClothingShoesBootsCombat
    eyes: ClothingEyesGlassesSecurity