- type: job
  id: NCPDSWAT
  name: Спецназ NCPD
  description: job-description-ncpd-swat
  playTimeTracker: JobNCPDSWAT
  startingGear: NCPDSWATGear
  icon: "JobIconSecurityOfficer" #TODO: заменить иконку
  access:
    - NCPD
    - ArmoryNCPD
    - SecurityNCPD

- type: startingGear
  id: NCPDSWATGear
  equipment:
    id: HoPPDA
    jumpsuit: ClothingUniformJumpsuitCentcomOfficerBlack
    outerCloting: ClothingOuterArmorBulletproof
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltAssaultFilled
    back: ClothingBackpackSatchelSecurity
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHelmetBasic
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesGlassesSecurity