- type: job
  id: NCPDSergeant
  name: Сержант
  description: job-description-ncpd-sergeant
  playTimeTracker: JobNCPDSergeant
  weight: 10
  startingGear: NCPDSergeantGear
  supervisors: job-supervisors-ncpd-chief
  access:
    - NCPD_Patrol
    - NCPD_Armory
    - NC_General

- type: startingGear
  id: NCPDSergeantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatWarden
    ears: ClothingHeadsetSecurity
    id: WardenPDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterArmorWarden
