- type: job
  id: NCPDSergeant
  name: Старший патрульный
  description: Стандартный патрульный, относящийся к сержантскому составу и знающий улицу лучше, чем собственную квартиру. Ваша смена — это лотерея между "скучным дежурством" и "кровавой баней", где бронежилет защищает от пуль, но не от цинизма. Если вы доживете до конца дня без новых дырок в теле — это уже отличный повод выпить синтетического пива
  playTimeTracker: JobNCPDSergeant
  weight: 10
  salary: 600
  startingGear: NCPDSergeantGear
  supervisors: Лейтенант
  access:
    - NCPD_Patrol
    - NCPD_Armory
    - NC_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: MapBeacon
      group: NCPD
      color: "#ffaa00"
      icon: /Textures/Interface/VerbIcons/star-solid-yellow.svg.192dpi.png
      visibleInWorld: false

- type: startingGear
  id: NCPDSergeantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatWarden
    ears: ClothingHeadsetAltSecurity
    id: NCPDSergeantPDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterCoatWarden
