- type: job
  id: NCPDWatchAgent
  name: Агент Дозора
  description: 'Вы — цифровой инквизитор, охраняющий человечество от того, что таится за Черным Заслоном. Пока нетраннеры-самоучки ломают торговые автоматы, вы выслеживаете ИскИны и поджариваете мозги тем, кто пытается проковырять дырку в стене между реальностью и цифровым адом. Помните: в Сети нет места состраданию — либо вы держите барьер, либо из вашего терминала полезет то, чему не место в нашем мире'
  playTimeTracker: JobNCPDWatchAgent
  weight: 10
  salary: 800
  startingGear: NCPDWatchAgentGear
  supervisors: Начальник департамента полиции
  access:
    - NCPD_Patrol
    - NCPD_Detective
    - NC_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: MapBeacon
      group: NCPD
      color: "#ffaa00"
      icon: /Textures/Interface/VerbIcons/star-solid-yellow.svg.192dpi.png
      visibleInWorld: false

- type: startingGear
  id: NCPDWatchAgentGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    back: ClothingBackpackSatchelSecurity
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatFedoraBrown
    ears: ClothingHeadsetSecurity
    id: NCPDWatchAgentPDA
    outerClothing: ClothingOuterCoatDetective
