- type: entity
  id: BaseMob
  abstract: true
  save: false
  components:
  - type: Actions
  - type: Alerts
  - type: Appearance
  - type: CameraRecoil
  - type: Clickable
  - type: ContentEye
  - type: DoAfter
  - type: Examiner
  - type: Eye
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 50
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: Input
    context: human
  - type: InputMover
  - type: InteractionOutline
  - type: LagCompensation
  - type: LanguageSpeaker
  - type: LightningTarget
    priority: 2
    lightningExplode: false
  - type: MindContainer
  - type: MobMover
  - type: MobState
  - type: MobStateOverlay
  - type: MobThresholdSounds
  - type: MovementSpeedModifier
  - type: OwnInteractionVerbs
  - type: Penetrated
  - type: Physics
    bodyType: KinematicController
  - type: Polymorphable
  - type: Pullable
  - type: RequireProjectileTarget
    active: False
  - type: RotationVisuals
    defaultRotation: 0
    horizontalRotation: 0
  - type: Sprite
    noRot: true
    drawdepth: Mobs
  - type: StatusIcon

- type: entity
  id: BaseMobAtmos
  abstract: true
  components:
  - type: AtmosExposed
  - type: MovedByPressure
  - type: Temperature
    currentTemperature: 310.15
    heatDamageThreshold: 325
    coldDamageThreshold: 0
    specificHeat: 42
    coldDamage:
      Cold : 0.1
    heatDamage:
      Heat : 1.5
  - type: ThermalRegulator
    metabolismHeat: 800
    radiatedHeat: 100
    sweatHeatRegulation: 2000
    shiveringHeatRegulation: 2000
    implicitHeatRegulation: 500
    normalBodyTemperature: 310.15
    thermalRegulationTemperatureThreshold: 0.4

- type: entity
  id: BaseMobAtmosStandard
  parent: BaseMobAtmos
  abstract: true
  components:
  - type: Barotrauma
    damage:
      Blunt: 0.15
  - type: Temperature
    coldDamageThreshold: 260
    coldDamage:
      Cold: 1
    heatDamage:
      Heat: 1
  - type: ThermalRegulator
    sweatHeatRegulation: 500
    shiveringHeatRegulation: 500
    implicitHeatRegulation: 250
  - type: TemperatureSpeed
    thresholds:
      293: 0.8
      280: 0.6
      260: 0.4

- type: entity
  id: BaseMobBlindable
  abstract: true
  components:
  - type: Blindable

- type: entity
  id: BaseMobBloodstream
  abstract: true
  components:
  - type: Bloodstream
  - type: InjectableSolution
    solution: bloodstream
  - type: SolutionContainerManager

- type: entity
  id: BaseMobCombat
  abstract: true
  components:
  - type: CombatMode
  - type: MeleeWeapon
    hidden: true
    soundHit:
      collection: MetalThud
    damage:
      Blunt: 5
  - type: TargetDoll

- type: entity
  id: BaseMobDamageable
  abstract: true
  components:
  - type: Damageable
    container: Biological
  - type: DamageOnHighSpeedImpact
    damage:
      Blunt: 5
    soundHit:
      path: /Audio/Effects/hit_kick.ogg
  - type: Deathgasp
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 400
      behaviors:
      - !type:GibBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 1500
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          Ash:
            min: 1
            max: 1
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact
  - type: HealthExaminable
    examinableTypes:
    - Blunt
    - Slash
    - Piercing
    - Heat
    - Shock
  - type: MobStateActions
    actions:
      Critical:
      - ActionCritSuccumb
      - ActionCritFakeDeath
      - ActionCritLastWords
  - type: MobThresholds
    thresholds:
      0: Alive
      100: Critical
      200: Dead
  - type: RadiationReceiver

- type: entity
  id: BaseMobFlammable
  abstract: true
  components:
  - type: FireVisuals
    sprite: Mobs/Effects/onfire.rsi
    normalState: Generic_mob_burning
  - type: Flammable
    fireSpread: true
    canResistFire: true
    damage:
      Heat: 1

- type: entity
  id: BaseMobHearing
  abstract: true
  components:
  - type: Hearing

- type: entity
  id: BaseMobPainful
  abstract: true
  components:
  - type: Painful
  - type: PainOverlay
  - type: PainStatus
  - type: PainThresholds
    painEffects:
      Moderate:
      - !type:Emote
        emote: PainScream
        showInChat: true
      - !type:Jitter
        amplitude: 24
        frequency: 1
        time: 0.9
      Severe:
      - !type:Emote
        emote: PainScream
        showInChat: true
      - !type:Jitter
        amplitude: 30
        frequency: 12
        time: 0.9
      Excruciating:
      - !type:Emote
        emote: PainScream
        showInChat: true
      - !type:Jitter
        amplitude: 20
        frequency: 7
        time: 4
      - !type:Paralyze
        paralyzeTime: 2
      # TODO: Release of adrenaline into the blood.
      Mortal:
      - !type:Emote
        emote: PainScream
        showInChat: true
      - !type:Jitter
        amplitude: 20
        frequency: 7
        time: 7
      - !type:Paralyze
        paralyzeTime: 3
        # TODO: Release of adrenaline into the blood.

- type: entity
  id: BaseMobRespirator
  abstract: true
  components:
  - type: Internals
  - type: Respirator

- type: entity
  id: BaseMobSatiation
  abstract: true
  components:
  - type: Hunger
  - type: Thirst

- type: entity
  id: BaseMobStamina
  abstract: true
  components:
  - type: Stamina

- type: entity
  id: BaseMobWoundable
  abstract: true
  components:
  - type: Damageable
  - type: DamageOnHighSpeedImpact
    damage:
      Blunt: 5
    soundHit:
      path: /Audio/Effects/hit_kick.ogg
  - type: Deathgasp
  - type: HealthExaminable
    examinableTypes:
    - Blunt
    - Slash
    - Piercing
    - Heat
    - Shock
  - type: MobStateActions
    actions:
      Critical:
      - ActionCritSuccumb
      - ActionCritFakeDeath
      - ActionCritLastWords
  - type: RadiationReceiver
  - type: Woundable
