using System.Linq;
using Content.Client._NC.Trade.Controls;
using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Trade;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.Trade;


[GenerateTypedNameReferences]
public sealed partial class NcStoreMenu : FancyWindow
{
    private readonly Dictionary<string, int> _balancesByCurrency = new();
    private readonly UiStateBinder _binder;
    private readonly List<string> _buyCats = new();
    private readonly NcStoreClientCatalogModel _catalogModel = new();
    private readonly Dictionary<string, int> _massSellTotals = new();
    private readonly IPrototypeManager _proto;
    private readonly HashSet<string> _scratchBuyCatSet = new();
    private readonly HashSet<string> _scratchSellCatSet = new();
    private readonly List<string> _sellCats = new();
    private readonly List<string> _visibleBuyIds = new();
    private readonly List<string> _visibleSellIds = new();
    private readonly HashSet<string> _visibleUnionScratch = new();
    private int _lastVisibleIdsSig;
    private readonly SpriteSystem _sprites;
    private bool _disposed;
    private bool _hasBuyTab;
    private bool _hasContractsTab;
    private bool _hasSellTab;
    private string _search = string.Empty;
    private string _searchLower = string.Empty;
    private Control? _tabBuy;
    private Control? _tabContracts;
    private bool _tabsCaptured;
    private Control? _tabSell;
    public Action<string>? OnContractClaim;
    public NcStoreMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        TabContainer.SetTabTitle(TabBuy, Loc.GetString("nc-store-tab-buy"));
        TabContainer.SetTabTitle(TabSell, Loc.GetString("nc-store-tab-sell"));
        TabContainer.SetTabTitle(TabContracts, Loc.GetString("nc-store-tab-contracts"));
        _sprites = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        _proto = IoCManager.Resolve<IPrototypeManager>();

        Header.BindServices(_proto, _sprites);

        BuyView.Initialize(StoreMode.Buy, _proto, _sprites, Loc.GetString("nc-store-tab-buy"), false);
        SellView.Initialize(StoreMode.Sell, _proto, _sprites, Loc.GetString("nc-store-tab-sell"), true);

        BuyView.ConfigureCategories(GetCategoryDisplayName, GetCategoryToolTip);
        SellView.ConfigureCategories(GetCategoryDisplayName, GetCategoryToolTip);

        BuyView.VisibleIdsChanged += ids =>
        {
            _visibleBuyIds.Clear();
            _visibleBuyIds.AddRange(ids);
            EmitVisibleListingIdsChanged();
        };

        SellView.VisibleIdsChanged += ids =>
        {
            _visibleSellIds.Clear();
            _visibleSellIds.AddRange(ids);
            EmitVisibleListingIdsChanged();
        };

        Header.OnSearchChanged += text =>
        {
            if (_disposed)
                return;

            _search = text;
            _searchLower = text.ToLowerInvariant();
            BuyView.SetSearch(_searchLower);
            SellView.SetSearch(_searchLower);
            OnSearchChanged?.Invoke(_search);
            RefreshListings();
        };

        SellView.MassSellButtonControl.Disabled = true;
        SellView.MassSellButtonControl.ClipText = true;
        SellView.MassSellButtonControl.Text = Loc.GetString("nc-store-mass-sell-button");
        SellView.MassSellButtonControl.ToolTip = Loc.GetString("nc-store-mass-sell-tooltip");
        SellView.MassSellButtonControl.OnPressed += _ => OnMassSellPulledCrate?.Invoke();

        _binder = new(this);
    }

    private string GetCategoryDisplayName(string catId) =>
        catId switch
        {
            NcStoreClientCatalogModel.CatIdReady => Loc.GetString("nc-store-cat-ready-short"),
            NcStoreClientCatalogModel.CatIdCrate => Loc.GetString("nc-store-cat-crate-short"),
            _ => catId
        };

    private string GetCategoryToolTip(string catId) =>
        catId switch
        {
            NcStoreClientCatalogModel.CatIdReady => Loc.GetString("nc-store-cat-ready-full"),
            NcStoreClientCatalogModel.CatIdCrate => Loc.GetString("nc-store-cat-crate-full"),
            _ => catId
        };

    public event Action<string>? OnSearchChanged;
    public event Action<StoreListingData, int>? OnBuyPressed;
    public event Action<StoreListingData, int>? OnSellPressed;
    public event Action? OnMassSellPulledCrate;
    public event Action<string[]>? OnVisibleListingIdsChanged;

    private void EmitVisibleListingIdsChanged()
    {
        if (OnVisibleListingIdsChanged == null)
            return;

        _visibleUnionScratch.Clear();

        for (var i = 0; i < _visibleBuyIds.Count; i++)
        {
            var id = _visibleBuyIds[i];
            if (!string.IsNullOrWhiteSpace(id))
                _visibleUnionScratch.Add(id);
        }

        for (var i = 0; i < _visibleSellIds.Count; i++)
        {
            var id = _visibleSellIds[i];
            if (!string.IsNullOrWhiteSpace(id))
                _visibleUnionScratch.Add(id);
        }

        var arr = _visibleUnionScratch.ToArray();
        Array.Sort(arr, static (a, b) => string.CompareOrdinal(a, b));

        var sig = 17;
        for (var i = 0; i < arr.Length; i++)
            sig = unchecked(sig * 31 + arr[i].GetHashCode());

        if (sig == _lastVisibleIdsSig)
            return;

        _lastVisibleIdsSig = sig;
        OnVisibleListingIdsChanged(arr);
    }

    private int GetBalanceForCurrency(string currencyId)
    {
        if (string.IsNullOrWhiteSpace(currencyId))
            return 0;

        return _balancesByCurrency.GetValueOrDefault(currencyId, 0);
    }

    public void SetBalancesByCurrency(Dictionary<string, int> balances)
    {
        _balancesByCurrency.Clear();

        foreach (var (cur, amt) in balances)
        {
            if (string.IsNullOrWhiteSpace(cur))
                continue;

            _balancesByCurrency[cur] = amt;
        }

        Header.SetBalances(_balancesByCurrency);
    }


    public void SetMassSellTotals(Dictionary<string, int> totals)
    {
        _massSellTotals.Clear();
        foreach (var (cur, amt) in totals)
            _massSellTotals[cur] = amt;
        var btn = SellView.MassSellButtonControl;
        btn.Text = Loc.GetString("nc-store-mass-sell-button");
        btn.ClipText = true;

        if (_massSellTotals.Count == 0)
        {
            btn.ToolTip = Loc.GetString("nc-store-mass-sell-tooltip");
            btn.Disabled = true;
            return;
        }

        btn.Disabled = false;

        var parts = _massSellTotals
            .Where(p => p.Value > 0 && !string.IsNullOrWhiteSpace(p.Key))
            .Select(p => Loc.GetString(
                "nc-store-currency-format",
                ("amount", p.Value),
                ("currency", CurrencyName(p.Key))))
            .ToList();

        var full = parts.Count > 0 ? string.Join(", ", parts) : "—";

        btn.ToolTip = Loc.GetString("nc-store-mass-sell-tooltip-with-reward", ("reward", full));
    }

    private void CaptureTabsIfNeeded()
    {
        if (_tabsCaptured)
            return;

        _tabsCaptured = true;

        _tabBuy = TabBuy;
        _tabSell = TabSell;
        _tabContracts = TabContracts;
    }


    private void EnsureTab(Control? tab, bool shouldExist)
    {
        if (Tabs == null || tab == null)
            return;

        var exists = Tabs.Children.Contains(tab);

        if (shouldExist && !exists)
            Tabs.AddChild(tab);
        else if (!shouldExist && exists)
            Tabs.RemoveChild(tab);
    }


    private void ApplyTabsVisibility()
    {
        if (Tabs == null)
            return;

        CaptureTabsIfNeeded();

        EnsureTab(_tabBuy, _hasBuyTab);
        EnsureTab(_tabSell, _hasSellTab);
        EnsureTab(_tabContracts, _hasContractsTab);

        var count = Tabs.ChildCount;
        if (count <= 0)
            return;

        var curIndex = Tabs.CurrentTab;
        if (curIndex < 0 || curIndex >= count)
            Tabs.CurrentTab = 0;
    }


    public void PopulateCatalog(
        List<StoreListingStaticData> listings,
        bool hasBuyTab,
        bool hasSellTab,
        bool hasContractsTab
    ) =>
        _binder.PopulateCatalog(listings, hasBuyTab, hasSellTab, hasContractsTab);


    private void UpdateHeaderVisibility() => Header.Visible = _hasBuyTab || _hasSellTab;

    private void RebuildCategoriesFromCatalog()
    {
        _buyCats.Clear();
        _sellCats.Clear();

        _scratchBuyCatSet.Clear();
        _scratchSellCatSet.Clear();

        var catalog = _catalogModel.Catalog;
        for (var i = 0; i < catalog.Count; i++)
        {
            var it = catalog[i];
            if (string.IsNullOrWhiteSpace(it.Category))
                continue;

            if (it.Mode == StoreMode.Buy)
                _scratchBuyCatSet.Add(it.Category);
            else if (it.Mode == StoreMode.Sell)
                _scratchSellCatSet.Add(it.Category);
        }

        _buyCats.AddRange(_scratchBuyCatSet);
        _sellCats.AddRange(_scratchSellCatSet);

        _buyCats.Sort(static (a, b) => string.Compare(a, b, StringComparison.CurrentCulture));
        _sellCats.Sort(static (a, b) => string.Compare(a, b, StringComparison.CurrentCulture));

        BuildCategoryButtons();
    }

    private void UpdateVirtualSellCategories()
    {
        var hasReady = false;
        var hasCrate = false;

        var items = _catalogModel.Items;
        for (var i = 0; i < items.Count; i++)
        {
            var it = items[i];

            if (!hasReady && it is { Mode: StoreMode.Sell, Category: NcStoreClientCatalogModel.CatIdReady, })
                hasReady = true;

            if (!hasCrate && it is { Mode: StoreMode.Sell, Category: NcStoreClientCatalogModel.CatIdCrate, })
                hasCrate = true;

            if (hasReady && hasCrate)
                break;
        }

        _sellCats.Remove(NcStoreClientCatalogModel.CatIdReady);
        _sellCats.Remove(NcStoreClientCatalogModel.CatIdCrate);

        var insertIndex = 0;
        if (hasReady)
            _sellCats.Insert(insertIndex++, NcStoreClientCatalogModel.CatIdReady);

        if (hasCrate)
            _sellCats.Insert(insertIndex, NcStoreClientCatalogModel.CatIdCrate);

        BuildCategoryButtons();
    }

    public void ApplyDynamicState(
        Dictionary<string, int> balancesByCurrency,
        Dictionary<string, int> remainingById,
        Dictionary<string, int> ownedById,
        Dictionary<string, int> crateUnitsById,
        Dictionary<string, int> massTotals,
        bool hasBuyTab,
        bool hasSellTab,
        bool hasContractsTab,
        List<ContractClientData> contracts
    ) =>
        _binder.ApplyDynamicState(
            balancesByCurrency,
            remainingById,
            ownedById,
            crateUnitsById,
            massTotals,
            hasBuyTab,
            hasSellTab,
            hasContractsTab,
            contracts);


    private void RebuildItemsFromCatalogAndDynamic()
    {
        _catalogModel.RebuildItemsFromCatalogAndDynamic();
        BuyView.SyncAvailableIds(_catalogModel.AvailableIds);
        SellView.SyncAvailableIds(_catalogModel.AvailableIds);
    }

    public void PopulateContracts(List<ContractClientData>? list)
    {
        var contractList = ContractList;
        if (contractList == null)
            return;

        contractList.RemoveAllChildren();

        if (list == null || list.Count == 0)
        {
            contractList.AddChild(
                new Label
                {
                    Text = Loc.GetString("nc-store-contracts-empty"),
                    HorizontalAlignment = HAlignment.Center,
                    Margin = new(0, 8, 0, 0)
                });

            ApplyTabsVisibility();
            return;
        }

        var ordered = list
            .OrderBy(x => x.Difficulty switch
            {
                "Easy" => 0,
                "Medium" => 1,
                "Hard" => 2,
                _ => 99
            })
            .ThenBy(x => x.Name)
            .ThenBy(x => x.Id)
            .ToList();

        foreach (var c in ordered)
        {
            var card = new NcContractCard(c, _proto, _sprites, IoCManager.Resolve<IEntityManager>());
            card.OnClaim += id => OnContractClaim?.Invoke(id);
            contractList.AddChild(card);
        }

        ApplyTabsVisibility();
    }

    private void RefreshListings()
    {
        var items = _catalogModel.Items;
        BuyView.BindListingsData(items, GetBalanceForCurrency, (d, qty) => OnBuyPressed?.Invoke(d, qty));
        SellView.BindListingsData(items, static _ => int.MaxValue, (d, qty) => OnSellPressed?.Invoke(d, qty));

        BuyView.SetSearch(_searchLower);
        SellView.SetSearch(_searchLower);
    }

    private void BuildCategoryButtons()
    {
        BuyView.SetCategories(_buyCats);
        SellView.SetCategories(_sellCats);
    }

    private string CurrencyName(string? currencyId)
    {
        if (string.IsNullOrWhiteSpace(currencyId))
            return string.Empty;

        if (_proto.TryIndex<StackPrototype>(currencyId, out var stackProto) &&
            _proto.TryIndex<EntityPrototype>(stackProto.Spawn, out var currencyEnt))
            return currencyEnt.Name;

        return currencyId;
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        _disposed = true;
        BuyView.ClearCaches();
        SellView.ClearCaches();
        _catalogModel.Clear();

        base.Dispose(disposing);
    }
}
