using System.Numerics;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Timing;

namespace Content.Client._White.NavalTurretConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class NavalTurretConsoleWindow : FancyWindow, IComputerWindow<NavInterfaceState>
{
    private IGameTiming _timing;
    private Font _font;
    public NavalTurretConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        _font = new VectorFont(IoCManager.Resolve<IResourceCache>().GetResource<FontResource>("/EngineFonts/NotoSans/NotoSans-Regular.ttf"), 16);
        _timing = IoCManager.Resolve<IGameTiming>();
        InitShit();
    }

    public void InitShit()
    {
        //RadarScreen.DrawTop += (handle, shuttleToWorld, worldToView) =>
        //{
        //    var time = IoCManager.Resolve<IGameTiming>();
        //    if (time.CurTime.TotalSeconds % 2 <= 1)
        //        return;
        //    var font = new VectorFont(IoCManager.Resolve<IResourceCache>().GetResource<FontResource>("/EngineFonts/NotoSans/NotoSans-Regular.ttf"), 16);
        //    
        //    var signalText = Loc.GetString("shuttle-console-no-signal");
        //    var dimensions = handle.GetDimensions(font, signalText, 1f);
        //    var position = dimensions / 2f;
        //    position.X *= -1;
        //    handle.DrawString(font, Vector2.Transform(position, shuttleToWorld * worldToView), Loc.GetString("shuttle-console-no-signal"), Color.WhiteSmoke);
        //}
    }

    private void DrawNoSignal(DrawingHandleScreen handle, Matrix3x2 shuttleToWorld, Matrix3x2 worldToView)
    {

        if (_timing.CurTime.TotalSeconds % 2 <= 1)
            return;
        
        var signalText = Loc.GetString("shuttle-console-no-signal");
        var dimensions = handle.GetDimensions(_font, signalText, 1f);
        var position = dimensions / 2f;
        var center = (shuttleToWorld * worldToView).Translation;
        position.X *= -1;
        handle.DrawString(_font, center + position, signalText, Color.WhiteSmoke);
    }

    public void UpdateState(NavInterfaceState scc)
    {
        RadarScreen.UpdateState(scc);
    }
}
