using System.Numerics;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._White.NavalTurretControl.BUIStates;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Timing;

namespace Content.Client._White.NavalTurretConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class NavalTurretConsoleWindow : FancyWindow, IComputerWindow<NavInterfaceState>
{
    // TODO: this and InitShit() is an attempt at avoiding rude changes.
    //       If you see this, it means I am a dumbass and forgot to remove them before pushing.
    private IGameTiming _timing = default!;
    private Font _font = default!;
    public NavalTurretConsoleError Error { get; private set; }

    public NavalTurretConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        InitShit();
    }

    public void InitShit()
    {
        _font = new VectorFont(IoCManager.Resolve<IResourceCache>().GetResource<FontResource>("/Fonts/_White/LCD14/LCD14.otf"), 16);
        _timing = IoCManager.Resolve<IGameTiming>();
        RadarScreen.DrawAfterBackground += DrawNoSignal;
    }

    public void SetError(NavalTurretConsoleError error)
    {
        Error = error;
        RadarScreen.ForceSkip = Error != NavalTurretConsoleError.None;
    }

    private void DrawNoSignal(DrawingHandleScreen handle, UIBox2 controlSize, bool active)
    {
        if (!active || _timing.CurTime.TotalSeconds % 2 > 1)
            return;

        var signalText = Error switch
        {
            NavalTurretConsoleError.NotConnected => "NO SIGNAL",
            NavalTurretConsoleError.NoPowerTurret => "NO POWER",
            NavalTurretConsoleError.TurretDestroyed => "SIGNAL LOST",
            _ => string.Empty
        };
        var dimensions = handle.GetDimensions(_font, signalText, 1f);
        var center = controlSize.Center;
        handle.DrawString(_font, center - dimensions / 2f, signalText, Color.Green);
    }


    public void UpdateState(NavInterfaceState scc)
    {
        RadarScreen.UpdateState(scc);
    }
}
