using System.Linq;
using Content.Client.Eye;
using Content.Client.Resources;
using Content.Shared._NC.CitiNet;
using Content.Shared._NC.CitiNet.Live;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Shared.Prototypes;
using Robust.Shared.Graphics;


namespace Content.Client._NC.CitiNet.UI;

[GenerateTypedNameReferences]
public sealed partial class CitiNetUiFragment : BoxContainer
{
    public Action<CitiNetUiMessageType, string?, string?>? OnSendMessage;
    // NC Live: отправка Live-сообщений
    // public Action<CitiNetLiveMessageType, string?>? OnSendLiveMessage; // Removed as per instruction

    // Current tab index (0=Direct, 1=Chats, 2=DataPool, 3=Status, 4=Live)
    private int _currentTab = 1; // Default to Chat Rooms

    // Cache the state so we can rebuild the UI when switching tabs
    private CitiNetUiState? _lastState;
    private EntityUid? _currentCamera;

    // Cyberpunk specific colors
    private static readonly Color ColorNeonGreen = Color.FromHex("#51f542");
    private static readonly Color ColorDimGreen = Color.FromHex("#1e5c18");
    private static readonly Color ColorAlertRed = Color.FromHex("#f54242");
    private static readonly Color ColorCyberBlue = Color.FromHex("#42e3f5");
    private static readonly Color ColorDarkGrey = Color.FromHex("#444444");
    // private readonly FixedEye _defaultEye = new(); // Removed as per instruction

    public CitiNetUiFragment()
    {
        RobustXamlLoader.Load(this);

        var resourceCache = IoCManager.Resolve<IResourceCache>();
        var protoMan = IoCManager.Resolve<IPrototypeManager>();



        // --- SIDEBAR MENU BINDINGS ---
        MenuDirectCallsBtn.OnPressed += _ => SwitchTab(0);
        MenuChatRoomsBtn.OnPressed += _ => SwitchTab(1);
        MenuDataPoolBtn.OnPressed += _ => SwitchTab(2);
        MenuNetworkStatusBtn.OnPressed += _ => SwitchTab(3);

        // --- CHAT MESSAGE BINDINGS ---
        ChatSendButton.OnPressed += _ =>
        {
            var text = ChatInput.Text.Trim();
            if (string.IsNullOrEmpty(text)) return;

            if (_currentTab == 0 && _lastState?.CurrentContactNumber != null)
                OnSendMessage?.Invoke(CitiNetUiMessageType.SendCallMessage, null, text);
            else if (_currentTab == 1 && _lastState?.CurrentChannelId != null)
                OnSendMessage?.Invoke(CitiNetUiMessageType.SendBBSMessage, null, text);
            else if (_currentTab == 2 && _lastState != null && _lastState.InGroup)
                OnSendMessage?.Invoke(CitiNetUiMessageType.SendGroupMessage, null, text);

            ChatInput.Text = string.Empty;
        };

        // --- ACTION BINDINGS (Middle panel buttons) ---
        ActionButton.OnPressed += HandleActionButton;

        // --- CALL CONTROLS ---
        CallDialButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.InitiateCall, null, null);
        CallAcceptButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.AcceptCall, null, null);
        CallDeclineButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.DeclineCall, null, null);
        CallHangUpButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.HangUp, null, null);
        CallPingLocationButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.PingLocation, null, null);
        CallJoinVoiceButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.JoinGroupVoice, null, null);
        CallLeaveVoiceButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.LeaveGroupVoice, null, null);

        // --- PASSWORD PANNEL ---
        PasswordSubmitBtn.OnPressed += _ =>
        {
            var text = PasswordInput.Text.Trim();
            if (!string.IsNullOrEmpty(text) && _lastState?.CurrentChannelId != null)
            {
                // We send a JoinChannel message with the password as content
                OnSendMessage?.Invoke(CitiNetUiMessageType.JoinChannel, _lastState.CurrentChannelId, text);
                PasswordInput.Text = string.Empty;
            }
        };

        SwitchTab(0);
    }

    private void SwitchTab(int tab)
    {
        _currentTab = tab;

        // Visual update for menu buttons
        var activeColor = ColorNeonGreen;
        var inactiveColor = ColorDimGreen;

        MenuDirectCallsBtn.Modulate = tab == 0 ? activeColor : inactiveColor;
        MenuChatRoomsBtn.Modulate = tab == 1 ? activeColor : inactiveColor;
        MenuDataPoolBtn.Modulate = tab == 2 ? activeColor : inactiveColor;
        MenuNetworkStatusBtn.Modulate = tab == 3 ? activeColor : inactiveColor;

        ListContainer.RemoveAllChildren();
        ContentMessagesContainer.RemoveAllChildren();
        ActionControlsPanel.Visible = false;
        PasswordPanel.Visible = false;
        ChatInputPanel.Visible = false;
        CallControlsPanel.Visible = false;

        if (_lastState != null)
        {
            UpdateUIFields(_lastState);
        }
    }

    private void HandleActionButton(BaseButton.ButtonEventArgs args)
    {
        var input = ActionInput.Text.Trim();
        if (_currentTab == 0) // Start Chat
        {
            if (!string.IsNullOrEmpty(input))
            {
                OnSendMessage?.Invoke(CitiNetUiMessageType.StartChat, input, null);
                ActionInput.Text = string.Empty;
            }
        }
        else if (_currentTab == 2) // Group Actions
        {
            if (_lastState != null && !_lastState.InGroup)
            {
                OnSendMessage?.Invoke(CitiNetUiMessageType.CreateGroup, null, null);
            }
            else if (!string.IsNullOrEmpty(input))
            {
                OnSendMessage?.Invoke(CitiNetUiMessageType.InviteToGroup, input, null);
                ActionInput.Text = string.Empty;
            }
        }
    }

    public void UpdateState(CitiNetUiState state)
    {
        _lastState = state;

        // --- HEADER ---
        NetworkStatusLabel.Text = state.HasRelay ? "[color=#51f542]STATUS: CONNECTED ●[/color]" : "[color=#f54242]STATUS: OFFLINE ○[/color]";
        LocationLabel.Text = state.HasRelay ? "[color=#51f542]SIGNAL Yll[/color]" : "[color=#f54242]SIGNAL None[/color]";
        OnlineStatusLabel.Text = state.HasRelay ? "[color=#51f542][ ONLINE ][/color]" : "[color=#f54242][ OFFLINE ][/color]";
        UsernameLabel.Text = $"[color=#51f542][ USER: AGENT-{state.OwnNumber} ][/color]";

        UpdateUIFields(state);
    }

    private void UpdateUIFields(CitiNetUiState state)
    {
        ListContainer.RemoveAllChildren();
        ContentMessagesContainer.RemoveAllChildren();

        ActionControlsPanel.Visible = false;
        CallControlsPanel.Visible = false;
        PasswordPanel.Visible = false;
        ChatInputPanel.Visible = false;

        switch (_currentTab)
        {
            case 0: // DIRECT CALLS
                RenderDirectCalls(state);
                break;
            case 1: // CHAT ROOMS (BBS)
                RenderChatRooms(state);
                break;
            case 2: // DATA POOL (Group)
                RenderDataPool(state);
                break;
            case 3: // NETWORK STATUS
                RenderNetworkStatus(state);
                break;
                // case 4: // LIVE // Removed as per instruction
                //     RenderLive(state); // Removed as per instruction
                //     break;
        }
    }

    private void RenderDirectCalls(CitiNetUiState state)
    {
        ListTitleLabel.Text = "[ DIRECT CALLS ]";
        ListSubtitleLabel.Text = "CONTACTS:";

        ContentHeaderLabel.Text = "[color=#51f542]● P2P COMMUNICATION[/color]";

        // Кнопка для старта нового чата. Отображается всегда.
        ActionControlsPanel.Visible = true;
        ActionInput.PlaceHolder = "NEW AGENT NUMBER...";
        ActionInput.Visible = true;
        ActionButton.Text = "[START CHAT]";

        if (state.Contacts.Count == 0)
        {
            AddListEntry("[ NO ACTIVE CONTACTS ]", ColorDarkGrey);
        }
        else
        {
            foreach (var contact in state.Contacts)
            {
                var isCurrent = contact.Number == state.CurrentContactNumber;
                var color = isCurrent ? ColorNeonGreen : ColorCyberBlue;
                var prefix = isCurrent ? "▶" : " ";

                var escapedContactName = Robust.Shared.Utility.FormattedMessage.EscapeText(contact.Name);
                var btn = new Button
                {
                    Text = $"{prefix} {escapedContactName} (#{contact.Number})",
                    Modulate = color,
                    StyleClasses = { "OpenBoth" },
                    Margin = new Thickness(0, 0, 0, 4)
                };

                btn.OnPressed += _ =>
                {
                    OnSendMessage?.Invoke(CitiNetUiMessageType.StartChat, contact.Number, null);
                };

                ListContainer.AddChild(btn);
            }
        }

        if (state.CurrentContactNumber == null)
        {
            AddMessage("[color=#444444]SELECT A CONTACT TO VIEW MESSAGES[/color]");
            return;
        }

        // Рендер сообщений открытого чата
        foreach (var msg in state.CallMessages)
        {
            var color = msg.IsSystem ? "#f54242" : "#42e3f5";
            var escapedMsg = Robust.Shared.Utility.FormattedMessage.EscapeText(msg.Content);
            var escapedName = Robust.Shared.Utility.FormattedMessage.EscapeText(msg.SenderName);
            AddMessage($"[color={color}]\\[{msg.Timestamp:hh\\:mm}\\] {escapedName}:[/color] {escapedMsg}");
        }

        ChatInputPanel.Visible = true;
        CallControlsPanel.Visible = true;

        CallDialButton.Visible = state.CallState == CitiNetCallState.None;
        CallPingLocationButton.Visible = true;
        CallAcceptButton.Visible = state.CallState == CitiNetCallState.Incoming;
        CallDeclineButton.Visible = state.CallState == CitiNetCallState.Incoming;
        CallHangUpButton.Visible = state.CallState == CitiNetCallState.Active || state.CallState == CitiNetCallState.Ringing;
        CallJoinVoiceButton.Visible = false;
        CallLeaveVoiceButton.Visible = false;

        string voiceStr = state.CallState switch
        {
            CitiNetCallState.Active => "[color=#51f542]● VOICE: CONNECTED[/color]",
            CitiNetCallState.Ringing => "[color=#e3f542]● VOICE: RINGING...[/color]",
            CitiNetCallState.Incoming => "[color=#f54242]● VOICE: INCOMING CALL[/color]",
            _ => "[color=#444444]○ VOICE: DISCONNECTED[/color]"
        };

        CallControlsStatusLabel.Text = voiceStr;
    }

    private void RenderChatRooms(CitiNetUiState state)
    {
        ListTitleLabel.Text = "[ CHAT ROOMS ]";
        ListSubtitleLabel.Text = "AVAILABLE NETWORKS:";
        ContentHeaderLabel.Text = "[color=#51f542]● PUBLIC / SECURE BBS[/color]";

        var channels = state.Channels;
        if (channels.Count == 0)
        {
            AddListEntry("No channels found", ColorDarkGrey);
            return;
        }

        foreach (var channel in channels)
        {
            var btn = new Button
            {
                Text = $"{(channel.IsJoined ? "●" : "○")} {channel.Name}",
                HorizontalAlignment = HAlignment.Left,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2)
            };

            // Highlight selected
            if (state.CurrentChannelId == channel.Id)
                btn.Modulate = ColorNeonGreen;
            else
                btn.Modulate = channel.Color;

            btn.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.JoinChannel, channel.Id, null);
            ListContainer.AddChild(btn);
        }

        var curChannel = channels.FirstOrDefault(c => c.Id == state.CurrentChannelId);
        if (curChannel.Id != null)
        {
            ContentHeaderLabel.Text = $"[color=#{curChannel.Color.ToHex()}]● {curChannel.Name.ToUpper()}[/color]";

            if (curChannel.RequiresPassword && !curChannel.IsJoined)
            {
                PasswordPanel.Visible = true;
                AddMessage($"[color=#f54242]>> SYSTEM: SECURED CHANNEL. ENTER ACCESS CODE.[/color]");
            }
            else if (curChannel.IsJoined)
            {
                ChatInputPanel.Visible = true;
                foreach (var msg in state.ChannelMessages)
                {
                    var escapedMsg = Robust.Shared.Utility.FormattedMessage.EscapeText(msg.Content);
                    var escapedName = Robust.Shared.Utility.FormattedMessage.EscapeText(msg.SenderName);
                    AddMessage($"[color={curChannel.Color.ToHex()}]\\[{msg.Timestamp:hh\\:mm}\\] {escapedName}:[/color] {escapedMsg}");
                }
            }
        }
    }

    private void RenderDataPool(CitiNetUiState state)
    {
        ListTitleLabel.Text = "[ DATA POOL ]";
        ListSubtitleLabel.Text = "TACTICAL BRIDGE:";

        if (!state.InGroup)
        {
            ContentHeaderLabel.Text = "[color=#51f542]● TACTICAL BRIDGE: OFFLINE[/color]";
            AddListEntry("BRIDGE: OFFLINE", ColorDarkGrey);

            ActionControlsPanel.Visible = true;
            ActionInput.Visible = false;
            ActionButton.Text = "[CREATE TACTICAL BRIDGE]";
            return;
        }

        ContentHeaderLabel.Text = "[color=#51f542]● TACTICAL BRIDGE: ONLINE[/color]";
        ActionControlsPanel.Visible = true;
        ActionInput.Visible = true;
        ActionInput.PlaceHolder = "AGENT NUMBER...";
        ActionButton.Text = "[INVITE AGENT]";

        ChatInputPanel.Visible = true;
        CallControlsPanel.Visible = true;
        CallPingLocationButton.Visible = true;
        CallAcceptButton.Visible = false;
        CallDeclineButton.Visible = false;
        CallHangUpButton.Visible = false;

        CallJoinVoiceButton.Visible = !state.InGroupVoice;
        CallLeaveVoiceButton.Visible = state.InGroupVoice;

        CallControlsStatusLabel.Text = state.InGroupVoice
            ? "[color=#51f542]● GROUP VOICE: ACTIVE[/color]"
            : "[color=#444444]○ GROUP VOICE: INACTIVE[/color]";

        // Members
        AddListEntry($"SLOTS: {state.GroupParticipants.Count}/{state.MaxGroupParticipants}", ColorCyberBlue);
        foreach (var p in state.GroupParticipants)
        {
            if (p.IsAlive)
                AddListEntry($"● {p.Name}", ColorNeonGreen);
            else
                AddListEntry($"☠ {p.Name} [FLATLINE]", ColorAlertRed);
        }

        // Add a leave button to the list
        var leaveBtn = new Button { Text = "[LEAVE BRIDGE]", Modulate = ColorAlertRed, Margin = new Thickness(0, 8, 0, 0) };
        leaveBtn.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.LeaveGroup, null, null);
        ListContainer.AddChild(leaveBtn);

        // Messages
        foreach (var msg in state.GroupMessages)
        {
            var escapedMsg = Robust.Shared.Utility.FormattedMessage.EscapeText(msg.Content);
            var escapedName = Robust.Shared.Utility.FormattedMessage.EscapeText(msg.SenderName);
            var color = msg.IsSystem ? "#f54242" : "#e3f542";
            AddMessage($"[color={color}]\\[{msg.Timestamp:hh\\:mm}\\] {escapedName}:[/color] {escapedMsg}");
        }
    }

    private void RenderNetworkStatus(CitiNetUiState state)
    {
        ListTitleLabel.Text = "[ NETWORK STATUS ]";
        ListSubtitleLabel.Text = "DIAGNOSTICS:";
        ContentHeaderLabel.Text = "[color=#51f542]● ROOT DIAGNOSTICS[/color]";

        AddListEntry("INFRASTRUCTURE:", ColorCyberBlue);
        AddListEntry(state.HasRelay ? "● CITINET RELAY: OK" : "○ CITINET RELAY: ERR", state.HasRelay ? ColorNeonGreen : ColorAlertRed);

        AddListEntry("", Color.Transparent);
        AddListEntry("CURRENT SESSION:", ColorCyberBlue);
        AddListEntry($"● AGENT ID: {state.OwnNumber}", ColorNeonGreen);

        AddMessage($"[color=#42e3f5]>> SYS-OP:[/color] Welcome to CitiNet v4.5 Local Node.");
        if (!state.HasRelay)
            AddMessage($"[color=#f54242]>> FATAL:[/color] Missing connection to telecom relay. Voice and Text services are paused.");
    }

    private void AddListEntry(string text, Color color)
    {
        ListContainer.AddChild(new Label
        {
            Text = text,
            FontColorOverride = color,
            Margin = new Thickness(0, 0, 0, 2)
        });
    }

    private void AddMessage(string markupText)
    {
        var rt = new RichTextLabel();
        rt.SetMessage(Robust.Shared.Utility.FormattedMessage.FromMarkupOrThrow(markupText));
        ContentMessagesContainer.AddChild(rt);
    }

    // ======================== NC LIVE ========================

    // private CitiNetLiveUiState? _lastLiveState; // Removed as per instruction

    // private void RenderLive(CitiNetUiState state) // Removed as per instruction
    // {
    //     _lastLiveState = state.LiveState;
    //     var live = state.LiveState;

    //     ListTitleLabel.Text = "[ CITINET LIVE ]";
    //     ListSubtitleLabel.Text = "ACTIVE STREAMS:";
    //     ContentHeaderLabel.Text = live.IsStreaming
    //         ? "[color=#f54242]● ON AIR[/color]"
    //         : "[color=#444444]○ OFFLINE[/color]";

    //     // --- СПИСОК СТРИМОВ (средняя панель) ---
    //     if (live.ActiveStreams.Count == 0)
    //     {
    //         AddListEntry("[ NO ACTIVE STREAMS ]", ColorDarkGrey);
    //     }
    //     else
    //     {
    //         foreach (var stream in live.ActiveStreams)
    //         {
    //             var isWatched = live.WatchedCamNetEntity.HasValue
    //                             && live.WatchedCamNetEntity.Value == stream.CamNetEntity;
    //             var color = isWatched ? Color.FromHex("#f54242") : ColorCyberBlue;
    //             var prefix = isWatched ? "▶" : " ";
    //             var escapedTitle = Robust.Shared.Utility.FormattedMessage.EscapeText(stream.Title);
    //             var escapedName = Robust.Shared.Utility.FormattedMessage.EscapeText(stream.StreamerName);

    //             var btn = new Button
    //             {
    //                 Text = $"{prefix} {escapedTitle} | {escapedName} ({stream.ViewerCount}👁)",
    //                 Modulate = color,
    //                 Margin = new Thickness(0, 0, 0, 2)
    //             };

    //             var capturedStream = stream;
    //             btn.OnPressed += _ =>
    //             {
    //                 if (isWatched)
    //                     OnSendLiveMessage?.Invoke(CitiNetLiveMessageType.StopWatching, null);
    //                 else
    //                     OnSendLiveMessage?.Invoke(CitiNetLiveMessageType.WatchStream, capturedStream.CamNetEntity.ToString());
    //             };

    //             ListContainer.AddChild(btn);
    //         }
    //     }

    //     // --- ПРАВАЯ ПАНЕЛЬ: СТРИМЕР ---
    //     if (live.HasCamera)
    //     {
    //         ActionControlsPanel.Visible = true;
    //         ActionInput.PlaceHolder = "STREAM TITLE...";
    //         ActionInput.Visible = true;
    //         ActionButton.Text = live.IsStreaming ? "[STOP STREAM]" : "[GO LIVE]";

    //         // Переопределяем кнопку через событие
    //         ActionButton.OnPressed -= _liveStreamActionHandler;
    //         _liveStreamActionHandler = (BaseButton.ButtonEventArgs _) =>
    //         {
    //             if (live.IsStreaming)
    //             {
    //                 OnSendLiveMessage?.Invoke(CitiNetLiveMessageType.StopStream, null);
    //             }
    //             else
    //             {
    //                 var title = ActionInput.Text.Trim();
    //                 OnSendLiveMessage?.Invoke(CitiNetLiveMessageType.StartStream, string.IsNullOrWhiteSpace(title) ? "live" : title);
    //                 ActionInput.Text = string.Empty;
    //             }
    //         };
    //         ActionButton.OnPressed += _liveStreamActionHandler;

    //         if (live.IsStreaming)
    //         {
    //             AddMessage($"[color=#f54242]● STREAMING: {Robust.Shared.Utility.FormattedMessage.EscapeText(live.StreamTitle)}[/color]");
    //             AddMessage($"[color=#51f542]● VIEWERS: {live.ViewerCount}[/color]");
    //         }
    //     }
    //     else
    //     {
    //         AddMessage("[color=#f54242]>> NO CAMERA DETECTED.[/color]");
    //         AddMessage("[color=#444444]>> Equip or hold a StreamCam to go live.[/color]");
    //     }

    //     // --- ПРОСМОТР ---
    //     if (live.WatchedCamNetEntity.HasValue)
    //     {
    //         var entMan = IoCManager.Resolve<IEntityManager>();
    //         var activeCam = entMan.GetEntity(live.WatchedCamNetEntity.Value);

    //         if (entMan.TrySystem<Content.Client.Eye.EyeLerpingSystem>(out var eyeSystem))
    //         {
    //             if (_currentCamera == null)
    //             {
    //                 eyeSystem.AddEye(activeCam);
    //                 _currentCamera = activeCam;
    //             }
    //             else if (_currentCamera != activeCam)
    //             {
    //                 eyeSystem.RemoveEye(_currentCamera.Value);
    //                 eyeSystem.AddEye(activeCam);
    //                 _currentCamera = activeCam;
    //             }
    //         }

    //         if (entMan.TryGetComponent<EyeComponent>(activeCam, out var componentEye))
    //         {
    //             SetCameraView(componentEye.Eye);
    //         }

    //         var escapedWatcher = Robust.Shared.Utility.FormattedMessage.EscapeText(live.WatchedStreamerName);
    //         AddMessage($"[color=#42e3f5]>> WATCHING: {escapedWatcher}[/color]");
    //         AddMessage($"[color=#42e3f5]>> Balance: {live.Balance}$[/color]");

    //         CameraViewBox.Visible = true;

    //         // Донат
    //         DonatePanel.Visible = true;
    //         DonateSubmitBtn.OnPressed -= _liveStreamDonateHandler;
    //         _liveStreamDonateHandler = (BaseButton.ButtonEventArgs _) =>
    //         {
    //             var amount = DonateAmountInput.Text.Trim();
    //             var msgText = DonateMessageInput.Text.Trim();
    //             if (string.IsNullOrEmpty(amount) || !int.TryParse(amount, out var amountInt)) return;

    //             var finalMsg = string.IsNullOrEmpty(msgText) ? " " : msgText;
    //             OnSendLiveMessage?.Invoke(CitiNetLiveMessageType.SendDonate, $"{amountInt}|{finalMsg}");

    //             DonateAmountInput.Text = string.Empty;
    //             DonateMessageInput.Text = string.Empty;
    //         };
    //         DonateSubmitBtn.OnPressed += _liveStreamDonateHandler;
    //     }
    //     else
    //     {
    //         if (_currentCamera != null)
    //         {
    //             if (IoCManager.Resolve<IEntityManager>().TrySystem<Content.Client.Eye.EyeLerpingSystem>(out var eyeSystem))
    //                 eyeSystem.RemoveEye(_currentCamera.Value);
    //             _currentCamera = null;
    //         }
    //         SetCameraView(null);
    //     }

    //     // --- ЧАТ СТРИМА ---
    //     if (live.ChatMessages.Count > 0)
    //     {
    //         ContentMessagesContainer.AddChild(new Label
    //         {
    //             Text = "── LIVE CHAT ──",
    //             FontColorOverride = ColorDimGreen,
    //             Margin = new Thickness(0, 8, 0, 4)
    //         });

    //         foreach (var msg in live.ChatMessages)
    //         {
    //             var escapedMsg = Robust.Shared.Utility.FormattedMessage.EscapeText(msg.Text);
    //             var escapedSender = Robust.Shared.Utility.FormattedMessage.EscapeText(msg.Sender);
    //             var color = msg.IsSystem ? "#f54242" : "#42e3f5";
    //             AddMessage($"[color={color}]({msg.Time:hh\\:mm}) {escapedSender}:[/color] {escapedMsg}");
    //         }
    //     }

    //     // Показываем поле ввода чата если зритель смотрит стрим или стример ведёт трансляцию
    //     if (live.WatchedCamNetEntity.HasValue || live.IsStreaming)
    //     {
    //         ChatInputPanel.Visible = true;
    //     }
    // }

    // Хранилище для хэндлера события кнопки Live (чтобы правильно отписаться)
    // private Action<BaseButton.ButtonEventArgs>? _liveStreamActionHandler; // Removed as per instruction
    // private Action<BaseButton.ButtonEventArgs>? _liveStreamDonateHandler; // Removed as per instruction

    // public void SetCameraView(IEye? eye) // Removed as per instruction
    // {
    //     if (eye != null)
    //     {
    //         CameraView.Eye = eye;
    //         CameraView.Visible = true;
    //         CameraViewBackground.Visible = false;
    //     }
    //     else
    //     {
    //         CameraView.Eye = _defaultEye;
    //         CameraView.Visible = false;
    //         CameraViewBackground.Visible = true;
    //     }
    // }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing && _currentCamera != null)
        {
            if (IoCManager.Resolve<IEntityManager>().TrySystem<Content.Client.Eye.EyeLerpingSystem>(out var eyeSystem))
            {
                eyeSystem.RemoveEye(_currentCamera.Value);
            }
            _currentCamera = null;
        }
    }
}

