- type: job
  id: TraumaTeamChief
  name: Руководитель отдела Trauma Team
  description: job-description-traumateam-chief
  playTimeTracker: JobTraumaTeamChief
  weight: 10
  startingGear: TraumaTeamChiefGear
  supervisors: job-supervisors-centcom
  access:
    - Trauma_Command
    - Trauma_Medical
    - Trauma_Morgue
    - Trauma_Hangar
    - NC_General

- type: startingGear
  id: TraumaTeamChiefGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackSatchelMedical
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHatBeretMedical
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetMedical
    id: CMOPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatCMO
