- type: job
  id: TraumaTeamChemist
  name: Химик TraumaTeam
  description: job-description-traumateam-chemist
  playTimeTracker: JobTraumaTeamChemist
  startingGear: TraumaTeamChemistGear
  access:
    - Medical
    - Chemistry

- type: startingGear
  id: TraumaTeamChemistGear
  equipment:
    id: HoPPDA
    jumpsuit: ClothingUniformJumpsuitChemistry
    outerClothing: ClothingOuterCoatLabChemOpened
    ears: ClothingHeadsetMedical
    belt: ChemBagFilled
    back: ClothingBackpackSatchelChemistry
    shoes: ClothingShoesColorWhite