- type: job
  id: TraumaTeamChemist
  name: Химик Trauma Team
  description: job-description-traumateam-chemist
  playTimeTracker: JobTraumaTeamChemist
  weight: 15
  startingGear: TraumaTeamChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-traumateam-chief
  access:
    - Medical
    - Chemistry

- type: startingGear
  id: TraumaTeamChemistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChemistry
    back: ClothingBackpackChemistry
    shoes: ClothingShoesColorWhite
    ears: ClothingHeadsetMedical
    id: ChemistryPDA
    outerClothing: ClothingOuterCoatLabChemical
