- type: job
  id: TraumaTeamDoctor
  name: Врач Trauma Team
  description: job-description-traumateam-doctor
  playTimeTracker: JobTraumaTeamDoctor
  weight: 20
  startingGear: TraumaTeamDoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-traumateam-chief
  access:
    - Medical
    - Maintenance # Trauma team often operates in field? Maybe restricted to Medbay for logic, but verified with user prompt context implies field work. Let's keep Medbay focused but standard doctor access.

- type: startingGear
  id: TraumaTeamDoctorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorWhite
    ears: ClothingHeadsetMedical
    id: MedicalPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLab
