- type: job
  id: TraumaTeamDoctor
  name: Врач Trauma Team
  description: job-description-traumateam-doctor
  playTimeTracker: JobTraumaTeamDoctor
  weight: 20
  startingGear: TraumaTeamDoctorGear
  supervisors: job-supervisors-traumateam-chief
  access:
    - Trauma_Medical
    - Trauma_Morgue
    - NC_General

- type: startingGear
  id: TraumaTeamDoctorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorWhite
    ears: ClothingHeadsetMedical
    id: MedicalPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLab
