- type: job
  id: TraumaTeamOperative
  name: Оперативник Trauma Team
  description: 'Ангел-хранитель с пулеметом и скверным характером. Вы не лечите, вы устраняете препятствия между врачом и телом. Если кто-то мешает спасению — превратите его в статистику. Ваше кредо: "Клиент должен жить, остальные — не обязательно"'
  playTimeTracker: JobTraumaTeamOperative
  weight: 15
  salary: 900
  startingGear: TraumaTeamOperativeGear
  supervisors: Главный врач Trauma Team, Парамедик Trauma Team
  access:
    - Trauma_Medical
    - Trauma_Hangar
    - Trauma_Morgue
    - NC_General

- type: startingGear
  id: TraumaTeamOperativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecBlue
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombat
    ears: ClothingHeadsetAltSecurity
    id: TraumaTeamOperativePDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterHardsuitTraumaTeamOperative
