- type: job
  id: TraumaTeamParamedic
  name: Парамедик Trauma Team
  description: Элитный мясник на зарплате. Ваша задача — заставить сердце клиента биться, даже если оно решило уйти на покой. Плевать на этику: залейте пациента стимуляторами и латайте дыры. Пока горит статус "Платина", смерть — лишь техническое неудобство
  playTimeTracker: JobTraumaTeamParamedic
  weight: 20
  salary: 850
  startingGear: TraumaTeamParamedicGear
  supervisors: Главный врач Trauma Team
  access:
    - Trauma_Medical
    - Trauma_Morgue
    - Trauma_Hangar
    - NC_General

- type: startingGear
  id: TraumaTeamParamedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitParamedic
    back: ClothingBackpackSatchelMedical
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHelmetHardsuitTraumaTeamMedic
    ears: ClothingHeadsetMedical
    id: TraumaTeamParamedicPDA
    belt: ClothingBeltMedicalEMTFilled
    outerClothing: ClothingOuterHardsuitTraumaTeamMedic
