- type: job
  id: TraumaTeamTech
  name: Техник Trauma Team
  description: Вы — тот, кто заставляет это ведро с гайками лететь, когда в него всадили очередь из турели. Пока врачи латают клиента, вы латаете "AV", используя смекалку и гаечный ключ. Помните: если двигатель заглохнет в Пустоши, медицинская страховка вам уже не понадобится
  playTimeTracker: JobTraumaTeamTech
  weight: 20
  salary: 450
  startingGear: TraumaTeamTechGear
  supervisors: Главный врач Trauma Team
  access:
    - Trauma_Medical
    - Trauma_Morgue
    - NC_General

- type: startingGear
  id: TraumaTeamTechGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitJeansBrown
    back: ClothingBackpackDuffel
    shoes: ClothingShoesColorWhite
    ears: ClothingHeadsetMedical
    id: MedicalPDA
    belt: ClothingBeltUtilityFilled
