using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._White.UserInterface.Systems.TargetDoll.Controls;

[GenerateTypedNameReferences]
public sealed partial class TargetDollControl : TextureRect
{
    public Texture? TextureHovered;
    public Texture? TextureFocused;

    public float DrawScale = 2;

    public TargetDollControl()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (TextureHovered != null)
            DrawTexture(handle, TextureHovered);

        if (TextureFocused != null)
            DrawTexture(handle, TextureFocused);
    }

    public void DrawTexture(DrawingHandleScreen handle, Texture tex, Color? color = null)
    {
        var texSize = new Vector2(tex.Width * DrawScale * UIScale, tex.Height * DrawScale * UIScale);
        var offset = Vector2.Zero;

        handle.DrawTextureRect(tex, new UIBox2(Vector2.Zero - offset, texSize - offset), color);
    }
}
