using System.Linq;
using Content.Client.Guidebook.Controls;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared._White.Humanoid.Markings.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._White.Humanoid.Markings.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class SingleMarkingPicker : BoxContainer
{
    private const int ColumnWidth = 500;

    private List<ISearchableControl> _searchable = new();

    private readonly HashSet<MarkingPrototype> _markings;
    private readonly MarkingsViewModel _model;
    private readonly ProtoId<MarkingCategoryPrototype> _category;

    public SingleMarkingPicker(HashSet<MarkingPrototype> markings, MarkingsViewModel model, ProtoId<MarkingCategoryPrototype> category)
    {
        RobustXamlLoader.Load(this);

        _markings = markings;
        _model = model;
        _category = category;

        OrderingItems.AddChild(new MarkingOrderer(model, category));

        UpdateMarkings();

        SearchBar.OnTextChanged += _ =>
        {
            foreach (var element in _searchable)
            {
                element.SetHiddenState(true, SearchBar.Text.Trim());
            }
        };

        UpdateStatus();

        ReorderButton.OnPressed += ReorderButtonPressed;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _model.MarkingsReset += UpdateStatus;
        _model.MarkingsChanged += MarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _model.MarkingsReset -= UpdateStatus;
        _model.MarkingsChanged -= MarkingsChanged;
    }

    protected override void Resized()
    {
        base.Resized();

        Items.Columns = (int)(Width / ColumnWidth);
    }

    private void MarkingsChanged(ProtoId<MarkingCategoryPrototype> category)
    {
        if (_category != category)
            return;

        UpdateStatus();
    }

    private void ReorderButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (ReorderButton.Pressed)
        {
            SelectionItems.Visible = false;
            SearchBar.Visible = false;
            OrderingItems.Visible = true;
        }
        else
        {
            SelectionItems.Visible = true;
            SearchBar.Visible = true;
            OrderingItems.Visible = false;
        }
    }

    private void UpdateMarkings()
    {
        foreach (var marking in _markings.OrderBy(marking => Loc.GetString($"marking-{marking.ID}")))
        {
            var item = new MarkingItem(true, marking, _model, _category);
            Items.AddChild(item);
        }
        _searchable = Items.GetSearchableControls();
    }

    private void UpdateStatus()
    {
        _model.GetMarkingStatus(_category, out var isRequired, out var count, out var selected);
        MarkingsStatus.Text = Loc.GetString("markings-limits", ("required", isRequired), ("count", count), ("selectable", count - selected));
    }
}
