- type: job
  id: Librarian
  name: job-name-librarian
  description: job-description-librarian
  playTimeTracker: JobLibrarian
  requirements:
  # WD EDIT START
  # - !type:CharacterDepartmentTimeRequirement
  #   department: Epistemics
  #   min: 14400
  # WD EDIT END
  - !type:CharacterLogicOrRequirement
    requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
      - IPC
    - !type:CharacterTraitRequirement
      traits:
      - AnomalousPositronics
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
  - !type:CharacterItemGroupRequirement
    group: TraitsCasterType
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  - Library
  special:
  - !type:AddComponentSpecial
    components:
    - type: Psionic
      baselinePowerCost: 75
      nextPowerCost: 75
      removable: false
      powerPool: PsychoHistorianPowerPool
    - type: InnatePsionicPowers
      powersToAdd:
      - XenoglossyPower
      - TelepathyPower
      - AssayPower


- type: startingGear
  id: LibrarianGear
  subGear:
  - LibrarianPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLibrarian
    back: ClothingBackpack
    shoes: ClothingShoesBootsLaceup
    # outerClothing: ClothingOuterCoatRnd - WD EDIT
    id: LibrarianPDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
    pocket2: HandLabeler
  storage:
    back:
    - BookRandom

- type: startingGear
  id: LibrarianPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitAncientVoid
    head: ClothingHeadEnvirohelmAncientVoid
    gloves: ClothingHandsGlovesEnviroglovesPrototype
