using System.Numerics;
using Content.Client.Computer;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Client.Weapons.Ranged.Systems;
using Content.Shared._White.Guns.ModularTurret;
using Content.Shared._White.RemoteControl.BUIStates;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Weapons.Ranged.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Graphics;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;

namespace Content.Client._White.RemoteControl.UI;

// consider this a hate crime aimed at the developers of robust toolbox
public sealed partial class RemoteControlConsoleWindow
{
    private static int[][] _cursorArr = {
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,7,9,7,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,7,9,7,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,9,9,9,8,8,7,7,6,6,5,5,3,5,5,6,6,7,7,8,8,9,9,9,0,0,0,0,0],
        [0,0,0,0,0,9,5,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,5,9,0,0,0,0,0],
        [0,0,0,0,0,9,2,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2,9,0,0,0,0,0],
        [0,0,0,0,0,8,1,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,1,8,0,0,0,0,0],
        [0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,0],
        [0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0],
        [0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0],
        [0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0],
        [0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0],
        [3,0,3,0,0,5,0,0,0,0,0,0,0,0,0,2,8,2,0,0,0,0,0,0,0,0,0,5,0,0,3,0,3],
        [7,0,7,0,0,5,0,0,0,0,0,0,0,0,2,5,9,5,2,0,0,0,0,0,0,0,0,5,0,0,7,0,7],
        [9,0,9,0,0,3,0,1,2,3,4,5,6,7,8,9,9,9,8,7,6,5,4,3,2,1,0,3,0,0,9,0,9],
        [7,0,7,0,0,5,0,0,0,0,0,0,0,0,2,5,9,5,2,0,0,0,0,0,0,0,0,5,0,0,7,0,7],
        [3,0,3,0,0,5,0,0,0,0,0,0,0,0,0,2,8,2,0,0,0,0,0,0,0,0,0,5,0,0,3,0,3],
        [0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0],
        [0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0],
        [0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0],
        [0,0,0,0,0,7,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0],
        [0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,0],
        [0,0,0,0,0,8,1,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,1,8,0,0,0,0,0],
        [0,0,0,0,0,9,2,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2,9,0,0,0,0,0],
        [0,0,0,0,0,9,5,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,5,9,0,0,0,0,0],
        [0,0,0,0,0,9,9,9,8,8,7,7,6,6,5,5,3,5,5,6,6,7,7,8,8,9,9,9,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,7,9,7,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,7,9,7,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    };


    private void BuildCursor()
    {
#if !DEBUG
        if (_aimingCursor is not null && _firingCursor is not null)
            return;
#endif

        var cursorImage = new SixLabors.ImageSharp.Image<Rgba32>(33, 33);
        for (int row = 5; row <= 27; row++)
        {
            for (int column = 5; column <= 27; column++)
            {
                cursorImage[column, row] = new(0, 1.0f, 0, _cursorArr[row][column] / 9.0f);
            }
        }
        _aimingCursor = _clyde.CreateCursor(cursorImage, new(16, 16));

        var cursorFiringImage = new SixLabors.ImageSharp.Image<Rgba32>(33, 33);
        for (int row = 0; row <= 32; row++)
        {
            for (int column = 0; column <= 32; column++)
            {
                // i'm not going to bother implementing proper blending for this, i just want a fancy cursor ffs
                if (5 <= column && column <= 27 && 5 <= row && row <= 27)
                    cursorFiringImage[column, row] = new(0, 1, 0, _cursorArr[row][column] / 9.0f);
                else
                    cursorFiringImage[column, row] = new(1, 0, 0, _cursorArr[row][column] / 9.0f);
            }
        }

        _firingCursor = _clyde.CreateCursor(cursorFiringImage, new(16, 16));
    }
}