using Content.Shared._NC.Forensics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using System;

namespace Content.Client._NC.Forensics;

[GenerateTypedNameReferences]
public sealed partial class BallisticAnalyzerWindow : DefaultWindow
{
    public event Action? OnStartAnalyze;

    public BallisticAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);

        AnalyzeButton.OnPressed += _ => OnStartAnalyze?.Invoke();
    }

    public void UpdateState(BallisticAnalyzerBuiState state)
    {
        // Статус пули
        if (state.BulletHash != null)
        {
            BulletStatusLabel.Text = "УСТАНОВЛЕНО";
            BulletStatusLabel.FontColorOverride = Color.LimeGreen;
        }
        else
        {
            BulletStatusLabel.Text = "ОТСУТСТВУЕТ";
            BulletStatusLabel.FontColorOverride = Color.Red;
        }

        // Статус оружия
        if (state.WeaponHash != null)
        {
            WeaponStatusLabel.Text = "УСТАНОВЛЕНО";
            WeaponStatusLabel.FontColorOverride = Color.LimeGreen;
        }
        else
        {
            WeaponStatusLabel.Text = "ОТСУТСТВУЕТ";
            WeaponStatusLabel.FontColorOverride = Color.Red;
        }

        // Кнопка анализа
        AnalyzeButton.Disabled = state.IsAnalyzing || state.BulletHash == null || state.WeaponHash == null;

        // Состояние анализа
        if (state.IsAnalyzing)
        {
            StatusLabel.Text = "ИДЕТ СКАНИРОВАНИЕ...";
            StatusLabel.FontColorOverride = Color.Yellow;
            ResultBox.Visible = false;
        }
        else
        {
            StatusLabel.Text = "Система готова";
            StatusLabel.FontColorOverride = Color.Gray;

            if (state.Result != BallisticMatchResult.None)
            {
                ResultBox.Visible = true;
                if (state.Result == BallisticMatchResult.Match)
                {
                    MatchLabel.Text = "СОВПАДЕНИЕ 100%";
                    MatchLabel.FontColorOverride = Color.LimeGreen;
                }
                else
                {
                    MatchLabel.Text = "СОВПАДЕНИЕ 0%";
                    MatchLabel.FontColorOverride = Color.Red;
                }
            }
            else
            {
                ResultBox.Visible = false;
            }
        }
    }
}
