using System.Text;
using Content.Shared._NC.Decryption.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.Decryption.UI;

[GenerateTypedNameReferences]
public sealed partial class DecryptionWindow : DefaultWindow
{
    private const string StatusSessionActive = "Session active";
    private const string StatusCarrierLoaded = "Carrier loaded";
    private const string StatusNoCarrier = "No carrier";

    private const string AttemptSlotFilled = "[#]";
    private const string AttemptSlotEmpty = "[ ]";

    // Larger matrix footprint so the grid occupies most of the left panel.
    private const int CellSize = 26;
    private const int CellSpacing = 1;
    private const int RightPanelMinWidth = 280;
    private const int RightPanelMaxWidth = 300;
    private const int RightPanelMaxHeight = 10000;

    public event Action? OnStart;
    public event Action? OnEject;
    public event Action<int>? OnMatrixClick;

    private readonly Label _protocolLabel;
    private readonly Label _tierLabel;
    private readonly Label _timerLabel;
    private readonly Label _integrityLabel;
    private readonly Label _attemptsLabel;
    private readonly RichTextLabel _logText;
    private readonly BoxContainer _matrixRows;
    private readonly PanelContainer _rightPanel;
    private readonly Button _startButton;
    private readonly Button _ejectButton;
    private readonly Label _statusLabel;

    public DecryptionWindow()
    {
        RobustXamlLoader.Load(this);

        _protocolLabel = FindControl<Label>("ProtocolLabel");
        _tierLabel = FindControl<Label>("TierLabel");
        _timerLabel = FindControl<Label>("TimerLabel");
        _integrityLabel = FindControl<Label>("IntegrityLabel");
        _attemptsLabel = FindControl<Label>("AttemptsLabel");
        _logText = FindControl<RichTextLabel>("LogText");
        _matrixRows = FindControl<BoxContainer>("MatrixRows");
        _rightPanel = FindControl<PanelContainer>("RightPanel");
        _startButton = FindControl<Button>("StartButton");
        _ejectButton = FindControl<Button>("EjectButton");
        _statusLabel = FindControl<Label>("StatusLabel");

        _rightPanel.MinSize = new System.Numerics.Vector2(RightPanelMinWidth, 1);
        _rightPanel.MaxSize = new System.Numerics.Vector2(RightPanelMaxWidth, RightPanelMaxHeight);

        _startButton.OnPressed += _ => OnStart?.Invoke();
        _ejectButton.OnPressed += _ => OnEject?.Invoke();
    }

    public void UpdateState(DecryptionBoundUiState state)
    {
        _protocolLabel.Text = state.ProtocolTitle;
        _tierLabel.Text = state.TierLabel;
        _timerLabel.Text = state.TimeRemainingSeconds >= 0 ? $"{state.TimeRemainingSeconds}s" : "--";
        _integrityLabel.Text = $"{state.Integrity}%";
        _attemptsLabel.Text = BuildAttemptsLabel(state.AttemptsRemaining, state.MaxAttempts);

        _statusLabel.Text = state.HasCarrier
            ? (state.SessionActive ? StatusSessionActive : StatusCarrierLoaded)
            : StatusNoCarrier;

        _startButton.Disabled = !state.HasCarrier;
        _ejectButton.Disabled = !state.HasCarrier;

        var logBuilder = new StringBuilder();
        foreach (var line in state.LogLines)
            logBuilder.AppendLine(line);

        _logText.SetMessage(logBuilder.ToString());
        BuildMatrix(state);
    }

    private void BuildMatrix(DecryptionBoundUiState state)
    {
        _matrixRows.RemoveAllChildren();

        if (!state.SessionActive || state.MatrixCells.Count == 0)
            return;

        var width = Math.Max(1, state.MatrixWidth);
        var height = Math.Max(1, state.MatrixHeight);

        for (var row = 0; row < height; row++)
        {
            var rowBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = CellSpacing,
                RectClipContent = true,
            };

            var col = 0;
            while (col < width)
            {
                var index = (row * width) + col;

                if (TryCreateBackdoorTokenButton(state, row, col, width, out var backdoorButton, out var backdoorLength))
                {
                    rowBox.AddChild(backdoorButton);
                    col += backdoorLength;
                    continue;
                }

                if (TryCreateWordTokenButton(state, row, col, width, out var wordButton, out var wordLength))
                {
                    rowBox.AddChild(wordButton);
                    col += wordLength;
                    continue;
                }

                var glyph = index < state.MatrixCells.Count ? state.MatrixCells[index].Glyph : ' ';
                rowBox.AddChild(CreateTokenButton(glyph.ToString(), index, 1, state.SessionActive));
                col++;
            }

            var rowWidth = (width * CellSize) + ((width - 1) * CellSpacing);
            rowBox.MinSize = new System.Numerics.Vector2(rowWidth, CellSize);
            rowBox.MaxSize = new System.Numerics.Vector2(rowWidth, CellSize);

            _matrixRows.AddChild(rowBox);
        }
    }

    private bool TryCreateBackdoorTokenButton(
        DecryptionBoundUiState state,
        int row,
        int col,
        int width,
        out Button button,
        out int length)
    {
        button = default!;
        length = 0;

        var index = (row * width) + col;
        if (index >= state.MatrixCells.Count)
            return false;

        var cell = state.MatrixCells[index];
        if (cell.BackdoorId < 0)
            return false;

        var isStart = col == 0 || state.MatrixCells[index - 1].BackdoorId != cell.BackdoorId;
        if (!isStart)
            return false;

        var tokenBuilder = new StringBuilder();
        var cursor = col;
        while (cursor < width)
        {
            var cursorIndex = (row * width) + cursor;
            if (cursorIndex >= state.MatrixCells.Count)
                break;

            var cursorCell = state.MatrixCells[cursorIndex];
            if (cursorCell.BackdoorId != cell.BackdoorId)
                break;

            tokenBuilder.Append(cursorCell.Glyph);
            cursor++;
        }

        var token = tokenBuilder.ToString();
        if (token.Length <= 0)
            return false;

        button = CreateTokenButton(token, index, token.Length, state.SessionActive);
        length = token.Length;
        return true;
    }

    private bool TryCreateWordTokenButton(
        DecryptionBoundUiState state,
        int row,
        int col,
        int width,
        out Button button,
        out int length)
    {
        button = default!;
        length = 0;

        var index = (row * width) + col;
        if (index >= state.MatrixCells.Count)
            return false;

        var cell = state.MatrixCells[index];
        if (cell.BackdoorId >= 0 || string.IsNullOrEmpty(cell.Word))
            return false;

        var isStart = col == 0 || state.MatrixCells[index - 1].Word != cell.Word || state.MatrixCells[index - 1].BackdoorId >= 0;
        if (!isStart)
            return false;

        var token = cell.Word;
        var safeLength = Math.Min(token.Length, Math.Max(0, width - col));
        if (safeLength <= 0)
            return false;

        button = CreateTokenButton(token[..safeLength], index, safeLength, state.SessionActive);
        length = safeLength;
        return true;
    }

    private Button CreateTokenButton(string text, int index, int glyphCount, bool isSessionActive)
    {
        var widthPx = (glyphCount * CellSize) + ((glyphCount - 1) * CellSpacing);
        var button = new Button
        {
            Text = text,
            MinSize = new System.Numerics.Vector2(widthPx, CellSize),
            MaxSize = new System.Numerics.Vector2(widthPx, CellSize),
            Disabled = !isSessionActive
        };

        button.OnPressed += _ => OnMatrixClick?.Invoke(index);
        return button;
    }

    private static string BuildAttemptsLabel(int remaining, int max)
    {
        var builder = new StringBuilder();
        for (var i = 0; i < max; i++)
        {
            builder.Append(i < remaining ? AttemptSlotFilled : AttemptSlotEmpty);
            if (i + 1 < max)
                builder.Append(' ');
        }

        return builder.ToString();
    }
}
