# Tabs

- type: quickPhrase
  id: BaseCommonPhrase
  tab: aac-tab-common-phrases # WWDP EDIT (loc)
  abstract: true

- type: quickPhrase
  id: BaseJobPhrase
  tab: aac-tab-jobs # WWDP EDIT (loc)
  abstract: true

- type: quickPhrase
  id: BaseLocationPhrase
  tab: aac-tab-locations # WWDP EDIT (loc)
  abstract: true

- type: quickPhrase
  id: BaseSubjectPhrase
  tab: aac-tab-subjects # WWDP EDIT (loc)
  abstract: true

- type: quickPhrase
  id: BaseThreatPhrase
  tab: aac-tab-safety # WWDP EDIT (loc)
  abstract: true

- type: quickPhrase
  id: BaseSpeciesPhrase
  tab: aac-tab-species # WWDP EDIT (loc)
  abstract: true

# Departments

- type: quickPhrase
  id: BaseCivilianPhrase
  group: aac-group-civilian # WWDP EDIT (loc)
  abstract: true

- type: quickPhrase
  id: BaseCommandPhrase
  group: aac-group-command # WWDP EDIT (loc)
  styleClass: CommandButton
  abstract: true

- type: quickPhrase
  id: BaseEngineeringPhrase
  group: aac-group-engineering # WWDP EDIT (loc)
  styleClass: EngineeringButton
  abstract: true

- type: quickPhrase
  id: BaseEpistemicsPhrase
  group: aac-group-epistemics # WWDP EDIT (loc)
  styleClass: EpistemicsButton
  abstract: true

- type: quickPhrase
  id: BaseJusticePhrase
  group: aac-group-justice # WWDP EDIT (loc)
  styleClass: JusticeButton
  abstract: true

- type: quickPhrase
  id: BaseLogisticsPhrase
  group: aac-group-logistics # WWDP EDIT (loc)
  styleClass: LogisticsButton
  abstract: true

- type: quickPhrase
  id: BaseMedicalPhrase
  group: aac-group-medical # WWDP EDIT (loc)
  styleClass: MedicalButton
  abstract: true

- type: quickPhrase
  id: BaseSecurityPhrase
  group: aac-group-security # WWDP EDIT (loc)
  styleClass: SecurityButton
  abstract: true

- type: quickPhrase
  id: BaseServicePhrase
  group: aac-group-service # WWDP EDIT (loc)
  styleClass: ServiceButton
  abstract: true
