- type: job
  id: PrisonGuard
  name: job-name-guard
  description: job-description-guard
  playTimeTracker: JobPrisonGuard
  startingGear: PrisonGuardGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "JobIconPrisonGuard"
  supervisors: job-supervisors-warden
  setPreference: false # WWDP disabled role, not mapped
#  whitelistRequired: true
  access:
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh
  requirements:
    - !type:CharacterEmployerRequirement
      employers:
      - ZavodskoiInterstellar
      - PMCG
      - NanoTrasen
    # WD EDIT START
    - !type:CharacterOverallTimeRequirement
      min: 3600
    # WD EDIT END

- type: startingGear
  id: PrisonGuardGear
  subGear:
  - PrisonGuardPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisonGuard
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack # WD EDIT: ClothingShoesBootsCombatFilled -> ClothingShoesBootsJack
    # eyes: ClothingEyesGlassesSecurity - WD EDIT
    head: ClothingHeadPrisonGuard
    id: PrisonGuardPDA
    ears: ClothingHeadsetPrisonGuard #DeltaV
    # belt: ClothingBeltSecurityFilled - WD EDIT
  storage:
    back:
    - WeaponEnergyGunPistolSecurity

- type: startingGear
  id: PrisonGuardPlasmamanGear
  parent: BasePlasmamanSecurityGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitPrisonGuard
    head: ClothingHeadEnvirohelmPrisonGuard
    gloves: ClothingHandsGlovesEnviroglovesBlack
