- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  requirements:
  # WD EDIT START
  # - !type:CharacterDepartmentTimeRequirement
  #   department: Epistemics
  #   min: 14400 #4 hrs
  # WD EDIT END
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
    - ZengHuPharmaceuticals
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ScientistGear
  subGear:
  - ScientistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScience
    shoes: ClothingShoesColorWhite
    # outerClothing: ClothingOuterCoatRnd - WD EDIT
    id: SciencePDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook

- type: startingGear
  id: ScientistPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitScientist
    head: ClothingHeadEnvirohelmScientist
    gloves: ClothingHandsGlovesEnviroglovesWhite
