- type: job
  id: SeniorResearcher
  name: job-name-senior-researcher
  description: job-description-senior-researcher
  playTimeTracker: JobSeniorResearcher
  setPreference: false # WWDP disabled role, not mapped
  requirements:
    # WD EDIT START
    # - !type:CharacterDepartmentTimeRequirement
    #   department: Epistemics
    #   min: 216000 #60 hrs
    # WD EDIT END
    - !type:CharacterEmployerRequirement
      employers:
      - NanoTrasen
      - ZengHuPharmaceuticals
  startingGear: SeniorResearcherGear
  icon: "JobIconSeniorResearcher"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: SeniorResearcherGear
  subGear:
  - ScientistPlasmamanGear
  equipment:
    head: ClothingHeadHatBeretRND
    jumpsuit: ClothingUniformJumpsuitSeniorResearcher
    back: ClothingBackpackScience
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLabSeniorResearcher
    id: SeniorResearcherPDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
