- type: loadout
  id: LoadoutCommandHoSBat
  category: JobsSecurityHeadOfSecurity
  cost: 0
  canBeHeirloom: true
  requirements:
  - !type:CharacterItemGroupRequirement
    group: LoadoutHeadOfSecurityWeapon
  - !type:CharacterJobRequirement
    jobs:
    - HeadOfSecurity
  items:
  - AssballBat
