# Hobo
- type: loadout
  id: LoadoutOverCoatHobo
  category: JobsAUncategorized
  cost: 3
  exclusive: true
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterJobRequirement
    jobs:
    - Hobo
  items:
  - ClothingOuterOverCoatHobo

- type: loadout
  id: LoadoutHeadHatHoboCap
  category: JobsAUncategorized
  cost: 3
  exclusive: true
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterJobRequirement
    jobs:
    - Hobo
  items:
  - ClothingHeadHatHoboCap

- type: loadout
  id: LoadoutHeadHatHoboHat
  category: JobsAUncategorized
  cost: 3
  exclusive: true
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterJobRequirement
    jobs:
    - Hobo
  items:
  - ClothingHeadHatHoboHat

- type: loadout
  id: LoadoutHeadHatWatermelon
  category: JobsAUncategorized
  cost: 3
  exclusive: true
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterJobRequirement
    jobs:
    - Hobo
  items:
  - ClothingHeadHatWatermelon
