- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  setPreference: false # WWDP disabled role, not mapped
  requirements:
    # WD EDIT START
    # - !type:CharacterDepartmentTimeRequirement
    #   department: Medical
    #   min: 21600 # 6 hrs
    # - !type:CharacterDepartmentTimeRequirement
    #   department: Security
    #   min: 18000 # 4 hrs
    # WD EDIT END
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - BrittleBoneDisease
    - !type:CharacterEmployerRequirement
      employers:
      - ZavodskoiInterstellar
      - Interdyne
      - PMCG
      - NanoTrasen
    # WD EDIT START
    - !type:CharacterOverallTimeRequirement
      min: 3600
    # WD EDIT END
  startingGear: CorpsmanGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  - External
  - Corpsman
  extendedAccess:
  - Chemistry
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining
    - type: SurgerySpeedModifier
      speedModifier: 2.0
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: CorpsmanGear # see Prototypes/Roles/Jobs/Fun/misc_startinggear.yml for "BrigmedicGear"
  subGear:
  - CorpsmanPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    # outerClothing: ClothingOuterArmorPlateCarrier - WD EDIT
    back: ClothingBackpackBrigmedic
    shoes: ClothingShoesBootsJack # WD EDIT: ClothingShoesBootsCombatFilled -> ClothingShoesBootsJack
    # gloves: ClothingHandsGlovesNitrile - WD EDIT
    # eyes: ClothingEyesHudMedical - WD EDIT
    head: ClothingHeadHatBeretCorpsman
    id: CorpsmanPDA
    ears: ClothingHeadsetBrigmedic
    # belt: ClothingBeltCorpsmanWebbingFilled - WD EDIT
  storage:
    back:
    - EmergencyRollerBedSpawnFolded
    - BodyBagFolded
    - Portafib
    - BruteAutoInjector
    - BruteAutoInjector
    - BurnAutoInjector
    - BurnAutoInjector
    - MagazinePistol

- type: startingGear
  id: CorpsmanPlasmamanGear
  parent: BasePlasmamanSecurityGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitBrigmedic
    head: ClothingHeadEnvirohelmBrigmedic
    gloves: ClothingHandsGlovesEnviroglovesBlack
