using System.Linq;
using Content.Client._White.UserInterface.Controls;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Orion.Antag;
using Content.Shared.Ghost;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostTargetWindow : DefaultWindow
    {
/* // Orion-Edit: Removed
        private List<(string, NetEntity)> _warps = new();
*/

        // WWDP EDIT START
        public static readonly Color AntagonistButtonColor = Color.FromHex("#7F4141");

        public static readonly Color LocationButtonColor = StyleNano.ButtonColorDefault;
        // WWDP EDIT END

        private string _searchText = string.Empty;

        // Orion-Start
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        private List<GhostWarpPlayer> _originalPlayerWarps = new();
        private List<GhostWarpPlace> _originalPlaceWarps = new();
        private List<GhostWarpGlobalAntagonist> _originalAntagonists = new();

        private List<GhostWarpPlayer> _playerWarps = new();
        private List<GhostWarpPlace> _placeWarps = new();
        private List<GhostWarpGlobalAntagonist> _globalAntagonists = new();

        private List<GhostWarpPlayer> _alivePlayers = new();
        private List<GhostWarpPlayer> _leftPlayers = new();
        private List<GhostWarpPlayer> _deadPlayers = new();
        private List<GhostWarpPlayer> _ghostPlayers = new();
        // Orion-End

        public event Action<NetEntity>? WarpClicked;
        public event Action? OnGhostnadoClicked;

        public GhostTargetWindow()
        {
            IoCManager.InjectDependencies(this); // Orion
            RobustXamlLoader.Load(this);
            SearchBar.OnTextChanged += OnSearchTextChanged;

            GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
        }

        public void Populate() // Orion-Edit: UpdateWarps > Populate
        {
/* // Orion-Edit: Removed
            // Server COULD send these sorted but how about we just use the client to do it instead
            _warps = warps
                .OrderBy(w => w.IsWarpPoint)
                .ThenBy(w => w.DisplayName, Comparer<string>.Create(
                    (x, y) => string.Compare(x, y, StringComparison.Ordinal)))
                .Select(w =>
                {
                    var name = w.IsWarpPoint
                        ? Loc.GetString("ghost-target-window-current-button", ("name", w.DisplayName))
                        : w.DisplayName;

                    return (name, w.Entity);
                })
                .ToList();
*/
            // Orion-Start
            GhostTeleportContainer.DisposeAllChildren();

            _playerWarps = _originalPlayerWarps;
            _placeWarps = _originalPlaceWarps;
            _globalAntagonists = _originalAntagonists;

            PlayersAllocation();
            AddButtons();
            // Orion-End
        }

        public void UpdateWarps(List<GhostWarpPlayer> players, List<GhostWarpPlace> places, List<GhostWarpGlobalAntagonist> antagonists) // Orion-Edit: Populate > UpdateWarps
        {
/* // Orion-Edit: Removed
            ButtonContainer.DisposeAllChildren();
            AddButtons();
*/
            // Orion-Start
            _originalPlayerWarps = players.ToList();
            _originalPlaceWarps = places.ToList();
            _originalAntagonists = antagonists.ToList();

            _playerWarps = _originalPlayerWarps;
            _placeWarps = _originalPlaceWarps;
            _globalAntagonists = _originalAntagonists;

            Populate();
            // Orion-End
        }

        private void AddButtons()
        {
/* // Orion-Edit: Removed
            foreach (var (name, warpTarget) in _warps)
            {
                var currentButtonRef = new Button
                {
                    Text = name,
                    TextAlign = Label.AlignMode.Right,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    SizeFlagsStretchRatio = 1,
                    MinSize = new Vector2(340, 20),
                    ClipText = true,
                };

                currentButtonRef.OnPressed += _ => WarpClicked?.Invoke(warpTarget);
                currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);

                ButtonContainer.AddChild(currentButtonRef);
            }
*/

            // Orion-Start // WWDP EDIT START
            AddAntagButtons(_globalAntagonists, "ghost-teleport-menu-antagonists-label", AntagonistButtonColor);
            AddPlayerButtons(_alivePlayers, "ghost-teleport-menu-alive-label", Color.Black, true); // Alive
            AddPlayerButtons(_ghostPlayers, "ghost-teleport-menu-ghosts-label", Color.Black, true); // Ghost
            AddPlayerButtons(_leftPlayers, "ghost-teleport-menu-left-label", Color.Black, true); // Left
            AddPlayerButtons(_deadPlayers, "ghost-teleport-menu-dead-label", Color.Black, true); // Dead
            AddPlaceButtons(_placeWarps, "ghost-teleport-menu-locations-label", LocationButtonColor);
            // Orion-End // WWDP EDIT END
        }

/* // Orion-Edit:Part of search bar
        private bool ButtonIsVisible(Button button)
        {
            return string.IsNullOrEmpty(_searchText) || button.Text == null || button.Text.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
        }

        private void UpdateVisibleButtons()
        {
            foreach (var child in ButtonContainer.Children)
            {
                if (child is Button button)
                    button.Visible = ButtonIsVisible(button);
            }
        }
*/

        // Orion-Start
        private void AddPlayerButtons(List<GhostWarpPlayer> players,
            string text,
            Color buttonColor,
            bool enableByDepartmentColorSheet)
        {
            if (players.Count == 0)
                return;

            var mainContainer = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 5
            };

            var header = CreateSectionHeader(text);
            mainContainer.AddChild(header);

            var sortedPlayers = SortPlayersByDepartment(players);

            foreach (var departmentList in sortedPlayers)
            {
                if (departmentList.Count == 0)
                    continue;

                var departmentBox = new FlexBox() // WWDP EDIT
                {
                    AlignContent = FlexBox.FlexAlignContent.SpaceBetween
                };

                var departmentPrototype = _prototypeManager.Index<DepartmentPrototype>(departmentList[0].DepartmentID);
                if (enableByDepartmentColorSheet)
                    buttonColor = departmentPrototype.Color; // WWDP EDIT

                var labelText = departmentPrototype.Name;

                var departmentLabel = new Label
                {
                    Text = Loc.GetString(labelText) + ": " + departmentList.Count,
                    StyleClasses = { "LabelSecondaryColor" }
                };

                foreach (var player in departmentList)
                {
                    var playerButton = new Button
                    {
                        Text = player.Name,
                        TextAlign = Label.AlignMode.Right,
                        HorizontalAlignment = HAlignment.Center,
                        VerticalAlignment = VAlignment.Center,
                        SizeFlagsStretchRatio = 1,
                        ModulateSelfOverride = buttonColor, // WWDP EDIT
                        ToolTip = player.JobName,
                        TooltipDelay = 0.1f,
                        SetWidth = 180,
                        ClipText = true,
                    };

                    playerButton.Label.ModulateSelfOverride = GetTextColor(buttonColor);

                    playerButton.OnPressed += _ => WarpClicked?.Invoke(player.Entity);

                    departmentBox.AddChild(playerButton); // WWDP EDIT
                }

                mainContainer.AddChild(departmentLabel); // WWDP EDIT
                mainContainer.AddChild(departmentBox); // WWDP EDIT
            }

            GhostTeleportContainer.AddChild(mainContainer); // WWDP EDIT
        }

        private void AddPlaceButtons(List<GhostWarpPlace> places, string text, Color buttonColor)
        {
            if (places.Count == 0)
                return;

            var mainContainer = new BoxContainer() // WWDP EDIT
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 5
            };

            var header = CreateSectionHeader(text);
            mainContainer.AddChild(header); // WWDP EDIT

            var placesBox = new FlexBox() // WWDP EDIT
            {
                AlignContent = FlexBox.FlexAlignContent.SpaceBetween
            };

            var countLabel = new Label
            {
                Text = Loc.GetString("ghost-teleport-menu-count-label") + ": " + places.Count,
                StyleClasses = { "LabelSecondaryColor" }
            };

            foreach (var place in places)
            {
                var placeButton = new Button
                {
                    Text = place.Name,
                    TextAlign = Label.AlignMode.Right,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    SizeFlagsStretchRatio = 1,
                    ModulateSelfOverride = buttonColor, // WWDP EDIT
                    ToolTip = place.Description,
                    TooltipDelay = 0.1f,
                    SetWidth = 180,
                    ClipText = true,
                };

                placeButton.Label.ModulateSelfOverride = GetTextColor(buttonColor);

                placeButton.OnPressed += _ => WarpClicked?.Invoke(place.Entity);

                placesBox.AddChild(placeButton); // WWDP EDIT
            }

            mainContainer.AddChild(countLabel); // WWDP EDIT
            mainContainer.AddChild(placesBox); // WWDP EDIT

            GhostTeleportContainer.AddChild(mainContainer); // WWDP EDIT
        }
        // Orion-End

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            // Orion-Edit-Start
            _searchText = args.Text.ToLower();

            GhostTeleportContainer.DisposeAllChildren();

            if (string.IsNullOrEmpty(_searchText))
            {
                _playerWarps = _originalPlayerWarps;
                _placeWarps = _originalPlaceWarps;
                _globalAntagonists = _originalAntagonists;
            }
            else
            {
                _playerWarps = GetSortedPlayers(_originalPlayerWarps).Where(p => p.Name.ToLower().Contains(_searchText)).ToList();
                _placeWarps = GetSortedPlaces(_originalPlaceWarps).Where(p => p.Name.ToLower().Contains(_searchText)).ToList();
                _globalAntagonists = GetSortedAntagonists(_originalAntagonists).Where(a => a.Name.ToLower().Contains(_searchText)).ToList();
            }
            PlayersAllocation();

            AddButtons();
            // Orion-Edit-End
        }

        // Orion-Start
        private void AddAntagButtons(List<GhostWarpGlobalAntagonist> antags, string text, Color buttonColor)
        {
            if (antags.Count == 0)
                return;

            var mainContainer = new BoxContainer() // WWDP EDIT
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 5
            };

            var header = CreateSectionHeader(text);
            mainContainer.AddChild(header); // WWDP EDIT

            var sortedAntags = SortAntagsByWeight(antags);

            foreach (var antagList in sortedAntags)
            {
                if (antagList.Count == 0)
                    continue;

                var departmentBox = new FlexBox() // WWDP EDIT
                {
                    AlignContent = FlexBox.FlexAlignContent.SpaceBetween
                };

                var labelText = antagList[0].AntagonistName;

                foreach (var antag in antagList)
                {
                    var playerButton = new Button
                    {
                        Text = antag.Name,
                        TextAlign = Label.AlignMode.Right,
                        HorizontalAlignment = HAlignment.Center,
                        VerticalAlignment = VAlignment.Center,
                        SizeFlagsStretchRatio = 1,
                        ModulateSelfOverride = buttonColor, // WWDP EDIT
                        ToolTip = Loc.GetString(antag.AntagonistDescription),
                        TooltipDelay = 0.1f,
                        SetWidth = 180,
                        ClipText = true,
                    };

                    playerButton.Label.ModulateSelfOverride = GetTextColor(buttonColor);

                    playerButton.OnPressed += _ => WarpClicked?.Invoke(antag.Entity);

                    departmentBox.AddChild(playerButton); // WWDP EDIT
                }

                var departmentLabel = new Label
                {
                    Text = Loc.GetString(labelText) + $": {antagList.Count}",
                    StyleClasses = { "LabelSecondaryColor" }
                };

                mainContainer.AddChild(departmentLabel); // WWDP EDIT
                mainContainer.AddChild(departmentBox); // WWDP EDIT
            }

            GhostTeleportContainer.AddChild(mainContainer); // WWDP EDIT
        }

        private Control CreateSectionHeader(string text, bool useStripeBack = true)
        {
            if (useStripeBack)
            {
                var stripe = new StripeBack()
                {
                    HorizontalExpand = true // WWDP EDIT
                };
                var label = new Label
                {
                    Text = Loc.GetString(text),
                    StyleClasses = { "LabelBig" },
                    Align = Label.AlignMode.Center,
                };
                stripe.AddChild(label);

                return stripe;
            }
            else
            {
                var label = new Label
                {
                    Text = Loc.GetString(text),
                    StyleClasses = { "LabelBig" },
                    Align = Label.AlignMode.Center,
                };

                return label;
            }
        }

        public List<List<GhostWarpPlayer>> SortPlayersByDepartment(List<GhostWarpPlayer> players)
        {
            if (players.Count == 0)
                return new List<List<GhostWarpPlayer>>();

            return players
                .GroupBy(GetPlayerWeights)
                .OrderByDescending(g => g.Key)
                .Select(g => g.ToList())
                .ToList();
        }

        private int GetPlayerWeights(GhostWarpPlayer player)
        {
            if (!_prototypeManager.TryIndex<DepartmentPrototype>(player.DepartmentID, out var departmentPrototype))
            {
                Logger.Error($"Error while getting player weights {player.Name} for department {player.DepartmentID}");
                return 0;
            }
            return departmentPrototype.Weight;
        }

        private int GetAntagWeights(GhostWarpGlobalAntagonist antag)
        {
            if (!_prototypeManager.TryIndex<AntagonistPrototype>(antag.PrototypeID, out var antagonistPrototype))
            {
                Logger.Error($"Error while getting {antag.Name} weights antag {antag.PrototypeID}");
                return 0;
            }
            return antagonistPrototype.Weight;
        }

        public List<List<GhostWarpGlobalAntagonist>> SortAntagsByWeight(List<GhostWarpGlobalAntagonist> antagonists)
        {
            if (antagonists.Count == 0)
                return new List<List<GhostWarpGlobalAntagonist>>();

            return antagonists
                .GroupBy(GetAntagWeights)
                .OrderBy(g => g.Key)
                .Select(g => g.ToList())
                .ToList();
        }

        private List<GhostWarpPlace> GetSortedPlaces(List<GhostWarpPlace> places)
        {
            return places
                .OrderBy(w => w.Name)
                .ToList();
        }

        private List<GhostWarpPlayer> GetSortedPlayers(List<GhostWarpPlayer> players)
        {
            return players
                .OrderBy(w => w.Name)
                .ToList();
        }

        private List<GhostWarpGlobalAntagonist> GetSortedAntagonists(List<GhostWarpGlobalAntagonist> antagonists)
        {
            return antagonists
                .OrderBy(w => w.Name)
                .ToList();
        }

        private void PlayersAllocation()
        {
            _alivePlayers = _playerWarps.Where(warp => warp.IsAlive).ToList();
            _deadPlayers = _playerWarps.Where(warp => warp.IsDead).ToList();
            _leftPlayers = _playerWarps.Where(warp => warp.IsLeft).ToList();
            _ghostPlayers = _playerWarps.Where(warp => warp.IsGhost).ToList();
        }
        // Orion-End

        // WWDP START
        public static Color GetTextColor(Color background)
        {
            // Perceived luminance formula
            double luminance = (0.299 * background.R +
                0.587 * background.G +
                0.114 * background.B);

            // Light background -> dark text, dark background -> light text
            return luminance > 0.5 ? Color.Black : Color.White;
        }
        //WWDP END
    }
}
