- type: job
  id: MaxTacCommander
  name: Штурм командир Макс-Так
  description: job-description-maxtac-commander
  playTimeTracker: JobMaxTacCommander
  weight: 5
  salary: 1800
  startingGear: MaxTacCommanderGear
  supervisors: job-supervisors-centcom
  access:
    - MaxTac_Command
    - MaxTac_General
    - MaxTac_Armory
    - NCPD_Command
    - NCPD_Patrol
    - NCPD_Armory
    - NCPD_Detective
    - NC_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: MapBeacon
      group: NCPD
      color: "#ffaa00"
      icon: /Textures/Interface/VerbIcons/star-solid-yellow.svg.192dpi.png
      visibleInWorld: false

- type: startingGear
  id: MaxTacCommanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetHardsuitSecurityRed
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetAltSecurity
    id: MaxTacCommanderPDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterHardsuitSecurityRed
