- type: job
  id: MaxTacNetrunner
  name: Нетраннер Макс-Так
  description: job-description-maxtac-netrunner
  playTimeTracker: JobMaxTacNetrunner
  weight: 5
  startingGear: MaxTacNetrunnerGear
  supervisors: job-supervisors-maxtac-commander
  access:
    - Security
    - Brig
    - Research
    - Maintenance
    - External

- type: startingGear
  id: MaxTacNetrunnerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMaxTacNetrunner
    back: ClothingBackpackSatchelSecurity
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetHardsuitMaxTacNetrunner
    ears: ClothingHeadsetSecurity
    id: SciencePDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterHardsuitMaxTacNetrunner
