- type: job
  id: MaxTacNetrunner
  name: Нетраннер Макс-Так
  description: job-description-maxtac-netrunner
  playTimeTracker: JobMaxTacNetrunner
  requirements:
    - !type:RoleTimeRequirement
      role: JobNCPDSergeant
      time: 18000 # 5 hours
  weight: 5
  startingGear: MaxTacNetrunnerGear
  icon: "JobIconMaxTacNetrunner"
  supervisors: job-supervisors-maxtac-commander
  access:
    - Security
    - Brig
    - Research
    - Maintenance
    - External

- type: startingGear
  id: MaxTacNetrunnerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMaxTacNetrunner
    back: ClothingBackpackSatchelSecurity
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetHardsuitMaxTacNetrunner
    ears: ClothingHeadsetSecurity
    id: ResearchPDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterHardsuitMaxTacNetrunner
