- type: job
  id: MaxTacOperative
  name: Оперативник Макс-Так
  description: job-description-maxtac-operative
  playTimeTracker: JobMaxTacOperative
  weight: 10
  startingGear: MaxTacOperativeGear
  supervisors: job-supervisors-maxtac-commander
  access:
    - MaxTac_General
    - MaxTac_Armory
    - NCPD_Patrol
    - NC_General

- type: startingGear
  id: MaxTacOperativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetHardsuitSecurity
    ears: ClothingHeadsetAltSecurity
    id: SecurityPDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterHardsuitSecurity
