using Content.Shared._White.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Network;

namespace Content.Client._White.UserInterface.Windows;

[GenerateTypedNameReferences]
public sealed partial class PremiumPassWindow : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public PremiumPassWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        PurchaseButton.OnPressed += OnButtonPress;
    }

    private void OnButtonPress(Button.ButtonEventArgs args)
    {
        _cfg.SetCVar(WhiteCVars.PremiumActive, true);
        PurchaseButton.Visible = false;
        PurchasedButton.Visible = true;
    }

}
