using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Content.Shared._NC.Netrunning.Components;
using Robust.Shared.GameObjects;
using System.Collections.Generic;
using System;

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class CyberdeckWindow : DefaultWindow
{
    public CyberdeckWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public event Action<NetEntity>? OnProgramSelected;

    public void UpdateState(int currentRam, int maxRam, List<(string, NetEntity, NetProgramData)>? programs = null, string? targetName = null)
    {
        RamBar.MaxValue = maxRam;
        RamBar.Value = currentRam;
        RamText.Text = $"{currentRam} / {maxRam} RAM";

        TargetLabel.Text = targetName != null ? $"Active Target: {targetName}" : "No Target";
        TargetLabel.FontColorOverride = targetName != null ? Color.Red : Color.Gray;

        if (programs == null) return;

        ProgramList.Children.Clear();
        foreach (var (name, id, program) in programs)
        {
            var btn = new Button
            {
                Text = $"{name} ({program.RamCost} RAM)",
                ToolTip = $"Type: {program.ProgramType}\nCost: {program.RamCost} RAM, {program.EnergyCost} Energy",
                HorizontalExpand = true
            };
            btn.OnPressed += _ => OnProgramSelected?.Invoke(id);
            ProgramList.AddChild(btn);
        }
    }
}
