using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Content.Shared._NC.Netrunning.Components;
using Robust.Shared.GameObjects;
using System.Collections.Generic;
using System;

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class CyberdeckWindow : DefaultWindow
{
    public CyberdeckWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public event Action<NetEntity>? OnProgramSelected;
    public event Action<NetEntity>? OnTargetSelected; // Added event

    public void UpdateState(int currentRam, int maxRam, List<(string, NetEntity, NetProgramData)>? programs = null, string? targetName = null, Dictionary<NetEntity, string>? devices = null)
    {
        RamBar.MaxValue = maxRam;
        RamBar.Value = currentRam;
        RamText.Text = $"{currentRam} / {maxRam} RAM";

        TargetLabel.Text = targetName != null ? $"Цель: {targetName}" : "Нет цели";
        TargetLabel.FontColorOverride = targetName != null ? Color.Red : Color.Gray;

        if (programs != null)
        {
            ProgramList.Children.Clear();
            foreach (var (name, id, program) in programs)
            {
                var btn = new Button
                {
                    Text = $"{name} ({program.RamCost} RAM)",
                    ToolTip = $"Тип: {program.ProgramType}\nЦена: {program.RamCost} RAM, {program.EnergyCost} Энергия",
                    HorizontalExpand = true
                };
                btn.OnPressed += _ => OnProgramSelected?.Invoke(id);
                ProgramList.AddChild(btn);
            }
        }

        // Update Device List
        if (devices != null)
        {
            DeviceList.Children.Clear();
            foreach (var (id, name) in devices)
            {
                var btn = new Button
                {
                    Text = name,
                    HorizontalExpand = true
                };
                btn.OnPressed += _ => OnTargetSelected?.Invoke(id);
                DeviceList.AddChild(btn);
            }
        }
    }

    protected override void Opened()
    {
        base.Opened();
    }
}
