using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._NC.Netrunning.UI;

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class NetMapWindow : DefaultWindow
{
    public event Action<NetEntity, NetMapAction>? OnInteract;

    public NetMapWindow()
    {
        RobustXamlLoader.Load(this);
        NavMap.OnInteract += (entity, action) => OnInteract?.Invoke(entity, action);
    }

    public void UpdateState(NetMapBoundUiState state)
    {
        NavMap.UpdateState(state);
    }
}
