using Content.Client.UserInterface.Controls;
using Content.Shared._NC.Netrunning.UI;
using Content.Shared._NC.Netrunning.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Client.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Robust.Shared.GameObjects;
using Robust.Client.UserInterface;
using System.Linq;
using System.Numerics; // Correct Vector2

namespace Content.Client._NC.Netrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class NetServerWindow : DefaultWindow
{
    public event Action<string, string>? OnPasswordSet;
    public event Action? OnOpenMap;

    public NetServerWindow()
    {
        RobustXamlLoader.Load(this);
        OpenMapButton.OnPressed += _ => OnOpenMap?.Invoke();
    }

    public void UpdateState(NetServerBoundUiState state)
    {
        ServerNameLabel.Text = $"Server: {state.ServerName}";

        PowerStatusLabel.Text = state.IsPowered ? "Online" : "Offline";
        PowerStatusLabel.FontColorOverride = state.IsPowered ? Color.Green : Color.Red;

        ApcStatusLabel.Text = state.HasApc ? "Connected" : "Disconnected";
        ApcStatusLabel.FontColorOverride = state.HasApc ? Color.Green : Color.Red;

        // Render Slots (Left)
        SlotsContainer.RemoveAllChildren();
        foreach (var slot in state.Slots)
        {
            var slotBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(0, 5) };

            var headerText = $"{slot.SlotLabel}";
            if (slot.HasIce)
            {
                headerText += $" [{slot.IceType}]: {slot.ItemName}";
            }
            else if (!string.IsNullOrEmpty(slot.ItemName))
            {
                headerText += $": {slot.ItemName}";
            }
            else
            {
                headerText += ": Empty";
            }

            slotBox.AddChild(new Label { Text = headerText, FontColorOverride = slot.HasIce ? Color.Cyan : Color.Gray });

            if (slot.HasIce && slot.IceType == NetIceType.Gate)
            {
                var pwdBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

                var input = new LineEdit
                {
                    Text = slot.InitPassword,
                    PlaceHolder = "####",
                    HorizontalExpand = true
                };

                input.OnTextChanged += (evt) =>
                {
                    var text = evt.Text;
                    var filtered = new string(text.Where(char.IsDigit).Take(4).ToArray());
                    if (text != filtered)
                    {
                        input.Text = filtered;
                        input.CursorPosition = filtered.Length;
                    }
                };

                var btn = new Button { Text = "Set" };
                btn.OnPressed += _ => OnPasswordSet?.Invoke(slot.SlotName, input.Text);
                pwdBox.AddChild(input);
                pwdBox.AddChild(btn);
                slotBox.AddChild(pwdBox);
            }

            SlotsContainer.AddChild(slotBox);
            SlotsContainer.AddChild(new PanelContainer { StyleClasses = { "LowDivider" } });
        }

        // Render Devices (Right)
        DevicesContainer.RemoveAllChildren();

        var spriteSys = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        var protoMan = IoCManager.Resolve<IPrototypeManager>();

        foreach (var dev in state.Devices)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(2) };

            // Icon
            if (!string.IsNullOrEmpty(dev.ProtoId) && protoMan.TryIndex(dev.ProtoId, out EntityPrototype? proto))
            {
                var texture = spriteSys.GetPrototypeIcon(proto).Default;
                var icon = new TextureRect
                {
                    Texture = texture,
                    SetSize = new Vector2(32, 32),
                    Stretch = TextureRect.StretchMode.KeepAspectCentered
                };
                row.AddChild(icon);
            }
            else
            {
                // Placeholder
                row.AddChild(new Control { MinSize = new Vector2(32, 32) });
            }

            // Name
            var nameLabel = new Label { Text = dev.Name, HorizontalExpand = true, ClipText = true, Margin = new Thickness(5, 0) };
            row.AddChild(nameLabel);

            // Status
            var statusLabel = new Label
            {
                Text = dev.IsPowered ? "ON" : "OFF",
                FontColorOverride = dev.IsPowered ? Color.Green : Color.Red
            };
            row.AddChild(statusLabel);

            DevicesContainer.AddChild(row);
        }
    }
}
