using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcListingPriceButtonControl : Button
{
    public NcListingPriceButtonControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetCurrencyIcon(Texture? texture)
    {
        CurrencyIcon.Texture = texture;
        CurrencyIcon.Visible = texture != null;
    }

    public void SetPriceText(string text)
    {
        PriceLabel.Text = text;
    }
}
