using Content.Shared._NC.Trade;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._NC.Trade.Controls;

/// <summary>
/// Standardized info block for store listings (no stock / remaining / owned).
/// Keeps label styling in XAML and exposes a minimal API to update values.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class NcListingStockInfoControl : BoxContainer
{
    public NcListingStockInfoControl()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Updates all labels and returns whether the listing currently has stock (Remaining != 0).
    /// </summary>
    public bool Update(StoreMode mode, int remaining, int owned)
    {
        var hasStock = remaining != 0;

        NoStockLabel.Visible = !hasStock;
        if (!hasStock)
        {
            NoStockLabel.Text = mode == StoreMode.Buy
                ? Loc.GetString("nc-store-no-stock")
                : Loc.GetString("nc-store-buying-finished");
        }

        if (remaining >= 0)
        {
            RemainingLabel.Visible = true;
            RemainingLabel.Text = mode == StoreMode.Buy
                ? Loc.GetString("nc-store-remaining", ("count", remaining))
                : Loc.GetString("nc-store-will-buy", ("count", remaining));
        }
        else
        {
            RemainingLabel.Visible = false;
        }

        OwnedLabel.Visible = owned > 0;
        if (owned > 0)
            OwnedLabel.Text = Loc.GetString("nc-store-owned", ("count", owned));

        return hasStock;
    }
}
