using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcListingsPane : PanelContainer
{
    private string _key = string.Empty;

    private ScrollContainer? _scroll;
    private BoxContainer? _host;

    public bool RememberScrollPerKey { get; set; } = false;

    public NcListingsPane()
    {
        RobustXamlLoader.Load(this);
        RectClipContent = true;

        RebuildScroll(resetToTop: true, preserveContent: false);
    }

    public void SetContent(Control content)
    {
        EnsureBuilt();

        _host!.RemoveAllChildren();
        _host.AddChild(content);
    }

    public void SetKey(string? key)
    {
        key ??= string.Empty;

        if (_key == key)
            return;

        _key = key;

        RebuildScroll(resetToTop: true, preserveContent: true);
    }

    public void ResetScroll()
    {
        RebuildScroll(resetToTop: true, preserveContent: true);
    }

    private void EnsureBuilt()
    {
        if (_scroll != null && _host != null)
            return;

        RebuildScroll(resetToTop: true, preserveContent: false);
    }

    private void RebuildScroll(bool resetToTop, bool preserveContent)
    {
        List<Control>? preserved = null;

        if (preserveContent && _host != null)
        {
            preserved = new List<Control>();
            foreach (var child in _host.Children)
            {
                if (child is Control c)
                    preserved.Add(c);
            }

            foreach (var c in preserved)
                _host.RemoveChild(c);
        }

        ScrollHost.RemoveAllChildren();

        _scroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            HScrollEnabled = false
        };

        _host = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,

            Margin = new Thickness(0, 0, 14, 0)
        };

        _scroll.AddChild(_host);
        ScrollHost.AddChild(_scroll);

        if (preserved != null)
        {
            foreach (var c in preserved)
                _host.AddChild(c);
        }

        _ = resetToTop;
    }
}
