using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcListingDescriptionBox : PanelContainer
{
    public NcListingDescriptionBox()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetDescription(string? fullText, int maxChars)
    {
        var full = fullText ?? string.Empty;

        if (string.IsNullOrWhiteSpace(full))
        {
            Visible = false;
            Label.Visible = false;
            Label.ToolTip = null;
            Label.SetMessage(new FormattedMessage());
            return;
        }

        Visible = true;
        Label.Visible = true;

        var trimmed = TrimToChars(full, maxChars);

        var msg = new FormattedMessage();
        msg.AddText(trimmed);

        Label.SetMessage(msg);
        Label.ToolTip = full;

        UpdateMaxWidth();
    }

    protected override void Resized()
    {
        base.Resized();
        UpdateMaxWidth();
    }

    private void UpdateMaxWidth()
    {
        var w = Size.X;
        if (w > 0)
            Label.MaxWidth = MathF.Max(0, w);
    }

    private static string TrimToChars(string s, int maxChars)
    {
        if (maxChars <= 0 || s.Length <= maxChars)
            return s;

        return s[..maxChars].TrimEnd() + "…";
    }
}

