using System;
using Content.Shared._NC.Trade;
using Content.Shared.Stacks;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._NC.Trade.Controls;

[GenerateTypedNameReferences]
public sealed partial class NcStoreListingControl : PanelContainer
{
    private const int MaxTotalDisplay = 999_999;
    private const int DescMaxChars = 220;

    private readonly bool _actionsEnabled;
    private readonly IUserInterfaceManager _ui = IoCManager.Resolve<IUserInterfaceManager>();

    private int _maxQty;
    private int _qty;
    private StoreListingData _staticData;

    public NcStoreListingControl(
        StoreListingData data,
        SpriteSystem sprites,
        IEntityManager entMan,
        int balanceHint = int.MaxValue,
        int initialQty = 1,
        bool actionsEnabled = true
    )
    {
        RobustXamlLoader.Load(this);

        _staticData = data;
        _actionsEnabled = actionsEnabled;

        var pm = IoCManager.Resolve<IPrototypeManager>();
        pm.TryIndex<EntityPrototype>(data.ProductEntity, out var proto);

        TitleLabel.Text = proto?.Name ?? data.ProductEntity;
        TitleLabel.ToolTip = proto?.Name ?? data.ProductEntity;

        if (data.Mode == StoreMode.Buy && data.UnitsPerPurchase > 1)
        {
            TitleLabel.Text = $"{TitleLabel.Text} ×{data.UnitsPerPurchase}";
            TitleLabel.ToolTip = TitleLabel.Text;
        }


        if (proto != null)
        {
            IconView.SetPrototype(proto.ID);
            NcUiIconFit.Fit(IconView, sprites, proto.ID, targetPx: 96, paddingPx: 8);
        }
        else
        {
            IconSlotBackground.Visible = false;
            IconDivider.Visible = false;
        }
        SetDescription(proto);

        SetupPriceButton(data, sprites, pm);

        SetupQtyLogic(data, balanceHint, initialQty);

        UpdateLabelsAndVisibility(data);
    }

    public Action<int>? OnBuyPressed { get; set; }
    public Action<int>? OnSellPressed { get; set; }
    public Action<int>? OnQtyChanged { get; set; }

    public string UiId => _staticData.Id;
    public string ListingId => _staticData.ListingId;
    public StoreListingFlavor Flavor => _staticData.Flavor;
    private int MinAllowed => _maxQty <= 0 ? 0 : 1;

    private void SetDescription(EntityPrototype? proto)
    {
        DescriptionBox.SetDescription(proto?.Description, DescMaxChars);
    }


    private void SetupPriceButton(StoreListingData data, SpriteSystem sprites, IPrototypeManager pm)
    {
        if (!string.IsNullOrEmpty(data.CurrencyId) &&
            pm.TryIndex<StackPrototype>(data.CurrencyId, out var stack) &&
            pm.TryIndex<EntityPrototype>(stack.Spawn, out var ent) &&
            sprites.GetPrototypeIcon(ent.ID).Default is { } currencyTex)
        {
            PriceButton.SetCurrencyIcon(currencyTex);
        }
        else
            PriceButton.SetCurrencyIcon(null);

        if (!_actionsEnabled)
            PriceButton.ToolTip = Loc.GetString("nc-store-only-mass-sell");

        PriceButton.OnPressed += _ =>
        {
            if (!_actionsEnabled || _maxQty <= 0 || _qty <= 0)
                return;

            switch (data.Mode)
            {
                case StoreMode.Buy:
                    OnBuyPressed?.Invoke(_qty);
                    break;
                case StoreMode.Sell:
                    OnSellPressed?.Invoke(_qty);
                    break;
            }
        };
    }

    private void SetupQtyLogic(StoreListingData data, int balanceHint, int initialQty)
    {
        CalculateMaxQty(data, balanceHint);
        _qty = Math.Clamp(initialQty, MinAllowed, Math.Max(MinAllowed, _maxQty));

        var noQty = _maxQty <= 0 || !_actionsEnabled;
        var disabledTip = !_actionsEnabled ? Loc.GetString("nc-store-only-mass-sell") : null;

        QtyControl.Configure(MinAllowed, _maxQty, _qty, enabled: !noQty, disabledTooltip: disabledTip);

        QtyControl.OnValueChanged += v =>
        {
            _qty = v;
            UpdatePriceAndButtons();
            OnQtyChanged?.Invoke(_qty);
        };

        QtyControl.OnEnter += () =>
        {
            if (!_actionsEnabled || _maxQty <= 0 || _qty <= 0)
                return;

            if (data.Mode == StoreMode.Buy)
                OnBuyPressed?.Invoke(_qty);
            else if (data.Mode == StoreMode.Sell)
                OnSellPressed?.Invoke(_qty);
        };
    }

    private void CalculateMaxQty(StoreListingData data, int balanceHint)
    {
        var remainingCap = data.Remaining >= 0 ? data.Remaining : int.MaxValue;
        var ownedCap = data.Mode == StoreMode.Sell ? data.Owned : int.MaxValue;
        var moneyCap = data.Mode == StoreMode.Buy && data.Price > 0
            ? balanceHint / data.Price
            : int.MaxValue;

        _maxQty = Math.Min(remainingCap, Math.Min(ownedCap, moneyCap));
    }

    public void UpdateIdentity(StoreListingData newData) => _staticData = newData;

    public void UpdateDynamicData(int playerBalance, int remainingStock, int playerOwned)
    {
        _staticData.Remaining = remainingStock;
        _staticData.Owned = playerOwned;

        CalculateMaxQty(_staticData, playerBalance);

        var minAllowed = _maxQty <= 0 ? 0 : 1;
        var clamped = Math.Clamp(_qty, minAllowed, Math.Max(minAllowed, _maxQty));

        // Update limits first so the picker can clamp itself.
        var noQty = _maxQty <= 0 || !_actionsEnabled;
        var disabledTip = !_actionsEnabled ? Loc.GetString("nc-store-only-mass-sell") : null;
        QtyControl.SetLimits(minAllowed, _maxQty);
        QtyControl.SetEnabled(!noQty, disabledTip);

        if (clamped != _qty)
        {
            _qty = clamped;
            if (!QtyControl.IsEditing(_ui))
                QtyControl.SetValue(_qty, notify: false);
            OnQtyChanged?.Invoke(_qty);
        }

        UpdatePriceAndButtons();
        UpdateLabelsAndVisibility(_staticData);
    }

    private void UpdatePriceAndButtons()
    {
        var noQty = _maxQty <= 0 || !_actionsEnabled;

        var disablePrice = !_actionsEnabled || noQty ||
            _staticData.Remaining == 0 ||
            _staticData.Mode == StoreMode.Sell && _staticData.Owned <= 0;

        PriceButton.Disabled = disablePrice;
        UpdateTotalPrice(_staticData);
    }

    private void UpdateLabelsAndVisibility(StoreListingData data)
    {
        // Stock info block drives all label text/visibility and also tells us whether to show price.
        var hasStock = StockInfo.Update(data.Mode, data.Remaining, data.Owned);

        PriceButton.Visible = hasStock;
        if (hasStock)
            UpdateTotalPrice(data);
    }

    private void UpdateTotalPrice(StoreListingData data)
    {
        var value = _qty <= 0 ? data.Price : (long) data.Price * _qty;
        PriceButton.SetPriceText(value > MaxTotalDisplay ? $"{MaxTotalDisplay}+" : value.ToString());
    }
}
