- type: job
  id: HoSMilitech
  name: job-name-hosm
  description: job-description-hosm
  playTimeTracker: JobHoSM
  startingGear: HoSecGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
  - SecurityMilitech
  - Militech
  - ArmoryMilitech


- type: startingGear
  id: HoSecGear
  equipment:
    id: HoPPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey