using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._White.UserInterface.Systems.AdminObserver.Widgets;

[GenerateTypedNameReferences]
public sealed partial class AdminObserverHandsGui : UIWidget
{
    public AdminObserverHandsGui()
    {
        RobustXamlLoader.Load(this);
        var controller = UserInterfaceManager.GetUIController<AdminObserverHandsUIController>();

        HandsButton.OnToggled += _ => controller.ToggleHands();
    }

    public void OnHandsUpdated(bool handsEnabled)
    {
        HandsButton.TexturePath = handsEnabled
            ? "/Textures/_White/Interface/AdminObserver/hands_on.png"
            : "/Textures/_White/Interface/AdminObserver/hands_off.png";
        HandsButton.Pressed = handsEnabled;
    }
}
