using Content.Shared._NC.Ncpd;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Maths;
using System;

namespace Content.Client._NC.Ncpd;

[GenerateTypedNameReferences]
public sealed partial class NcpdCaptainConsoleWindow : DefaultWindow
{
    public event Action<string>? OnPurchase;
    public event Action<NetEntity>? OnRevoke;
    public event Action? OnClearLogs;
    public event Action<int>? OnWithdraw;
    public event Action<int>? OnDeposit;

    public NcpdCaptainConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        Tabs.SetTabTitle(0, "АУДИТ ШТРАФОВ");
        Tabs.SetTabTitle(1, "БЮДЖЕТ");

        ClearLogsButton.OnPressed += _ => OnClearLogs?.Invoke();

        WithdrawButton.OnPressed += _ =>
        {
            if (int.TryParse(WithdrawAmountInput.Text, out var amount) && amount > 0)
            {
                OnWithdraw?.Invoke(amount);
                WithdrawAmountInput.Text = string.Empty;
            }
        };

        DepositButton.OnPressed += _ =>
        {
            if (int.TryParse(WithdrawAmountInput.Text, out var amount) && amount > 0)
            {
                OnDeposit?.Invoke(amount);
                WithdrawAmountInput.Text = string.Empty;
            }
        };
    }

    public void UpdateState(NcpdCaptainConsoleBuiState state)
    {
        BudgetLabel.Text = $"БЮДЖЕТ ДЕПАРТАМЕНТА: {state.Budget} Эдди";
        DepositButton.Text = $"ВНЕСТИ ({state.InsertedCash} Эдди)";
        DepositButton.Disabled = state.InsertedCash <= 0;

        // Обновляем Аудит Штрафов (Вкладка 0)
        LogsContainer.RemoveAllChildren();
        // Обновляем Финансовые Логи (Вкладка 1)
        FinancialLogsContainer.RemoveAllChildren();

        foreach (var log in state.Logs)
        {
            var logVbox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 5)
            };

            var logLabel = new Label();
            if (log.Status.Contains("СНЯТИЕ") || log.Status.Contains("ПОПОЛНЕНИЕ") || log.Status.Contains("ЗАКУПКА"))
            {
                // Финансовые операции — во вторую вкладку
                logLabel.Text = $"{log.Time:hh\\:mm\\:ss} | {log.OfficerName} | {log.Status} | Сумма: {log.Amount}";
                logLabel.FontColorOverride = log.Status.Contains("СНЯТИЕ") ? Color.Orange : Color.LimeGreen;
                logVbox.AddChild(logLabel);
                FinancialLogsContainer.AddChild(logVbox);
            }
            else
            {
                // Штрафы — в первую вкладку
                logLabel.Text = $"{log.Time:hh\\:mm\\:ss} | {log.OfficerName} | Оштрафовал: {log.TargetName} | Сумма: {log.Amount} | {log.Status}";
                logLabel.FontColorOverride = log.Status.Contains("ПРИНУДИТЕЛЬНОЕ") ? Color.OrangeRed : Color.LimeGreen;
                logVbox.AddChild(logLabel);

                if (!string.IsNullOrWhiteSpace(log.Reason))
                {
                    logVbox.AddChild(new Label
                    {
                        Text = $"   ПРИЧИНА: {log.Reason}",
                        FontColorOverride = Color.FromHex("#aaaaaa"),
                        Margin = new Thickness(20, 0, 0, 0)
                    });
                }
                LogsContainer.AddChild(logVbox);
            }
        }
    }
}
